### ISSUE TITLE
Tabula converts numbers in address filed to a date

### ISSUE THREAD

**Issue by intotecho** [tabulapdf/tabula#1017]
Input PDF table has addresses like:

Wall 	Street	1/2-4	
Wall 	Street	2/2-4	
Wall 	Street	3/2-4

Output is like:

Wall | Street | 1/02/2004 
Wall | Street | 2/02/2004 
Wall | Street | 3/02/2004 

It would be good to have an option to turn off conversion to date.

**Comment by jeremybmerrill** [comment]
Hi @intotecho, that's a behavior of Microsoft Excel that's doing that automatic conversion. If you examine Tabula's CSV output in a text editor (or in the preview pane in the Tabula web app), you'll see that Tabula exported the data exactly as it was in the input PDF.

**Comment by intotecho** [comment]
Apologies. Yes, i ran the conversion again and confirmed it is excel.
