### ISSUE TITLE
Confusion possible when working with the command line interface: -a option vs. the JSON with dimensions format

### ISSUE THREAD

**Issue by hexastax** [tabulapdf/tabula#1037]
I've got Tabula 1.2.1 for Mac installed and working generally, the app is up, I'm able to load a PDF file, highlight tables, extract them in the app, etc.

However, the export feature does not produce the same data for some of the formats.

For instance, I selected "script" and got:

`java -jar tabula-java.jar  -a 485.393,45.135,722.543,566.865 -p 1 "$1" `

Then I selected JSON with dimensions and got:

`[{"page":1,"extraction_method":"stream","selection_id":"T1564293407042","x1":45.135,"x2":566.865,"y1":485.3925,"y2":722.5425,"width":521.73,"height":237.15,"spec_index":0}]`

As you can see, the script has

x1 = 485.393
y1 = 45.135
x2 = 722.543
y2 = 566.865

and the JSON with dimensions export has

"x1":45.135
"y1":485.3925
"x2":566.865
"y2":722.5425

From testing via the command line, the script has the right coordinates and the JSON does not. It's got x1 that's actually y1, it's got y1 that's actually x1, and x2 that's actually y2 and y2 that's actually x2.

Anyone else seeing this?

**Comment by jeremybmerrill** [comment]
Hi @hexastax, I believe this is all correct behavior. The command line script [accepts dimensions](https://github.com/tabulapdf/tabula-java#usage-examples) in `top,left,bottom,right` order, aka `y1,x1,y2,x2`. This is a little confusing, I realize. :)

**Comment by hexastax** [comment]
Hi Jeremy,

So the doc says

>  -a,--area <AREA>           Portion of the page to analyze. Accepts top, left,bottom,right.  Example: --area 269.875,12.75,790.5,561.

I'm sorry but I can't seem to follow how 

`-a 485.393,45.135,722.543,566.865`

can the processed the same way as

> "x1":45.135,"x2":566.865,"y1":485.3925,"y2":722.5425,"width":521.73,"height":237.15

That just does not look correct.

To me, in the JSON, x1 is actually y1, y1 is actually x1, and x2 is actually y2 and y2 is actually x2.

Simply going by what I see, this looks wrong to me. The "script" format is correct though.

**Comment by jeremybmerrill** [comment]
`-a 485.393,45.135,722.543,566.865` is the same as
`   top,    left,  bottom, right` which is the same as
`   y1,     x1,    y2,      , x2`

Both methods of specifying the rectangle are semantically identical, though I recognize that the CLI app's `y1,x1,y2,x2` format is unconventional.

According to both the JSON and the CLI specification, the rectangle you appear to be specifying is twice as long as it is tall, right?

**Comment by hexastax** [comment]
Yes, just re-edited my comment :)

Um "top, left, bottom, right which is the same as y1, x1, y2, x2"... err I can't see that as intuitive :)

**Comment by hexastax** [comment]
I'm realizing that changing the order in the -a arguments may be drastic :)

> -a,--area Portion of the page to analyze. Accepts top, left,bottom,right.

I'd be happy to make a pull request to clarify the doc there to say, "y coordinate of the top level corner, x coordinate of the top left corner, y coordinate of the bottom right corner, x coordinate of the bottom right corner".

Would that be useful in your opinion?

**Comment by jeremybmerrill** [comment]
I can certainly see it not seeming entirely intuitive! 

As you say, though, we're not likely to change it, on account of wanting to maintain backwards compatibility.

I was going to change it to something like this.
```
-a/--area = Portion of the page to analyze. Example: --area 269.875,12.75,790.5,561. 
Accepts top,left,bottom,right i.e. y1,x1,y2,x2 
```
Do you think that would accomplish the same goal? Happy to continue to wordsmith.

**Comment by hexastax** [comment]
I think the "i.e." is definitely helpful, for sure.

The top, left, bottom, right continue to be confusing to me :)

Another thing that puzzled me a bit is the concept of "apply to all pages" and apply to next page. If you want to export a template, you'll see a rectangle applied to all the pages of the document you imported to create the template.

However, other documents that adhere to the same format may have fewer or more pages.

I guess what I'm saying is that there doesn't seem to be a way to capture the "apply to all pages" rule.  Unless I've missed it.

**Comment by jeremybmerrill** [comment]
You're right that the JSON templates don't carry over that command. You'd be welcome to open up a feature-enhancement request for that.

**Comment by jeremybmerrill** [comment]
I made that change to the README/`help` docs, btw. Thanks for raising this issue!

**Comment by hexastax** [comment]
Thanks, Jeremy. Super quick fix! :)

I'll file the feature enh for capturing the pages/all.
