### ISSUE TITLE
Dockerfile not working: Missing class name pdfbox.pdmodel.PDDocument

### ISSUE THREAD

**Issue by philippschw** [tabulapdf/tabula#1043]
Hi everyone, 

I tried to use the Dockerfile to deploy tabula on my Linux, unfortunately, it does not work.
The image is being built successfully but tabula crashes immediately with the following error message:

```
DATA_DIR = /root/.tabula
DOCUMENTS_BASEPATH = /root/.tabula/pdfs
ENABLE_DEBUG_METHODS = true
NameError: missing class name (`org.apache.pdfbox.pdmodel.PDDocument')
                     method_missing at org/jruby/javasupport/JavaPackage.java:259
                             <main> at /app/lib/tabula_java_wrapper.rb:1
                            require at org/jruby/RubyKernel.java:956
                             (root) at uri:classloader:/jruby/kernel/kernel.rb:1
                             <main> at uri:classloader:/jruby/kernel/kernel.rb:13
                            require at org/jruby/RubyKernel.java:956
                             (root) at /app/webapp/tabula_web.rb:12
                    block in (root) at uri:classloader:/jruby/kernel/kernel.rb:1
                      instance_eval at org/jruby/RubyBasicObject.java:1691
                   require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
                             <eval> at /app/config.ru:14
                               eval at org/jruby/RubyKernel.java:995
                         initialize at /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:55
                    new_from_string at /app/config.ru:1
                    new_from_string at /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:49
                         parse_file at /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:40
  build_app_and_options_from_config at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:319
                                app at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:219
                        wrapped_app at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:354
                             <main> at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:283
                               load at org/jruby/RubyKernel.java:974
                             <main> at /usr/local/bundle/bin/rackup:29

```

**Comment by philippschw** [comment]
Using docker-compose and the docker-compose.yml file to start the application solved it for me. 
I suggest that the Dockerfile should be corrected or updated, for example the last two lines be removed and a note being added that hints to use the docker-compose file!

**Comment by himanshuchawla009** [comment]
Hii @philippschw , how did you managed to solve this error, I am facing same issue even running it with docker-compose.

**Comment by philippschw** [comment]
I use the following docker-compose file. 
```
version: '3'
services:
  tabula:
    container_name: tabula
    build:
      context: .
    command: "jruby -G -r jbundler -S rackup -p 9292 -o 0.0.0.0 config.ru"
    ports:
      - 9292:9292
```

What is your error?

**Comment by himanshuchawla009** [comment]
@philippschw  thanks for quick reply,

Here is my error:-

himanshu@himanshu-HP-EliteBook-840-G1:~/tabula$ docker-compose up
Starting tabula_web_1 ... done
Attaching to tabula_web_1
web_1  | DATA_DIR = /root/.tabula
web_1  | DOCUMENTS_BASEPATH = /root/.tabula/pdfs
web_1  | ENABLE_DEBUG_METHODS = false
web_1  | NameError: missing class name (`org.apache.pdfbox.pdmodel.PDDocument')
web_1  |                      method_missing at org/jruby/javasupport/JavaPackage.java:259
web_1  |                              <main> at /app/lib/tabula_java_wrapper.rb:1
web_1  |                             require at org/jruby/RubyKernel.java:956
web_1  |                              (root) at uri:classloader:/jruby/kernel/kernel.rb:1
web_1  |                              <main> at uri:classloader:/jruby/kernel/kernel.rb:13
web_1  |                             require at org/jruby/RubyKernel.java:956
web_1  |                              (root) at /app/webapp/tabula_web.rb:12
web_1  |                     block in (root) at uri:classloader:/jruby/kernel/kernel.rb:1
web_1  |                       instance_eval at org/jruby/RubyBasicObject.java:1691
web_1  |                    require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
web_1  |                              <eval> at /app/config.ru:14
web_1  |                                eval at org/jruby/RubyKernel.java:995
web_1  |                          initialize at /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:55
web_1  |                     new_from_string at /app/config.ru:1
web_1  |                     new_from_string at /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:49
web_1  |                          parse_file at /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:40
web_1  |   build_app_and_options_from_config at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:319
web_1  |                                 app at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:219
web_1  |                         wrapped_app at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:354
web_1  |                              <main> at /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:283
web_1  |                                load at org/jruby/RubyKernel.java:974
web_1  |                              <main> at /usr/local/bundle/bin/rackup:29
tabula_web_1 exited with code 1

**Comment by philippschw** [comment]
I dont know but try my Dockerfile:

```docker
FROM jruby:9.1-jdk

RUN apt-get update -qq && apt-get install -y build-essential
RUN echo 'gem: --no-rdoc --no-ri' >> /.gemrc

ENV GEM_HOME /usr/local/bundle
ENV PATH $GEM_HOME/bin:$PATH
RUN gem install bundler -v '< 2' \
  && bundle config --global path "$GEM_HOME" \
  && bundle config --global bin "$GEM_HOME/bin"

# don't create ".bundle" in all our apps
ENV BUNDLE_APP_CONFIG $GEM_HOME

WORKDIR /app

# these didn't work as ONBUILD, strangely. Idk why. -JBM
COPY Gemfile ./
COPY Gemfile.lock ./
COPY Jarfile ./
COPY Jarfile.lock ./
RUN bundle install --system
RUN jruby -S jbundle install
COPY . .


```

**Comment by himanshuchawla009** [comment]
Thanks man it worked with your dockerfile :). You saved my day :100:

**Comment by razorness** [comment]
Don't know why this is closed while bug still persists in repo. 
I had to use `docker-compose.yml ` as of https://github.com/tabulapdf/tabula/issues/1043#issuecomment-559485284 to fix this error.

Got same error: 
```

[...]

jbundle complete !

Removing intermediate container 47bd5429918d
 ---> 12a17c457aa8
Step 15/17 : COPY . .
 ---> c1695e2d71f9
Step 16/17 : EXPOSE 9292
 ---> Running in a2ce38b905f5
Removing intermediate container a2ce38b905f5
 ---> 20ea6cfbe1cf
Step 17/17 : CMD ["jruby", "-G", "-r", "jbundler", "-S", "rackup", "-o", "0.0.0.0", "config.ru"]
 ---> Running in 7eae91a42f3d
Removing intermediate container 7eae91a42f3d
 ---> 08f9b227a9d1

Successfully built 08f9b227a9d1
Successfully tagged tabula_web:latest
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating tabula_web_1 ... done
Attaching to tabula_web_1
web_1  | DATA_DIR = /root/.tabula
web_1  | DOCUMENTS_BASEPATH = /root/.tabula/pdfs
web_1  | ENABLE_DEBUG_METHODS = false
web_1  | NameError: missing class name (`org.apache.pdfbox.pdmodel.PDDocument')
web_1  |                      method_missing at org/jruby/javasupport/JavaPackage.java:259
web_1  |                              <main> at /app/lib/tabula_java_wrapper.rb:1
web_1  |                             require at org/jruby/RubyKernel.java:956
web_1  |                              (root) at uri:classloader:/jruby/kernel/kernel.rb:1
web_1  |                              <main> at uri:classloader:/jruby/kernel/kernel.rb:13
web_1  |                             require at org/jruby/RubyKernel.java:956
web_1  |                              (root) at /app/webapp/tabula_web.rb:12
web_1  |                     block in (root) at uri:classloader:/jruby/kernel/kernel.rb:1
web_1  |                       instance_eval at org/jruby/RubyBasicObject.java:1691
web_1  |                    require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
web_1  |                              <eval> at /app/config.ru:14
web_1  |                                eval at org/jruby/RubyKernel.java:995
web_1  |                          initialize at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/builder.rb:55
web_1  |                     new_from_string at /app/config.ru:1
web_1  |                     new_from_string at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/builder.rb:49
web_1  |                          parse_file at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/builder.rb:40
web_1  |   build_app_and_options_from_config at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/server.rb:319
web_1  |                                 app at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/server.rb:219
web_1  |                         wrapped_app at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/server.rb:354
web_1  |                              <main> at /usr/local/bundle/jruby/2.3.0/gems/rack-2.0.6/lib/rack/server.rb:283
web_1  |                                load at org/jruby/RubyKernel.java:974
web_1  |                              <main> at /usr/local/bundle/bin/rackup:29
tabula_web_1 exited with code 1
```

Env: 
- Fedora 31
- docker-ce `3:19.03.6-3.fc31`
- docker-compose `1.24.1-3.fc31`
