### ISSUE TITLE
Enter the file path in form control instead using the Button "Browse."

### ISSUE THREAD

**Issue by aunsid** [tabulapdf/tabula#1054]
Is there a way of entering the filepath in the form control in ```Xpath - " /html/body/div[2]/div/div/div[3]/form/div/input" ``` instead of choosing files using the Browse Button. I am trying to automate the process using selenium for python.

Thanks!

**Comment by jazzido** [comment]
Instead of automating the UI, you might want to use `tabula-java`, or one of its various wrappers for Python or R.

Cheers.
