### ISSUE TITLE
"It works!" but no functionality on macOS 10.14.6

### ISSUE THREAD

**Issue by apjanke** [tabulapdf/tabula#1055]
Hello! Thanks for writing and sharing Tabula.

I am a new Tabula user. I've tried to run Tabula by downloading Tabula 1.2.1 from https://github.com/tabulapdf/tabula/releases/download/v1.2.1/tabula-mac-1.2.1.zip as linked from your home page at https://tabula.technology/. I've followed the install instructions and am able to run Tabula, but after firing it up, I just get a plain web page in my browser saying "It works!" instead of a prompt or form to upload a file.

<img width="778" alt="Firefox browser showing just 'It Works!'" src="https://user-images.githubusercontent.com/2618447/65939047-bcc30900-e3f2-11e9-8c7b-bf87cfabf3c5.png">

I can't proceed with the instructions in "How to Use Tabula: 1. Upload a PDF...", since there seems to be no upload affordance here.

Any ideas what to do here?

I am running macOS 10.14.6 on a 2019 iMac Pro; Firefox 69.0.1; Tabula 1.2.1.

**Comment by jazzido** [comment]
Hi @apjanke — You have something else (most likely the Apache web server) running on port 8080. Try to shut it down, and then start Tabula again.

Thanks!

**Comment by apjanke** [comment]
That was it. User error. Thanks!
