### ISSUE TITLE
Data Privacy

### ISSUE THREAD

**Issue by vgerber350** [tabulapdf/tabula#1059]
Does Tabula have a data privacy policy or an NDA regarding use of data uploaded to be extracted? Looking for further detail and clarity on the treatment of data, particularly in the event of uploading PDFs that contain confidential or sensitive data (i.e. business terms). Please advise. Thank you!

**Comment by tomdupont** [comment]
The [README.md includes a section about security concerns](https://github.com/tabulapdf/tabula#why-tabula). Data is never leaving your network, its only "uploading" to the localhost.
