### ISSUE TITLE
Tabula Data Extract Not Working

### ISSUE THREAD

**Issue by shishirchalisey** [tabulapdf/tabula#1070]
I have been trying to extract the data from financial statements. I tried numerous approaches, still I am unable to extract the heading (Acronym of Financial Institutions). Other data and figure from table is easily extracted except the headings. I have attached the screenshot of the same. Page 15 of the attached document.

Thanks in advance.

<img width="1129" alt="Screen Shot 2019-11-08 at 9 16 04 PM" src="https://user-images.githubusercontent.com/57535567/68488402-0f52d900-026d-11ea-82b4-54d8cba8c1e3.png">
[Monthly Statistics _ 2076_05 (Sep 2019) V1.0.pdf](https://github.com/tabulapdf/tabula/files/3825184/Monthly.Statistics._.2076_05.Sep.2019.V1.0.pdf)

**Comment by jazzido** [comment]
Hi @shishirchalisey,

Thanks for the report. Tabula does not support rotated text.
