### ISSUE TITLE
Export shows funny characters

### ISSUE THREAD

**Issue by tribalkouros** [tabulapdf/tabula#1112]
Hello, 

First of all I would like to congratulate you for this very useful tool! 

My issue is that I can successfully convert pdf tables to tabula and see the correct content at the local url but when i export the information to an excel csv file, I get funny characters.

Example: 
 А-КОНТ ЕООД ПЛАЩАНЕ ПО ДОГОВОР СЧЕТОВОДНИ УСЛУГИ 

However, exporting this to excel csv, I get:
 Ð-ÐšÐžÐÐ¢
  | Ð•ÐžÐžÐ” ÐŸÐ›ÐÐ©ÐÐÐ• ÐŸÐž   Ð”ÐžÐ“ÐžÐ’ÐžÐ
  | Ð¡Ð§Ð•Ð¢ÐžÐ’ÐžÐ”ÐÐ˜ Ð£Ð¡Ð›Ð£Ð“Ð˜

Please advise what I need to do.

I am using tabula.exe version: 1.2.1

Kind regards,

Mike

**Comment by jeremybmerrill** [comment]
You'll need to explicitly open the CSV with UTF-8 encoding in Excel. (Instructions vary by version, but all versions of Excel can do it.)
