### ISSUE TITLE
reading pdf <-MSword <- MSExcel 

### ISSUE THREAD

**Issue by Kleinnijenhuis** [tabulapdf/tabula#1129]
Apparently Tabula does not extract MSExcel 
[2019schedule.pdf](https://github.com/tabulapdf/tabula/files/4615588/2019schedule.pdf)
xlsx-tables that were included as pictures in MSWord and saved as pdf thereafter

**Comment by romel-roco07** [comment]
Hi @Kleinnijenhuis , have you solved this issue? Can I ask some help on resolving this?
