### ISSUE TITLE
The `silent` keyword argument does not behave pythonically

### ISSUE THREAD

**Issue by tddpirate** [tabulapdf/tabula#1144]
When I give `silent` as the last argument to `tabula.read_pdf()`, the mere existence of `silent` keyword causes it to be considered as `True`. To unsilence Tabula's `sys.stderr` output, I have to omit it. Setting `silent=False` or `silent=None` did not turn on Tabula's `sys.stderr` output.
I did not test other Tabula functions or other `tabula.io.build_options()` options, but I suspect that the bug exists also for them.

Workaround which worked for me:
```
tabula.read_pdf(...., **({ "silent": True } if silent else {})
```
which is not Pythonic.

**Comment by jazzido** [comment]
Hi @tddpirate — This issue belongs in the issue tracker for the Python wrapper, which is independent from the main Tabula project: https://github.com/chezou/tabula-py

cc: @chezou
