### ISSUE TITLE
warn users when they upload a scanned PDF

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#211]
we can detect this pretty easily and would save us (let alone our users) a lot of time

**Comment by dowcet** [comment]
I mainly use Tabula with documents that have been scanned and OCRed. It usually works pretty well and I am very grateful for that.  As a user, a generic warning that my document is a scan would not be very helpful. What would be really useful instead is to have a hint as to *why* it's not working when it's not (is it that no text elements are found, is it that they don't seem to line up into columns, or is it something else?).

**Comment by jeremybmerrill** [comment]
@dowcet: Thanks for adding your opinion, this really helpful. (And I'm glad to hear you're successful with OCR + Tabula -- may I ask which OCR program you're using? People ask all the time and I rarely have a good suggestion.)

I should have been clearer in this ticket. The only way we know if a PDF is scanned is if it _hasn't_ been OCRed, ergo it doesn't have any text elements. The warning, [as implemented in our hopefully-soon-to-be-released beta](https://github.com/tabulapdf/tabula/blob/feature/newUI/webapp/static/js/library.js#L37), says:
```
Sorry, your PDF file is image-based; it does not have any embedded text. It might have been scanned... Tabula isn't able to extract any data from image-based PDFs. (Though you can try OCRing the PDF with a tool like Tesseract and then trying Tabula again.)
```
Does that sound like it's clear enough to you?

Unfortunately, there's not a good way for Tabula to tell you *why* an extraction isn't working. Tabula only knows about the text elements and lines on the page and does its best to reconstruct the table. It doesn't really have any way of knowing* if what comes out is nonsense or not. I suppose what would be possible is a note saying something like "Tabula detected 5 rows and 3 columns. If this sounds like too few columns, try the <stream/lattice, whichever is not selected> method or try excluding the headers. If it sounds like too many rows (and you're using the stream method), try the lattice extraction method... etc." I'm hesitant because I think that this would be a bit too complex for casual users who don't want to learn the inner workings of Tabula -- but I'd love to hear what you think!

* We've thought about, but rejected, the idea of baking in some intelligence about what data cells "ought to" look like and using that to make decisions. This would be probabilistic, something along the lines of saying a table is more likely to be properly extracted if 
- there are a lot of cells containing only numbers and a maximum of one period or comma
- there are very few capital letters immediately following lowercase letters.
- many whitespace-delimited strings are valid words in some set of common languages (English, Spanish for us).
- columns tend to contain the same kind of data (things that look like integers or things that look like numbers to 2 digits of decimal precision or alphabetic strings less than 100 characters long) 
Unfortunately, this sort of "intelligence" would be wrong pretty often and would probably make us *even more wrong* in edge cases like non-English, non-Spanish documents or documents containing phone numbers like `212.555.1234` or dates like `12.13.2015` that look sort of like spuriously-combined numeric cells. Plus it'd be complex. 

Would love to hear your thoughts!

**Comment by dowcet** [comment]
> may I ask which OCR program you're using?

Most of the files I've used successfully in Tabula were OCRed with Adobe Acrobat Pro in Windows. The only easy way I've found to embed text in scanned PDFs in Linux is with Pdfsandwich, a wrapper for Tesseract. But Teserract's [fonts are broken](http://bugs.ghostscript.com/show_bug.cgi?id=695869) and I'm not sure if Tabula can handle them or not. I will test this and open a separate issue if I find Tabula consistently fails.

> Does that sound like it's clear enough to you?

This is great, but I would urge more precision regarding the distinction between being *scanned / image-based* in general and having *no embedded text elements* in particular. Something like this would be less confusing to me:

`Sorry, your PDF file is image-based (probably scanned from paper) and does not have any embedded text for Tabula to extract.`

I would just leave it at that unless you are prepared to fully address supporting OCRed documents.

> I think that this would be a bit too complex for casual users who don't want to learn the inner workings of Tabula

That makes sense. But something along the lines of an optional verbose mode might be helpful.

With the "intelligent" approach... if it actually works a lot better some of the time but worse most of the time, it could be an option, just like the "spreadsheet mode" is now.

**Comment by jeremybmerrill** [comment]
Thanks for the help on both the OCR question and the warning wording question. Very useful.

The issue with the "intelligent" mode, even if we were to do as you say and make it an advanced option of some sort, is that it would need to be built! It's a nice-to-have, in any case. but if someone -- maybe you? :grinning:  -- were to implement it, I think we'd probably be happy to merge it in.
