### ISSUE TITLE
congressional research service PDF unreadable both automatically and manually

### ISSUE THREAD

**Issue by meli-lewis** [tabulapdf/tabula#239]
This PDF seems to be ill-suited for Tabula; when I tried auto-detecting tables I was told this may not be the correct file type and when I try to manually select a table I see "Sorry, there's been an error." Here's the URL: https://www.fas.org/sgp/crs/misc/RL34468.pdf

**Comment by jazzido** [comment]
Hi @meli-lewis, thanks for reporting your issue.

I can reproduce what you describe in the latest version (0.9.6). The problem is not present in the previous one, Tabula 0.9.5, which you can download from here: https://github.com/tabulapdf/tabula/releases/tag/v0.9.5

Thanks again!
