### ISSUE TITLE
"overflow: scroll" in list of uploaded files

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#240]
Maybe show 10-15 items at a time

**Comment by jeremybmerrill** [comment]
are we lazy-loading here? if you scroll down to, say, page 100, should we remove pages 1-90 from the DOM (until you scroll back up, and of course retaining your selection)?

**Comment by jazzido** [comment]
> are we lazy-loading here?

No, but we should. 

(My original post was about the list of uploaded files in the main screen, but this is equally valid)

**Comment by jazzido** [comment]
Just edited the title for clarity
