### ISSUE TITLE
selections are in the wrong place, after selectionEnd

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#241]
maybe aspect ratio related?

**Comment by jazzido** [comment]
Seems that the new CSS use different positioning directives, thus messing up with the selector widget. Investigating.

**Comment by jeremybmerrill** [comment]
So the selector widget positions the rectangles based on pageX/pageY in the click events. These are relative to the page as a whole, of course. But the positioning on the selection HTML elements is relative to the parent div.

**Comment by jazzido** [comment]
Sorry I couldn’t take care of this. The semester is one week in and I’m already slammed :)

With the old UI, the selection element was attached to a absolutely positioned element, so the position was correct. How can we do the same with the new HTML?

**Comment by jeremybmerrill** [comment]
I'll try to figure that out when I get a chance.

**Comment by jeremybmerrill** [comment]
fixed in  	89c7821

**Comment by jazzido** [comment]
👍🎉
