### ISSUE TITLE
Lazy-load pages and thumbnails

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#245]
As per @jeremybmerrill's [comment](https://github.com/tabulapdf/tabula/issues/240#issuecomment-71379104)

> are we lazy-loading here? if you scroll down to, say, page 100, should we remove pages 1-90 from the DOM (until you scroll back up, and of course retaining your selection)?

**Comment by jeremybmerrill** [comment]
Oh, I was thinking maybe we would just lazy-load the _pages_, but load all of the thumbnails... Thoughts?

**Comment by jazzido** [comment]
We should block as little as possible. The thumbnail and page images are the same (thumbnails are scaled down in the browser), and we want to minimize requests, so we need to lazy-load both.

**Comment by jeremybmerrill** [comment]
Fair enough.

**Comment by jeremybmerrill** [comment]
some work in 7edc47f

**Comment by jeremybmerrill** [comment]
Hmm. Right now, selections are absolutely positioned. If we start hiding pages above where the user's viewing, the selections will be in the wrong spot. The page at say, 3000px, is no longer page 5, but is now page 95, perhaps. The best way to solve this would be to put selections inside the page div, so they're positioned relative to that and shown/hidden along side it. (The alternative, separately hiding/showing/moving the selections based on where their page is shown seems to be unnecessarily difficult.)

A stopgap alternative would be to only lazily load, without hiding anything already-loaded. (Which solves one rationale for this -- the long blocking while all the images load from the server, but not the other, of throwing 400 * 1mb images into the user's memory.)

**Comment by jeremybmerrill** [comment]
Would love to hear y'all's input for lazy-load behavior choices, @mtigas @jazzido

**Comment by jeremybmerrill** [comment]
Implemented the "stopgap" alternative of loading only a few (10?) pages at first and, as the user scrolls, loading the rest. No pages are ever hidden or removed from the page (so selections stay in the right place).

4b110f3

**Comment by jeremybmerrill** [comment]
I think this is fine. @jazzido, @mtigas, thoughts on implementation?
