### ISSUE TITLE
Tabula breaks after highlighting an area of the PDF including a table

### ISSUE THREAD

**Issue by sfcpoll** [tabulapdf/tabula#249]

**Comment by jazzido** [comment]
Thanks for the report @sfcpoll.

In order to properly diagnose and fix the issue, we would need a better description. Also, it would be ideal if you can provide us with the PDF you tried to process with Tabula.

Thanks!

**Comment by sfcpoll** [comment]
Sure thing -- I've attached the PDF, but can try to provide a better
description. I first attempted to auto-detect tables, which gave me this
error:
"Sorry, your file upload could not be processed. Please double-check that
the file you uploaded is a valid PDF file and try again"

Second, I uploaded the file without auto-detection and got to the page
showing the document and pages along with instructions for making
rectangular selection of tables. I selected the entire first page, since
the table encompasses multiple pages and I could not select multiple. After
shading the selection I got this error:
"Tabula couldn't finish processing your request. We'd appreciate if you
could report this error in our issue tracker. If possible, please include
the document that caused the error and the text below."

I cancelled out of that window and tried to make additional selections,
repeating selections on each page, but got the same error.
Thanks for looking into this
Scott

On Mon, Jan 26, 2015 at 12:56 PM, Manuel Aristarán <notifications@github.com

**Comment by jazzido** [comment]
Thanks, @sfcpoll! Unfortunately, GitHub drops attachments when you comment on an issue from email. Can you email it directly to me at *manuel at jazzido dot com* ?

Thanks!

**Comment by jeremybmerrill** [comment]
@sfcpoll: Feel free to reopen this issue if you send the PDF *directly* to me or Manuel.
