### ISSUE TITLE
Access to Tabula's internal API ?

### ISSUE THREAD

**Issue by abelsonlive** [tabulapdf/tabula#251]
I watch all the requests getting fired off when I do a network inspect on tabula extractor and was wondering if it would be possible to access this API to create tabula wrappers in different languages. (are there a list of endpoints somewhere?)  I know, of course, i could just make subprocess calls to `$ tabula` but this is not always the best practice. 

Access to this API could also enable things like containerizing tabula instances and easily parallelizing extraction jobs per page.

**Comment by jazzido** [comment]
Hey Brian,

One of the many things that we need to finish and merge into Tabula is tabula-api (http://github.com/tabulapdf/tabula-api <http://github.com/tabulapdf/tabula-api>). The plan is to replace the webapp that’s bundled inside Tabula with that.

If you’re interested in contributing code to make that happen, I point you to what needs to be done (not much).

Cheers,

M

**Comment by jazzido** [comment]
In any case, shelling out to `tabula` or [using `tabula-extractor` as a library](https://github.com/tabulapdf/tabula-extractor/blob/master/README.md#scripting-examples) will be faster than using it through an HTTP API.

**Comment by jeremybmerrill** [comment]
I'd imagine using `tabula` on the shell is slower than starting up the API in another thread and using it repeatedly, because you save the ~2 seconds per PDF of JVM startup time. (Maybe, in addition to the API, we should build in a "server mode" like a lot of Java apps have.)

**Comment by abelsonlive** [comment]
Whups! I'm sorry I missed that @jazzido. Yes! we're increasingly using Tabula in production at Enigma and would be glad to contribute to the codebase in order to get this feature in place.  The reason we'd prefer using the API over the shell is that we could simply spin up a few tabula API servers and have our scripts access them over HTTP rather than ensuring that every machine that our scripts are running on has `tabula` installed. In the end i imagine the tradeoff between spinning up the JVM and having to send files / receive output over HTTP might actually make the API approach slower, but i'm not really sure.

**Comment by jazzido** [comment]
@jeremybmerrill :
> I'd imagine using tabula on the shell is slower than starting up the API in another thread and using it repeatedly, because you save the ~2 seconds per PDF of JVM startup time.

If you want to cut down the JVM startup time, [drip](https://github.com/jruby/jruby/wiki/Using-Drip-with-JRuby) is the way to go.

**Comment by jazzido** [comment]
@abelsonlive:
> Yes! we're increasingly using Tabula in production at Enigma and would be glad to contribute to the codebase in order to get this feature in place
Awesome!
 
> […] In the end i imagine the tradeoff between spinning up the JVM and having to send files / receive output over HTTP might actually make the API approach slower, but i'm not really sure.

If you really need to expose Tabula as a service running on a remote machine, then we need an API. Otherwise, shelling out+drip or scripting tabula-extractor are possible alternatives.

**Comment by colincadams** [comment]
Is there any update on this? We have a python application that runs on app engine in which we want to extract data from pdf's. We cant use tabula-py as the jvm can't be used in that environment. Instead we are considering deploying tabula as a separate app, but would want to be able to access it over http. cc @arian487

**Comment by colincadams** [comment]
cc @zacharylawrence

**Comment by jeremybmerrill** [comment]
@colincadams There's not currently an HTTP API for Tabula. It would be doable -- we took a stab at it a few years back in https://github.com/tabulapdf/tabula-api but never finished it -- but there's no off-the-shelf solution. You could also roll your own with a thin layer to take uploaded PDFs as POSTs, write them to disk, then shell out to a Tabula command-line tool (in whatever language you want) and return the result.

**Comment by colincadams** [comment]
Makes sense. Thanks for the update!

**Comment by colincadams** [comment]
Following up in case it's useful for anyone else, we ended up moving to app engine flex with a custom docker image so that we could have a Python environment with the JRE installed. Then we could just keep using tabula-py.

**Comment by jazzido** [comment]
Thanks for sharing your solution, @colincadams !
