### ISSUE TITLE
(ArgumentError) comparison of Float with Float failed

### ISSUE THREAD

**Issue by amandabee** [tabulapdf/tabula#252]
I'm trying to lift tables out of:
<http://www.journalism.org/files/2014/03/pathways_to_news_topline.pdf> and getting the following error:
  
    Internal Server Error at /pdf/630ece42c570162fd5fe54d11eabd97324050444/data
  
  
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  

  
    Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:8080/pdf/630ece42c570162fd5fe54d11eabd97324050444/data
      
    
  
  
    (ArgumentError) comparison of Float with Float failed
  

  
    
    You're seeing this error because you use Rack::ShowStatus.
    
  Any tips much appreciated!

**Comment by jeremybmerrill** [comment]
Hi Amanda: this should be fixed in our latest version. https://github.com/tabulapdf/tabula/releases/tag/v0.9.7 Please let us know if it's not!
