### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ChrKoenig** [tabulapdf/tabula#255]
For some days now, I get the following error when starting tabula:

![capture](https://cloud.githubusercontent.com/assets/10863705/6058215/a04e57b0-ad25-11e4-922d-0114bb945a18.PNG)

What causes this? I didn't change anything, as far as I remember.

**Comment by jeremybmerrill** [comment]
*org.jruby.exceptions.RaiseException: (Encoding::CompatibilityError) incompatible character encodings*: (Windows): Your Windows computer expects a type of encoding other than Unicode or Windows's English encoding. You can fix this by entering a few simple commands in the Command Prompt. (The commands won't affect anything besides Tabula.)

    Open a Command Prompt
    type `cd` and then the path to the directory that contains tabula.exe, e.g. `cd C:\Users\Username\Downloads`
    Change that terminal's codepage to Unicode by typing: `chcp 65001`
    Run Tabula by typing `tabula.exe`
