### ISSUE TITLE
Page thumbnail size can't be relative to viewport width

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#256]
See what happens:

![out](https://cloud.githubusercontent.com/assets/27584/6065421/5bed82ae-ad33-11e4-9b40-d84e4014fc11.gif)

**Comment by jeremybmerrill** [comment]
Or should the selector widget watch for resizes and resize itself?

**Comment by jazzido** [comment]
Yeah, that’s the ideal. But we should have a min-width anyways.

**Comment by jeremybmerrill** [comment]
added a min-width: 429388b

I don't think the case where the user resizes the page is a blocker for a release, though enhancing the selector widget to watch for resize and to resize its own selections would be worthwhile as a nice-to-have.
