### ISSUE TITLE
give output CSV the same name as the input PDF

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#257]
e.g. `sierra_leone_ebola.pdf` when processed should output `sierra_leone_ebola.csv` rather than `tabula-asdfasdf1234567890.csv`. Or perhaps something to disambiguate, like `sierra_leone_ebola-1.csv`

**Comment by jeremybmerrill** [comment]
The best way to to do this might involve creating a File Library API in tabula_web.rb that takes a PDF_ID and gives back its metadata.

**Comment by jeremybmerrill** [comment]
hell, let's put the filename in the header of the selection/extraction pages (in case you have multiple open in tabs, etc.)

**Comment by jeremybmerrill** [comment]
done in 62c5e08

**Comment by jeremybmerrill** [comment]
![screenshot from 2015-02-25 22 13 32](https://cloud.githubusercontent.com/assets/548250/6385698/b90781de-bd3b-11e4-836d-9a5a66f2d00a.png)

![screenshot from 2015-02-25 22 13 23](https://cloud.githubusercontent.com/assets/548250/6385697/b77e5ce8-bd3b-11e4-8e40-4b4d3049ceb3.png)

Pending better design ideas...

**Comment by jeremybmerrill** [comment]
Any design thoughts, @floodfish, @mtigas, @jazzido?

**Comment by floodfish** [comment]
I like using the PDF's filename as a default. And yes, some kind of auto-incremented naming sounds good if the app knows there are multiple extractions from the same PDF.

I'd been planning that the user would only see and (potentially) edit it via the system "save" dialog box. This is pretty typical when saving a new file in most apps, right, including web browsers?

**Comment by jeremybmerrill** [comment]
The default download option in Firefox on Ubuntu does not give such a default option (for Tabula or anything). Likewise Chrome on Ubuntu.

There's no need to add the filename-renaming option if it applies only to software hippies like myself; that is, if Windows and Mac include this option natively. I'll have to do some research on a Mac and on my Windows box...

**Comment by mtigas** [comment]
I think you only get the system dialog if you manually "save as" or if your browser is set to "Ask where to save each file before downloading". Otherwise most modern browsers automatically dump to wherever it's set up to download files.

And I'm fine with that and just using the input filename as the basis for the output filename. Don't think there's any need to muck with the filename within Tabula, since if your browser skips the system dialog, I'm 95% sure it'll tack on a " (1)" or some other serial number after the duplicated filename.

**Comment by floodfish** [comment]
Ok. So I guess the question is, is system/browser default file saving behavior good enough? Or, is it at least the appropriate standard to be consistent with?

**Comment by jeremybmerrill** [comment]
I guess my thought is that the browser mechanism is fine... I can pretty easily transform that little text input back into just a <span></span> -- but maybe there's somewhere better it can go?

**Comment by jeremybmerrill** [comment]
for now, d5a5bba turns off editable filenames. it's easy to turn on again (or move) if we decide we want it.
