### ISSUE TITLE
Deleting uploaded file

### ISSUE THREAD

**Issue by ahjones854** [tabulapdf/tabula#261]
Once a file has been uploaded to be converted is the file stored on a server or deleted?

**Comment by jeremybmerrill** [comment]
Hi @ahjones854:

In short, no, it's not stored on a server. It's stored locally on your computer. The data from your file never even touches the internet, let alone our servers.

Here's what our readme says:

> Your PDF and the extracted data never touch the net -- when you use Tabula, as long as your browser's URL bar says "localhost" or "127.0.0.1", all processing takes place on your local machine. Tabula does download a list of Tabula versions from our server to alert you if Tabula has been updated (and we use hits to that list to count how often Tabula is being used); it also downloads a few badges and assets from the web.
