### ISSUE TITLE
Problem Extracting EMS  Data from NYPD Fire Statistics

### ISSUE THREAD

**Issue by h2oboxer** [tabulapdf/tabula#264]
When i attempt to scrape the Ambulance incident and run data it misses an entire vertical column titled "1-8"

Link to failed document : http://www.nyc.gov/html/fdny/pdf/stats/2008/ems/bk/ems_bksum_0208.pdf

Thanks
Tim

**Comment by jeremybmerrill** [comment]
hiya @h2oboxer:

Oof, that's a nasty PDF. Between all the weirdly shaped tables, the table borderlines that _just barely_ don't intersect and the multiple headers, it's guaranteed to cause some trouble.

Try excluding the headers and using the "Original" extraction method (under advanced options in the data download modal window), like this: 
![screenshot from 2015-02-16 11 28 28](https://cloud.githubusercontent.com/assets/548250/6215475/120fbe82-b5cf-11e4-9bb1-03366dd2dad2.png)

That should get you pretty decent data.
