### ISSUE TITLE
Enhancement - Draw a line over a pdf to delimitate a column

### ISSUE THREAD

**Issue by hpiedcoq** [tabulapdf/tabula#265]
Hi!
1st of all, thank you for Tabula, a software that saves my life everyday.
One question : 
Could it be useful/possible to implement a function that would allow us to draw a vertical line on every page, on top of the selected area, in order to delimitate columns on documents where columns are not well marked.
It would help Tabula to structure the document.

Thanks for your help
Hervé (from Paris France)

**Comment by jeremybmerrill** [comment]
Hi Hervé,

Glad to hear Tabula is useful to you! We've thought about implementing a feature for Tabula like you describe. We've never found time to do it, though [tabula-extractor](https://github.com/tabulapdf/tabula-extractor), Tabula's command-line counterpart, supports this feature. We'll keep in mind your feedback when choosing what new features to add.
