### ISSUE TITLE
error message when using similar selection to grab from multiple pdf pages

### ISSUE THREAD

**Issue by egrommet** [tabulapdf/tabula#269]
I'm getting an error message when trying to export to a csv file - but it is actually working and exporting the first page, but not repeating selections from subsequent pages

**Comment by jeremybmerrill** [comment]
Hi @egrommet, what was the error message?

**Comment by jeremybmerrill** [comment]
Feel free to reopen, @egrommet, if you can give me the error message -- I can't help debug without it.
