### ISSUE TITLE
newUI: no images shown for 1-page PDFs

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#274]
To reproduce: upload a single-page PDF.

Maybe related to #245 ?

**Comment by jeremybmerrill** [comment]
I think this is an edgecase that will never actually occur. Wontfix.

**Comment by jeremybmerrill** [comment]
(j/k, obviously. I can replicate and will fix shortly.)

:grinning: :grinning: :grinning:

**Comment by jeremybmerrill** [comment]
fixe din 0bd7899
