### ISSUE TITLE
Selection thumbnail duplicated

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#277]
1. Make a selection
  2. Get data
  3. Selection thumbnail duplicated (see screenshot)

![screen shot 2015-03-08 at 2 02 33 pm](https://cloud.githubusercontent.com/assets/27584/6546897/1a7fa3fc-c59c-11e4-956c-d178584d0407.png)

Additionally, when drawing new selections, the selection frame is invisible as you drag the mouse.

**Comment by jeremybmerrill** [comment]
Yep, aware of it, thanks

**Comment by jeremybmerrill** [comment]
second issue fixed in 598637f

**Comment by jeremybmerrill** [comment]
fixed in 2469b9784721e1e456e0397279dc683e74dedfb3
