### ISSUE TITLE
Remember scroll position when switching between document and preview

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#280]
So the users don't get lost.

**Comment by jeremybmerrill** [comment]
I [tried to implement this last night](https://github.com/tabulapdf/tabula/blob/feature/newUI/webapp/static/js/pdf_view.js#L1222-L1228), but it didn't work! I'm not sure why, and I didn't feel like debugging more; this does verify my instinct that this is a thing we ought to have implemented.

Any ideas why?

**Comment by jeremybmerrill** [comment]
Nope, I'm just an idiot! I was rendering the div, calling scrollTop, but only then unhiding the element. That'll do it. Fixed in my next commit.
