### ISSUE TITLE
Can't resize lassos after coming back from preview

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#281]
Does work if I don't go to preview right after creating a selection.

**Comment by jeremybmerrill** [comment]
Hmm. Probably easy to fix, probably I need to call redelegateEvents or something.

**Comment by jeremybmerrill** [comment]
Fixed. Actually was kind of gross. For some reason, pdf_view.js keeps two, denormalized lists of selections, one global one and one per page_view (keeping track of only that page's selections). Selections were created once on the first load, and a second time on the return to the selection view. The first selection, however, was never removed from the page_view's list of selections. This meant that the collision-detection logic was seeing the two overlapping selections, and forbidding them from being changed.

See #282
