### ISSUE TITLE
Upload progress bar should only appear on demand

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#286]
IMO, the progressbar should only be visible while an upload is in progress. Additionally, the "Upload progress" header should be removed.

No upload:  
![screen shot 2015-03-14 at 12 29 42 pm](https://cloud.githubusercontent.com/assets/27584/6652454/d63ee88e-ca45-11e4-9c5d-8c052f856f78.png)

Uploading:
![screen shot 2015-03-14 at 12 29 29 pm](https://cloud.githubusercontent.com/assets/27584/6652456/db2be6bc-ca45-11e4-863d-864d0dd942f0.png)

To me, it makes the UI look less cluttered.

What do you think?

**Comment by jeremybmerrill** [comment]
Brilliant. 👍👍

Jeremy B. Merrill

**Comment by jeremybmerrill** [comment]
Implemented in feature/multiple branch.

**Comment by jeremybmerrill** [comment]
Closed in 40d0a655953307a2ced86a180ee601abf047e9ef et seq.
