### ISSUE TITLE
Error on extraction preview

### ISSUE THREAD

**Issue by cblevinsajc** [tabulapdf/tabula#292]
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:8080/pdf/e2be25532ebf14d71417275a3d15ac222e3adbed/data<br /><br />(ArgumentError) comparison of Float with nil failed

os 10.10.2
  Model Identifier:	MacBookPro11,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B14
  SMC Version (system):	2.18f15

**Comment by jeremybmerrill** [comment]
Hi Chuck,

Can you send me an email with the PDF that's causing this problem? A link works best, but if that's not possible, send it to me directly, not via Github, since Github strips out attachments). If it's sensitive, I understand too, of course.

**Comment by cblevinsajc** [comment]
Here’s one of the charts.
Thanks – love the tool!

Chuck Blevins
Manager, Digital Products and Projects
The Atlanta Journal-Constitution  |  Cox Media Group
404-526-7008 (o)
678-439-5840 (m)
Chuck.Blevins@ajc.com<mailto:your-email@ajc.com>
twitter  twitter.com/crblev<https://twitter.com/access_atlanta>

**Comment by jeremybmerrill** [comment]
I wasn't able to replicate this issue -- that is, I was able to successfully extract the data without a problem.
