### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by SourcingMogul** [tabulapdf/tabula#294]
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:8080/pdf/c3310e0f1022982599e1f765c3f0da10ef4f2c64/data<br /><br />(ArgumentError) comparison of Float with nil failed

**Comment by jeremybmerrill** [comment]
@SourcingMogul Can you send me an email with the PDF that's causing this problem? A link works best, but if that's not possible, send it to me directly, not via Github, since Github strips out attachments). If it's sensitive and you can't, I understand too, of course.

**Comment by SourcingMogul** [comment]
Here is the link:

https://www.usenix.org/system/files/tech-schedule/srecon15_attendeelist.pdf

On Fri, Mar 20, 2015 at 5:01 PM, Jeremy B. Merrill <notifications@github.com

**Comment by jeremybmerrill** [comment]
@SourcingMogul Sadly, that link is behind some sort of paywall. Maybe you can host it elsewhere or email it to me *directly, not via Github*? (Github strips out PDF attachments.)

**Comment by jeremybmerrill** [comment]
Closed for inactivity.
