### ISSUE TITLE
Question on Tabula features

### ISSUE THREAD

**Issue by sharkichacko** [tabulapdf/tabula#299]
Hi,

I just want to know whether Tabula support exporting of Charts and Images from PDF to Excel?

Thanks,
Sharki

**Comment by jazzido** [comment]
Hi @sharkichacko,

Tabula does not support exporting either charts or images. If your image contains a table, you might get good results by first processing it with an OCR engine and then feeding the document to Tabula.

Thanks,

Manuel

**Comment by sharkichacko** [comment]
Thanks, Are you aware of any open source software which support exporting
of charts and images from PDF to Excel?

Thanks,
Sharki

**Comment by jazzido** [comment]
Tesseract is a good open source OCR engine, but AFAIK is does not directly export a scanned table to Excel.
As for charts, I’m not sure what you mean by ‘exporting to Excel’.

**Comment by sharkichacko** [comment]
Converting  PDF charts to Excel charts. Are charts in PDF considered as images or PDF has charts objects?

**Comment by jazzido** [comment]
PDF has no notion of “chart" whatsoever. It only knows about vector and bitmap images.
It’s absolutely up to the author of the document whether to display a chart as a vector or bitmap image.

**Comment by sharkichacko** [comment]
Does Tabula support exporting images from PDF to Excel as vector or bitmap image?

**Comment by jazzido** [comment]
Tabula does not export images of any kind.

**Comment by sharkichacko** [comment]
We would like to integrate Tabula with our software, do you have a dll file or a command line utility we can use to export PDF tables to CSV/Excel?

**Comment by jazzido** [comment]
You can use [tabula-java](http://github.com/tabulapdf/tabula-java) or [tabula-extractor](http://github.com/tabulapdf/tabula-extractor)

**Comment by sharkichacko** [comment]
Thanks, the PDF files we have has so many tables in it, does Tabula tell me which table come from which page?

**Comment by sharkichacko** [comment]
Thanks, can Tabula tell me what table is from which page in PDF document? I
am looking for some info which tells me original location of table exported
to Excel. Our software is a Linking software which links objects in Excel
and other softwares. Is case of PDF, I am trying to link tables in PDF to
tables in Excel after the export, for that I need to know the location of
the original table in PDF.

Thanks,
Sharki

**Comment by jazzido** [comment]
There are usage examples in the source trees of both tabula-java and tabula-extractor. You might find methods to implement the functionalities you describe.

**Comment by sharkichacko** [comment]
Thanks, I am having a hard time installing tabula-extractor. I have
installed JRuby and downloaded tabula-extractor-master then not sure what
to do, can you help?

**Comment by sharkichacko** [comment]
HI, can you update on this?

**Comment by jazzido** [comment]
There's tons of info in the docs and the code.

**Comment by sharkichacko** [comment]
Thanks for the response, I am having trouble in the installation phase.
When I try "jruby -S gem install tabula-extractor " in JRuby, I get the
attached error, can you tell me the exact command? JRuby is not
recognizing tabula-extractor it looks like.

Thanks,
Sharki

**Comment by sharkichacko** [comment]
Hi,

Can anyone help me on the installation? "jruby -S gem install tabula-extractor"
seems to be not working for me, I am getting an error that I sent you in
the previous email.

Thanks,
Sharki
