### ISSUE TITLE
Not reliably extracting text content rendered in legacy Asian language font (Hind/Devnagri)

### ISSUE THREAD

**Issue by answerquest** [tabulapdf/tabula#303]
I'm trying to extract budget data from a document that is using a legacy Devnagri script font embedded (and obscured) within the PDF, where each character is actually an ANSI character, and the font replaces the glyphs with its own. Regular a/b/c as well as } Ÿ ë etc (ie, the ANSI charset from character code 33 to 255).
I have a to-Unicode converter on the outside that will process this text to Unicode.
Example: fc©flXl`T will turn into: सर्वसाधारण

*With manual copy-paste, the content is coming out fine.* But when Tabula takes a go at it, the text **gets scrambled up** at places, adjoining letters get swapped, unwanted spaces come in. This is common to both the "normal" and "spreadsheet" extraction options.

[See this diff output] (https://www.diffchecker.com/9k5i0o0b) to see the same text brought out by normal copy-paste on left, and Tabula on the right.

The Devnagri script's complex consonant-vowel relations means that this altered text when converted to Unicode, result in flawed data like this:
"पणु  े" when it should have been "पुणे" . It's too messed up to be an acceptable output.

This same issue (and more!) is happening with all the online pdf-to-excel converter services I've tried with this document, which tells me it must have something to do with the way the program is reading in the data.There's no issue with tabulating, mind.. all the cells are ordered properly, nothing is out of place (cheers!). But the content in those cells is getting messed up; data is being corrupted when extracting. 

My guess is that Tabula is not doing a simple textual copy-paste. Since when that is done manually, we don't get errors like these. When I box-select (Ctrl+Alt+click+drag) the text in the PDF and copy it, the output is perfect. That's simply what I need to be automated across several pages. When I draw the selecting box over the page thumbnail in Tabula, I want it to simply mimic this simple box-select > copy > paste action.

So, feature request, in case we can't fix this jumbling-up of letters : Can Tabula have an option to simply copy-paste text, raw, with no smarty stuff, within the bounding boxes set by the user? This would enable us to use Tabula with a lot of legacy-font PDFs published by government agencies in India.

The PDF document in question can [be seen here] (https://drive.google.com/open?id=0B8sY5vZfk1W5S2F1N0M1ZVdIaUE&authuser=0)
Full project [is here] (https://drive.google.com/open?id=1AJg3p89hQcjkI0eG_TomzYFAjnGAmEHpQHt7-E2H6UY&authuser=0) (an attempt to make an online spreadsheet version of an Indian city's annual budget book which they only publish as PDF)
[This is the to-Unicode converter being used] (https://gist.github.com/answerquest/74c13f73f1bfb21c3177)

**Screenshots**
Selecting the portion in Tabula, which is giving slightly distorted output: 
![tabula selection](https://cloud.githubusercontent.com/assets/9089552/7163654/d2bf88c6-e3b8-11e4-8027-a1b302956ef2.jpg)
---------------------------------
Doing the same selection in a regular PDF reader, which is giving perfect output:
![pdf manual box selection](https://cloud.githubusercontent.com/assets/9089552/7163673/f324100a-e3b8-11e4-80dd-1cc2fd3d6721.jpg)

**Comment by jeremybmerrill** [comment]
This is a really interesting bug (and well described, thank you!). I don't know of a solution of the top of my head. Do you know of a good description of how Devanagari is translated to ANSI and back? 

I'm especially curious about how conjuncts and diacritics are handled in the transliteration system. I wonder if PDFBox -- the library we use for PDF rendering -- simply handles Devanagari scripts poorly, perhaps linearizing the vowel diacritics inconsistently.

**Comment by answerquest** [comment]
Thanks, Jeremy. I must add that the same issue doesn't repeat for some pages from this document, while it repeats for some others. Overall more than 50% is seeing distortion. And it's the same with online converters.. so if Tabula is doing a distortion then so are zamzar, pdftoexcelonline, etc. All while a simple manual copy-paste doesn't get any distortion (and that's got me confused).

Currently, the pdf text extraction tools out there give us all the text in the page, and with tables that's too messed up, with all the other rows merging in and playing havoc. Tabula can help us mark a column with bounding boxes and extract only the text that appears in there. (It's literally a copy-paste job, we only need to figure out how to automate it). From the user's end, I can draw a bounding box and make it repeat on all pages in the document.. that's exactly what I need. Next, I only need to Ctrl+C everything selected. I know that on Tabula's end it's actually only showing me a thumbnail and all that jazz.. so please figure it out! Basically, it'd be great if there was a third "Raw Text" like option next to Normal and Spreadsheet.

== Digressing a little ... ==
What you mentioned about conjuncts etc.. I think that pertains to Unicode text in PDF.. this is not that case. There is no unicode text inside these files.. it's all regular ANSI chars rendered in a legacy fonts which draws "c" as "व" etc. Yes, the maatras (the vowel symbols) have to overlap with next or previous characters etc, the font takes care of that. If I have to work with PDFs then I prefer the legacy fonts, since the PDF faithfully carries the content in (which at least I can retrieve through copy-paste). If it were Unicode, then PDF technology as of today, destroys information in Unicode Devnagri scripts in the "print-to-PDF" process.
Example: 
> "मेरा नाम चिन चिन चू"
( I print that from Notepad to PDF using PrimoPDF, a standard free PDF creator tool.)

Tabula, extracts this:
> "मरा नाम चन चन च"
(all vowels placed at top and bottom got zapped)..

..and simple copy-paste, gets this:
> "मे रा नाम चन चन चू"
(a ghost space crept in, and two preceding vowel signs went weird)

..which means the original text information has been distorted in the PDF and is irretrievable! So this is why I stil prefer legacy fonts.. at least there with simple copy-paste I'm able to get the original text out!

I did find one project out there working on this issue some months back.. they seem to have had some success, but there wasn't any end-user application created yet.

I don't think the script's issues can be resolved right now. But what can be done, and I feel it'll be useful elsewhere too, is a simple text-copy mode wherein it mimicks the user's action of box-selection and Ctrl+C. Right now on clicking advanced options we get a Normal mode and a Spreadsheet mode, right? Add a third mode : Raw Text, or whatever you name it.

**Comment by jeremybmerrill** [comment]
Thanks, @answerquest. This explanation is really helpful. 

I don't have time right now to respond at length (though I'll do my best to get back to you in the next few days!).

I will note that mimicking how PDF display programs implement copy-paste is not trivial -- there's no "act like you're copy-pasting" command in our PDF library, for instance. The way Tabula extracts text from an area, especially in "Spreadsheet" (soon to be renamed "Lattice") mode, *tries* to mimic copy-pasting, but apparently doesn't work perfectly in this case. [This document](http://doc.qt.digia.com/qq/qq27-poppler.html) appears to explain how libpoppler, a C pdf reading library implements copy paste, which might be useful for us to improve how Tabula linearizes characters, in a way that mimics copy-paste.

**Comment by jeremybmerrill** [comment]
Oh, and if you hav ea link to that semi-successful project that might be helpful -- it might be neat to take a look at their approach, if you can find the project again.

**Comment by answerquest** [comment]
It was here: http://indicpdf.apphb.com/?lang=Devanagari but not there anymore :(

Some possible leads:
http://stackoverflow.com/questions/4297931/how-to-extract-text-from-a-pdf-doc-within-a-specific-rectangular-region 
> this code will perfectly extract pdf data on the basis of rectangular coordinates using itextsharp"

http://pdfclown.org/tag/text-extraction/ 
> a text extraction tool allows sub-page region selection to extract text only from specific page areas.

**Comment by jeremybmerrill** [comment]
Got it, I just saw your ANSI-to-Unicode converter, which answers a lot of my questions. 

Let's reverse engineer this, starting with -- and forgive my rusty Sanskrit that I'm misapplying to whatever language this is (Hindi? Marathi?) -- the word in the top right corner of the header row on the first page that I would pronounce `jamaichA`.

I see from copy/paste that this is represented in ANSI as `N^nLl`. Tabula extracts this as `N^Ln l`

Tabula sees the locations of the characters as, in [top, left, bottom, right] format, 
```
#<TextElement: 55.42,549.49,60.0,556.25 'N'>
#<TextElement: 55.42,556.22,60.0,561.97 '^'>
#<TextElement: 55.42,561.96,60.0,568.74 'L'>
#<TextElement: 55.42,561.97,60.0,562.02 'n'>
#<TextElement: 55.42,568.8,60.0,571.66 'l'>
```
as you can see `n`/`"े"`/`"ai" starts (on the x axis), 0.01 pixels to the right of `L`/`च`/`"ch"`. That's strange, but I guess a quirk of the font?

And, there's the misplaced space. 

There are two issues here:
* Tabula orders characters (TextElements) by their left edge, not by their center.
* Tabula keeps uses a hack ot determine a typical character width and average between-word width to try to figure out where to insert a space. The combining characters are probably skewing this.

If I adjust the first issue and order characters by their center, now we get `N^n Ll`. Now we're in the right order! (and much to my great surprise, the tests pass!) But there's still that pesky space.

I also messed around with space insertion to calculate averages better. Because of a really silly hack, we had been weighting too high the width of the most recent character. Because the 'n' has so little width (because it really goes on top!), a space is spuriously inserted after it. If we instead keep all the space widths and take a real average, we get the right result: `N^nLl`. Hooray!

Will this solve the whole thing? I don't know! But the tests still pass! I also extracted the first page for you to use to look at -- https://www.dropbox.com/s/2gqepxfplal7g2z/tabula-pune-budget-page-1.csv?dl=1 -- how's it look?

If it looks good and if you tell me what platform you're on, @answerquest (i.e. Windows/Mac/Linux), I'll bake a special version of Tabula for you to try with these fixes.

**Comment by jeremybmerrill** [comment]
Pull request: https://github.com/tabulapdf/tabula-extractor/pull/97

**Comment by answerquest** [comment]
Hi Jeremy, wow, the output was perfect! I hope this doesn't mess up other scripts' conversions ;) :P

This should put Tabula well ahead of all the online pdf-to-excel converters out there for people wanting to convert docs with Devnagri scripts.

It would also be worth testing this with PDFs having Unicode Devnagri/Hindi/Marathi chars.. I'll check on that too and report back once I get the newly baked version.

(FYI, `Devnagri` is the standard technical term used to define this script, while `Hindi` and `Marathi` are two sister languages that use it)

I'm using Win7, and you can call me Nikhil.

This fix would've made [this project a lot quicker] (http://tiny.cc/punebudget2015). :P Still, this is great.. many similar conversions can now be a lot smoother. Many thanks!

**Comment by jeremybmerrill** [comment]
> Hi Jeremy, wow, the output was perfect!
Glad to hear it -- and nice to meet you, Nikhil!

>I hope this doesn't mess up other scripts' conversions ;) :P
Nope, all the test pass! (Much to my surprise, tbh)

> (FYI, Devnagri is the standard technical term used to define this script, while Hindi and Marathi are two sister languages that use it)
Yes, but, just out of curiosity, which language is that budget in?

I baked you TWO new versions that incorporate the tabula-extractor changes that fix the Devanagari problem. [This one](https://www.dropbox.com/s/7nft81kzm5pdz3h/tabula-win-rev7c611c8ec5b7636c6a2380ee6307b0abf2d35123.zip?dl=0) is the new Tabula pre-beta with a new UI. If you try this one, please ALSO let us know what you think about the new UI. (Here's fine, or open a new bug with your feedback.) But don't feel obligated -- if you'd prefer, [here's the normal/old version](https://www.dropbox.com/s/h3gk98xhmi9hvxf/tabula-win-revee356e1c9c5e2dc5bf47abe5b87c134262a16ee9.zip?dl=0) with the fix for the Devanagari characters.

Let me know how it goes with the entire Pune budget PDF and with the other PDFs. I suspect it will work well -- perhaps we're getting closer to mimicking how desktop PDF viewers implement copy/paste.

**Comment by answerquest** [comment]
Ok, now was able to test this out... Kudos, all the chars were extracted perfectly.
I liked the new UI.

A few inputs on the new UI:
1. (Issue) CSV output: when the data has a comma in it, the CSV isn't enclosing it in quotes or anything. So, when copying to clipboard and then importing to a spreadsheet, the data of that cell gets split into columns due to the rogue comma.
2. When we press "Copy to Clipboard", it was nice to have a text "Copied!" appear next to it in the old version, please bring that back so we know it has happened.
3. You've increased the size of the thumbnails, but their resolution stays low, so it gives a very blurred feeling. Want to consider making them bigger? Or, want to vary it according to number of pages? (more pages, low res)
4. It would be great to be able to shrink the page thumbnails to "fit page height" level, so if the table's easily markable, I can scroll to next pages quicker, as before. The bigger view (fit page width) is also useful to have for more precise marking. So I'd suggest keeping a dropdown menu on the top bar, right side with "fit page width", "fit whole page" view options.
5. (Issue) Clicking on the side thumbails at area selection stage doesn't take me to the corresponding page! I'm clicking on page 2 and being taken somewhere around page 10. Clicking the last page 20 is also taking me somewhere in the middle of the document. The ordering's all gone haywire.
6. Writing the page number next to even the big page would be a helpful guide.
7. I think I preferred a blue colour selection rectangle instead of red.
8. ...and with the border not this fat. It doesn't allow us to have accuracy in selecting the target portion.
9. The "Repeat this Selection" button is old-style uniform grey, whereas other buttons in this application are all 3D-looking, well-shaded and light up on mouseover..
10. Feature request: Allow to repeat selection for alternative pages instead of every page, as many PDF's are printed across two adjoining pages and we don't want the odd/even page to get in the way..

**Comment by answerquest** [comment]
The language was Marathi, btw

**Comment by answerquest** [comment]
With unicode devnagri script (ie, not the legacy fonts but Unicode) the same problem as I had described earlier has persisted, 
> "मेरा नाम चिन चिन चू"

Tabula, extracts this:
>  "मरा नाम चन चन च"

indicating that must be another problem, maybe another bug could be filed for that?

**Comment by jeremybmerrill** [comment]
Super helpful! Thanks! (Will open other bugs for your feedback!)

**Comment by abh0077** [comment]
Hi, I am also facing the same issue.
For example:  पिता का नाम  is displaying as नपतर कर नरम: on Tabula output format and if i try to download this ANSI Conversion is not correct
@answerquest please see if you can help.

**Source File:-**
![trying_to-convert](https://user-images.githubusercontent.com/32451596/31072103-456fcff2-a784-11e7-8f1c-30be57be7e45.PNG)

**Tabula Format Output Version:-**
![tabula-export](https://user-images.githubusercontent.com/32451596/31072181-8ae3e4e2-a784-11e7-879b-1f8fce046bb2.PNG)
 
**Downloaded CSV File:-**
![voter_list_excel conversion](https://user-images.githubusercontent.com/32451596/31072200-9bf3fe52-a784-11e7-882e-dad9c1d35191.PNG)

**Comment by answerquest** [comment]
Hi @abh0077 I'm not focusing on this now, hoping you find a solution. If the mistakes are predictable for your data then a program could be written to fix them. The CSV output needs to be not in ANSI but in UTF-8; I think there was something around here for making sure Tabula's exports are in UTF-8 and not in ANSI.

**Comment by jazzido** [comment]
@abh0077 Thanks for your comment. If the browser preview looks fine, then the CSV should be also correct. Make sure that the application that you're using for opening that CSV uses UTF-8 encoding.

**Comment by abh0077** [comment]
@jazzido Hi, Thanks for prompt reply, exporting in utf8, solved the download problem but what about wrong output ? Did you guys found a solution of it ?

**Comment by answerquest** [comment]
Hi @abh0077 , could you verify if the font in your PDF is in a legacy devnagri font, or in unicode? The simple way to check is copy-paste some text from the PDF to notepad or a simple text editor. 

1. If you still see devnagri chars in the notepad, then your source is Unicode and this is the wrong issue/thread to be discussing this in.. the right one would be this: #621 (Tabula does not recognize correctly Hindi script from Government of India)

2. If you get non-devnagri chars in the notepad, then this thread is the proper place.

**Comment by abh0077** [comment]
@answerquest Thanks. moved to #621 now. But i can't see any solution there too. 
please see if you can help me in any manner brother. My email id is abh007.7@gmail.com

**Comment by answerquest** [comment]
@abh0077 yes, It would be great if you could put up your case there, might help revive the interest.
My explorations in the unicode problem have led me to this stand : there's a problem in the way current PDF technology is handling Unicode Devnagri characters. To make things appear proper for printing (PDF's initial purpose), the content is messed with, apparently permanently.
OCR is another option. Automating it haoul really help. Check out #409

**Comment by mdileep** [comment]
Check this 

https://www.google.com.pg/patents/US9740667

**Comment by blmali** [comment]
still i can't able to convert a pdf file to word .which is written in hindi.
[मानव व्यवहार दर्शन.pdf](https://github.com/tabulapdf/tabula/files/1892914/default.pdf)

**Comment by answerquest** [comment]
Hi @blmali your file has legacy hindi fonts - that's appropriate for this thread. Do you know exactly which legacy font has been used? Please check out this site hosting all the legacy-to-unicode converters and try out and find which one is good for your data:  https://sites.google.com/site/technicalhindi/home/converters .
