### ISSUE TITLE
consider toning down red selection and wide border

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#319]
>  7. I think I preferred a blue colour selection rectangle instead of red.
> 8. ...and with the border not this fat. It doesn't allow us to have accuracy in selecting the target portion.

from https://github.com/tabulapdf/tabula/issues/303

**Comment by jazzido** [comment]
+1 to making the border thinner

**Comment by jeremybmerrill** [comment]
check this ish out: 3b4c889 what do you think?

**Comment by jazzido** [comment]
Much better. Closing.
