### ISSUE TITLE
Reset file input if image-pdf warning appears

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#326]
![screen shot 2015-05-02 at 6 50 56 pm](https://cloud.githubusercontent.com/assets/27584/7443038/5b8c8d20-f0fc-11e4-94a9-5a2a18ee3d59.png)

If the uploaded PDF is image-only, the file upload box should be cleared.

**Comment by jeremybmerrill** [comment]
Ah good catch.

Jeremy B. Merrill

**Comment by jeremybmerrill** [comment]
close din a774ebe
