### ISSUE TITLE
“Tabula” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by ShaneCurcuru** [tabulapdf/tabula#327]
Since your release page says "let us know", here you go!  

Downloaded 0.9.7 package for Mac, unzip, drag Tabula to Application folder, doubleclick to run - get the above error.  MacBook Air with OS X 10.8.5 (12F2518).

It runs fine once I CTRL-Open to allow it.  

Feel free to close if you don't need these reports - is there a specific issue with your app signature on some OSX builds?

Thanks!

**Comment by jeremybmerrill** [comment]
@mtigas any ideas?

**Comment by mtigas** [comment]
welp, just realized I used the iOS signing key for Onion Browser instead of the OSX signing key for Tabula. Will be fixed in next build.

**Comment by jeremybmerrill** [comment]
LOL

oopsies, hooray for betas.
