### ISSUE TITLE
Port 8080 already in use

### ISSUE THREAD

**Issue by Properhead** [tabulapdf/tabula#331]
I have another app which also requires 8080.  As a result, this has to be closed before running Tabula.  Neither app provides flexibility to use a different port, so this is an ongoing problem.

**Comment by jazzido** [comment]
Hi @Properhead,

It it possible to change the port that Tabula binds to. See documentation here: https://github.com/tabulapdf/tabula#using-tabula

**Comment by Properhead** [comment]
Thank you Manuel, for your speedy reply that answers my question exactly.






On 28 May 2015 at 8:19, Manuel Aristarán wrote to me about the above subject:



Hi 
@Properhead,

It it possible to change the port that Tabula binds to. See documentation here: 
https://github.com/tabulapdf/tabula#using-tabula

—
Reply to this email directly or 
view it on GitHub.





Best Wishes,





Neil A Fraser
  

    
        
        
    
    
    
    
    
    
    
    
    TEL:    +27 (0)44 884 0493
    FAX:    +27 (0)86 500 3591
    CELL:  +27 (0)82 903 4962
                  whatsapp
    
    
    SKYPE: neilfraser
    

SA distributors: Megapulse battery conditioners
Web site and on-line shop: 
www.necon.co.za


*** Email disclaimer can be found at: 
www.necon.co.za/emdisc.php
 
***


PGP public key at
      ldap://keyserver.pgp.com
      ldap://europe.keys.pgp.com:11370
