### ISSUE TITLE
Forgets my selections :(

### ISSUE THREAD

**Issue by emilytroutman** [tabulapdf/tabula#333]
I keep selecting the tables and when I go to download the information, the app crashes. When I re-open the document, it has forgotten what I selected. So sad! Is there a way to save my selections???

**Comment by jeremybmerrill** [comment]
There's not a way to save selections -- though maybe eventually: https://github.com/tabulapdf/tabula/issues/93

I am worried about why the app is crashing, though. That's no good. Can you describe that in greater depth? Is there an error message?

**Comment by jeremybmerrill** [comment]
@emilytroutman: please feel free to reopen this issue if you can give me the error message or a more detailed description of what steps you take that cause the app to crash.
