### ISSUE TITLE
Stream extraction results

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#335]
#332 is essentially an `OutOfMemory` exception. It shouldn't be too hard to implement a streamed response (e.g. an `Enumerator` of extracted tables) so we don't accumulate the *entire* result before sending it off to the client.

**Comment by jeremybmerrill** [comment]
If you think that'd fix the issue, great!

**Comment by jazzido** [comment]
Not streaming the response yet, but this change (7e12814268cce2fc565e1ccfb12522e601fde04b) avoids converting the extraction enumerator to an array —possibly saving memory and time.

BTW, only works with the tabula-java version of the extractor: doing it for tabula-extractor is a lot more involved (the array is materialized inside tabula-extractor)

**Comment by jazzido** [comment]
Still haven't implemented a streaming response of extracted tables, but these two changes (9ef62b0141bc2766b2d35d27b486ffe4a9bef884, e202c715f153bbc31cc775e2d148bc25d431a4e0) implement an `Enumerator` of tables in `newUI-ruby`

Closing.
