### ISSUE TITLE
Huge tables

### ISSUE THREAD

**Issue by rusimody** [tabulapdf/tabula#338]
Firstly thanks much for tabula!

One small issue:
Ive a 1000 page pdf -- 1 huge table
Any suggestions for selecting the whole lot?

**Comment by jazzido** [comment]
Hi @rusimody,

Thanks for trying out Tabula! If you're comfortable with the command line, I suggest that you try [tabula-extractor](http://github.com/tabulapdf/tabula-extractor) or [tabula-java](http://github.com/tabulapdf/tabula-java), the *kernel* that powers Tabula. It is much better suited to work with large PDFs.

Here's some instructions to help you get started: https://github.com/tabulapdf/tabula-extractor/wiki/Using-the-command-line-tabula-extractor-tool
