### ISSUE TITLE
Tabula selections move when returning to selection page

### ISSUE THREAD

**Issue by Schwanksta** [tabulapdf/tabula#339]

**Comment by jeremybmerrill** [comment]
1. Make some selections, go to the extraction page, then go back with the Revise Selections button. The selections have moved. (I could have sworn I fixed this bug.)
2. Also at lesat sometimes, the selections on the main page don't show back when you hit Repeat Selections. I thought I fixed that too, so I wonder if this is an issue with the git reverts we were doing a few weeks ago...

**Comment by jeremybmerrill** [comment]
both fixed under 2ff2ef7. not sure how this ever worked... #confused
