### ISSUE TITLE
Tabula -is not Opening

### ISSUE THREAD

**Issue by Bijuja** [tabulapdf/tabula#340]
No error messages, the icon flashes like it is opening, but nothing happens, not in the dock, not anywhere. I am running Windows 7, . Maybe it is something simple?

**Comment by kludikovsky** [comment]
I had a similar issue:
Got an SSL-error - see attached image  - in my standard chromium based Opera browser.
But it worked without any error in Firefox.

So it might have something to do with the browser or any add-ons.
![_screen_shot_2015-07-17_192907b](https://cloud.githubusercontent.com/assets/6077916/8753302/c96d120c-2cba-11e5-9938-46df1aa92440.jpg)
