### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by Temporary-Failure** [tabulapdf/tabula#347]
Yesterday worked but not anymore (0.9.7)

Internal Server Error (500)
Request Method: 	GET
Request URL: 	http://127.0.0.1:8080/
(Encoding::CompatibilityError) incompatible encodings: UTF-8 and CP850
You're seeing this error because you use Rack::ShowStatus.

What to do?

**Comment by jazzido** [comment]
Hi @Temporary-Failure,

Seems that you're running Tabula under Windows, that's a bug we're aware of. Please try [the steps described here](https://github.com/tabulapdf/tabula#user-content-encoding), it should fix the issue.
