### ISSUE TITLE
V1.0 : Unable to retrieve my previous tabula projects

### ISSUE THREAD

**Issue by hpiedcoq** [tabulapdf/tabula#349]
Hi!
Thanks you for this version 1.0, that I just installed this morning.

Apparently, even if the same project directory is used for version 0.9.7 an 1.0, version 1.0 can't reload an 0.9.7 project. Is it normal?
![sans titre](https://cloud.githubusercontent.com/assets/8553310/9131116/15d768f2-3ce9-11e5-92ed-7d95fa904490.png)

Explaination of this screenshot : the first two files were uploaded via V1.0. The others were uploaded with 0.9.7.

**Comment by jeremybmerrill** [comment]
Tabula should be able to load those projects from v0.97. Our older version of the "PDF library" didn't save page counts or document sizes, so that's why those show up as `??`. However,  if you click Extract Data, Tabula should work as expected. 

Please let us know if you weren't able to interact with the older documents properly...

**Comment by hpiedcoq** [comment]
Thanks for your answer.
No, I didn't manage to interact with my old documents.
If I try to open one of my old projects I just get a blank page.

No drama, though.

**Comment by jeremybmerrill** [comment]
This *should* work and I want to fix it, so I'm reopening.

**Comment by hpiedcoq** [comment]
Hi!
Some more feedback about this issue. I just try to instal version 1.0.0 on my lubuntu laptop, where 0.9.7 is installed and functionnal.

I do have the same issue : I see my old projects, but if I click on it, they don't open.

**Comment by jeremybmerrill** [comment]
Hi @hpiedcoq,

I was able to replicate this. It's a pretty simple bug to fix on our part (I forgot to render the page the first time if the file was processed in the older version); I'll make sure the fix gets out into the next release. Sorry about the inconvenience!

**Comment by hpiedcoq** [comment]
\o/ Nice job, Jeremy!!!!
Thank you so much for that!

**Comment by hpiedcoq** [comment]
Fixed with v.1.0.1

Thanks, you guys! \o/
