### ISSUE TITLE
(ArgumentError) comparison of Float with nil failed

### ISSUE THREAD

**Issue by mayur007** [tabulapdf/tabula#355]
PDF file: 
http://ceokarnataka.kar.nic.in/ElectionFinalroll2014/PCROLL_2014/English/WOIMG/AC169/AC1690002.pdf

Error
Tabula API version: 1.0.0
Filename: AC1690002.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/a1f68fa19b2cc054399a2c7375df1a18239a1c2a/data

(ArgumentError) comparison of Float with nil failed

**Comment by victortoulouse** [comment]
I am having the same issue with all my bank account statements.

**Comment by victortoulouse** [comment]
Ok, I've got some more information on this issue:
It seems to happen only when I use the "Autodetect Tables" feature.
If I select the relevant areas manually, the extraction works.

Also, if I clean the file a bit in Adobe Acrobat, leaving only the tables I want to extract, autodetection works fine.

**Comment by mayur007** [comment]
Yep it seems to work with manual selection.

**Comment by jeremybmerrill** [comment]
I was able to replicate the error from the first document (I won't ask you to share your bank statements, of course :) ), here's the traceback:

```
ArgumentError: comparison of Float with nil failed
	org/jruby/RubyFloat.java:615:in `<'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:296:in `snap_points!'
	org/jruby/RubyArray.java:1613:in `each'
	org/jruby/RubyEnumerable.java:865:in `inject'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:293:in `snap_points!'
	org/jruby/RubyArray.java:1613:in `each'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:290:in `snap_points!'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:218:in `get_ruling_lines!'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:204:in `horizontal_ruling_lines'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:41:in `minimal_bounding_box_of_ruling_lines'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:25:in `initialize'
	/home/merrillj/.rbenv/versions/jruby-1.7.15/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:85:in `get_area'
	/home/merrillj/code/tabula/webapp/tabula_web.rb:80:in `extract_tables'
	org/jruby/RubyArray.java:1613:in `each'
	/home/merrillj/code/tabula/webapp/tabula_web.rb:72:in `extract_tables'```

It looks like Autodetect Tables is surfacing some table selections that don't work. I'll take a look at why that is. (I'm suspecting it may be related to pagination on the selection page.)

**Comment by jeremybmerrill** [comment]
The autodetect issue is, I believe, fixed via https://github.com/tabulapdf/tabula/commit/6d5c22203e6e683eef334aa343bd33259cfabc85, which will be part of the next bugfix release. 

Thank you both for reporting this bug, it's appreciated.
