### ISSUE TITLE
Internal Server Error (500) - Autodetect tables: (NoMethodError) undefined method `-' for nil:NilClass

### ISSUE THREAD

**Issue by haematologic** [tabulapdf/tabula#356]
Here's a link to the offending document: http://www.jrcptb.org.uk/sites/default/files/2010%20Haematology%20%28amendment%202012%29.pdf
Managed to extract several tables using manual selection. **Lattice** method is great!
Using Autodetect tables then preview & export however resulted in the error below.
```
Tabula API version: 1.0.0
Filename: 2010 Haematology (amendment 2012)(1).pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/5d9d137d259c3444fd375fa1e8ffb18a3ebac05a/data

(NoMethodError) undefined method `-' for nil:NilClass
```

**Comment by jeremybmerrill** [comment]
Thank you for the bug report -- we appreciate it. This issue has been fixed in https://github.com/tabulapdf/tabula/commit/6d5c22203e6e683eef334aa343bd33259cfabc85, which will be included in the next bugfix release of Tabula, which should be released soon.
