### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by AleFeMo** [tabulapdf/tabula#361]
Hola, soy usuaria de Mac.
Convertí un PDF a Excel con Tabula, pero no aparece ningún botón para descargar. Aparece uno para exportar, pero no logro descargar el archivo csv a ninguna parte. Lo intenté en Safari y en Chrome sin éxito.

**Comment by jazzido** [comment]
Hola @AleFeMo,

Tenemos un problema con la exportación en Chrome, la vamos a resolver en la
próxima versión. Por el momento, la solución es usar Firefox.

Gracias!

**Comment by AleFeMo** [comment]
Gracias a vos!

**Comment by mtigas** [comment]
duplicate of #350
