### ISSUE TITLE
Display area co-ordinates of selected areas

### ISSUE THREAD

**Issue by psychemedia** [tabulapdf/tabula#363]
Is there a way of displaying or export the co-ordinates of areas of a PDF selected using the Tabula GUI tool that I could then use as parameter values within the Tabula extractor CLI.

Or perhaps generating a copyable CLI command from a particular selection made within the Tabular GUI?

**Comment by jeremybmerrill** [comment]
@psychemedia: We've got the latter, if you choose the `Script` Export Format option.

(Also, I think that the coordinates are output in the right format in the developer console, for this exact reason.)
