### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by zief0002** [tabulapdf/tabula#364]
Got an error and it asked me to report. The file is: http://www.ncraoa.com/PDF/BreedWeightHeightQuickRef.pdf

The error:

Tabula API version: 1.0.0
Filename: BreedWeightHeightQuickRef.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/fdb4ad5be8f41289ae25d43b093be33f3fa21d82/data

(ArgumentError) comparison of Float with nil failed

**Comment by jeremybmerrill** [comment]
Thank you for the bug report -- we appreciate it. This issue has been fixed in 6d5c222, which will be included in the next bugfix release of Tabula, which should be released soon.
