### ISSUE TITLE
Tabula for Windows doesn't export files

### ISSUE THREAD

**Issue by DuarteRV** [tabulapdf/tabula#366]
Hi,

I'm using Tabula for Windows and after extracting the tables I need, I pressed the "export" button in order to download them in a CSV file but it's not working. I don't receive any error message, it just doesn't download anything.

**Comment by jeremybmerrill** [comment]
@DuarteRV: Are you using Google Chrome?

@mtigas, could this be the same chrome issue you fixed the other day?

**Comment by DuarteRV** [comment]
Hi @jeremybmerrill , yes, I'm using Chrome.

**Comment by DuarteRV** [comment]
I've tried with Firefox and it work. Thanks!

**Comment by jeremybmerrill** [comment]
@DuarteRV: Great. Mike fixed this issue the other day and the fix will be included in the next version of Tabula; as you've discovered, the solution for now is to use Firefox. Thanks for reporting the problem -- we appreciate it.
