### ISSUE TITLE
Export button is not working

### ISSUE THREAD

**Issue by eschow** [tabulapdf/tabula#368]
I extracted data from a PDF, selected "csv" from the dropdown and clicked "export." The UI indicates that it's processing the export with the loading button and finishes, but the file is nowhere to be found and there isn't any feedback as to where it's been saved down to. I looked for it in my documents, and the search yielded zero results.

**Comment by aaronschiff** [comment]
I'm having the same problem, with Tabula 1.0 on OS X and Chrome as the browser.

**Comment by eschow** [comment]
Yes, sorry I didn't add that. I'm on Tabula 1.0 on OS X 10.9.5 and Chrome 44.

**Comment by jazzido** [comment]
Hi @eschow and @aaronschiff,

We are aware of the issue. Until it is fixed in the next bugfix release, the workaround is to use Firefox instead of Chrome.

Thanks!

**Comment by mtigas** [comment]
Fixed in version 1.0.1 — https://github.com/tabulapdf/tabula/releases/tag/v1.0.1
