### ISSUE TITLE
Non-breaking spaces in output

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#37]
If there are non-breaking spaces in a PDF, they'll show up in the output (both in the modal and the CSV). This can cause encoding problems in the CSV output (showing up as "Â " in Excel).

It's possible that the nbsps are actually some other character in the PDF -- in my example, they only show up near some italic text -- so they may be coming out of PDFBox.

At some stage in the pipeline, these should be stripped out or replaced with regular spaces.

**Comment by jazzido** [comment]
closing as ancient. we replace NBSP with normal spaces in `ObjectExtractor`
