### ISSUE TITLE
Export Feature

### ISSUE THREAD

**Issue by number-cruncher** [tabulapdf/tabula#372]
The export feature is not behaving as expected. 
The tool successful extracts the pdf->table, however when I hit 'export', it renders but doesn't appear to export to my downloads.

**Comment by jazzido** [comment]
Thanks for the report @number-cruncher. Are you using Chrome? This is a known issue for Chrome users. Until the next bugfix release (soon!), the workaround is to use Firefox.

**Comment by mtigas** [comment]
Chrome/Safari bug fixed in version 1.0.1 — https://github.com/tabulapdf/tabula/releases/tag/v1.0.1
