### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by LiamDGray** [tabulapdf/tabula#377]
[Is this likely due to my firewall? I'm on Windows 8, with ZoneAlarm firewall.]

With this PDF:
http://4thavenueyoga.com/wp-content/uploads/sites/3/2015/07/4thAveYogaSchedule_23jul2015.pdf

I got this error:

Tabula API version: 1.0.0
Filename: 4thAveYogaSchedule_23jul2015.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/b0d3cc2e7f21a2e0faeac3ecddbb00df51741603/data

(ArgumentError) comparison of Float with nil failed

**Comment by jazzido** [comment]
Hi @LiamDGray,

Thanks for your report. It's a known issue that'll be fixed on our next release due later this week.

**Comment by hpiedcoq** [comment]
Liam, 
Your pdf doesn't seem to be a text pdf but an image. For example, if you try to search for the term 'class' or 'avenue' you don't find it.

With this version, OCRized, it works with me.
https://drive.google.com/file/d/0B1YVmQyWrFA8U1VpcjlGV3Ywalk/view?usp=sharing

**Comment by LiamDGray** [comment]
Thanks, @hpiedcoq .
