### ISSUE TITLE
Tabula 1.0 discombobulated by Furman Center PDFs

### ISSUE THREAD

**Issue by jqnatividad** [tabulapdf/tabula#379]
The PDF doesn't render properly:
![select_tables___tabula](https://cloud.githubusercontent.com/assets/1980690/9419162/5c2b766a-4827-11e5-845e-0493764313a2.jpg)

And autodetect doesn't really work coz of the gridless design.

When manually selected, the parsing kinda works...

Tons of data-packed PDFs at http://furmancenter.org/research/sonychan/

**Comment by jazzido** [comment]
Thanks for the report @jqnatividad.

  - The rendering bug is due to JPedal, the PDF rendering library we rely on. It'll be fixed when we get around to switching to PDF.js (#362)
  - Indeed, autodetect won't work if the tables aren't perfectly delimited by a grid, so this behaviour is expected.
