### ISSUE TITLE
Problems when exporting data

### ISSUE THREAD

**Issue by g0ris** [tabulapdf/tabula#383]
Hi there, I'm trying to export some table but nothing happens when clicking export. Same happens to copy to clipboard option. I'm using the iOS app. Any advice?

Regards

**Comment by petehuang** [comment]
Confirming the same issue on Windows 8. Copy to clipboard works fine, but CSV export doesn't do anything

**Comment by c-wilson** [comment]
Same here on Mac OS 10.10 with Safari. Lifesaving program despite this small flaw.

**Comment by mtigas** [comment]
Fixed in version 1.0.1 — https://github.com/tabulapdf/tabula/releases/tag/v1.0.1
