### ISSUE TITLE
Can not extract PDF

### ISSUE THREAD

**Issue by agisut** [tabulapdf/tabula#384]
Hi,
Please help me to solve this problem. I can not extract any PDF document.
I got the message as below in my browser:
------------------------------------------------------------------------------------
Tabula API version: 1.0.0
Filename: 11._aceh.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/c73a32b56fafbd131a175f9dcb4913361c4c49dc/data

(ArgumentError) comparison of Float with nil failed
------------------------------------------------------------------------------------

I got the message as below in my command line:

INFO: jruby 1.7/15 (1.9.3p392) 2014-9-03 82b5cc3 on Java HotSpot(TM) Client VM 1.0.0_51-b16 +jit [Windows 7-x86]
INFO: using a shared (threadsafe!) runtime
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DATA_DIR = C:\**********\AppData\Roaming\Tabula
DOCUMENTS_BASEPATH = C:\**********\AppData\Roaming\Tabula/pdfs
ENABLE_DEBUG_METHODS = false

==================================
Launching ........
............................
............................
............................
return to this window and press "Control-C" to close it.
==================================

2015-08-24 10:53:06.807:INFO:oejsh.ContextHandler:started o.e.jw.WebAppContext{/,file:C:/**********/AppData/Local/Temp/warbler4064919576605785197webroot/tabula.jar/work/jetty-0.0.0.0-34555-tabula.jar-_-any-/webapp/},/C:/**********/tabula-win-1.0.0/tabula/tabula.jar
2015-08-24 10:53:07.389:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:34555
DEBUG: resetting rack response due exception

**Comment by jeremybmerrill** [comment]
This bug will be fixed in the next version of Tabula, which will be released soon.
