### ISSUE TITLE
Nothing happens after hitting the "export" button

### ISSUE THREAD

**Issue by scottpham** [tabulapdf/tabula#385]
On Tabula v.1.0.0, Mac OSX 10.9.5

**Comment by jazzido** [comment]
Hi @scottpham,

We are aware of the issue. Will be solved in our next bugfix release.
The workaround is to use Tabula with Firefox instead of Safari/Chrome.

Thanks!

**Comment by mtigas** [comment]
Fixed in version 1.0.1 — https://github.com/tabulapdf/tabula/releases/tag/v1.0.1
