### ISSUE TITLE
extracting the files

### ISSUE THREAD

**Issue by lindnera** [tabulapdf/tabula#386]
Hi all, 

I am using Tabula program and it is amazing. The preview of the exported tabular data looks great. However, for some reason when I click the export bottom nothing happens, and so I cannot export and save the exported tabular. 

Is there any reason for that? Do I make something wrong here?
Many thanks for your help in advance!

**Comment by jazzido** [comment]
Hi @lindnera, thanks a lot for reporting the issue.

What you describe is a known issue with Tabula 1.0.0, which will be resolved in our next bugfix release. The workaround, for now, is to use Tabula through Firefox instead of Chrome or Safari.

**Comment by mtigas** [comment]
Fixed in version 1.0.1 — https://github.com/tabulapdf/tabula/releases/tag/v1.0.1
