### ISSUE TITLE
fails to export/copy data

### ISSUE THREAD

**Issue by bllkng** [tabulapdf/tabula#388]
Get this PMC article: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2929692/

Click Table 2 to bring up as a separate window. Save as a 1 page PDF. Extract the table. The data shows up after the extraction but copy or export doesn't do anything.

**Comment by jeremybmerrill** [comment]
Are you using Chrome? There's a bug with the extraction button that will be fixed shortly.

**Comment by bllkng** [comment]
Yes, using Chrome, but fails in Safari as well.
Mac OS 10.9.5 and 10.10.5
Chrome Version 44.0.2403.157 (64-bit)
Safari Version 7.1.8 (9537.85.17.9.1)

At least the on-screen displayed table can be copied to a spreadsheet.

**Comment by bllkng** [comment]
When you do the extract on 10.9 (Chrome and Safari) you get a table displayed which you can copy with copy/paste. Export and Copy to Clipboard don't work.

When you do the extract on 10.10 (Chrome and Safari) you get 'no data' and Export and Copy to Clipboard don't work.

**Comment by jeremybmerrill** [comment]
The latter bug (10.10) is strange. Tabula works fine in Firefox for me on those platforms.

In any case, the solution for now is to use Firefox. The solution as soon as we build and release Tabula 1.01 will be to use that in any browser.

**Comment by bllkng** [comment]
Tabula 1.0.0
Mac OS 10.10.5
Firefox 40.0.3
Save Table 2 from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2929692/ as separate PDF
Fails to import data, gives 'no data'

Tabula 1.0.0
Mac OS 10.9.5
Firefox 40.0.3
Save Table 2 from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2929692/ as separate PDF
Data is correctly exported as CSV, TSV, JSON, etc. 
Copy to Clipboard fails
