### ISSUE TITLE
Auto-detect tables - suggested enhancement

### ISSUE THREAD

**Issue by baronmax** [tabulapdf/tabula#390]
Hi - hope this is the right place to file a suggestion.  I like the column extract - works well if: 1) you only have a few pages to convert or 2) you have multiple pages and they are all the same.

What doesn't work so well is multiple pages that have columns and ordinary text which vary.  Now I realise it might not be trivial to do this but it would be brilliant if the tabula could auto select what look like tables rather than having to manually select them.  You could then go through and cancel any that aren't what you want or export/import the whole caboodle into Excel and sort it there.  The thing I'm trying to do is turn 200 page pdfs of bank statements into Excel. (My bank doesn't give a .csv output option).  - I won't post an image for obvious reasons... :).  I have managed to do almost what I want by exporting the pdf as text and then using search and replace on specific columns to insert tabs and then filter it in Excel but its a bit time consuming.

Anyway maybe this need isn't that widespread but thought I'd give you my tuppence worth as a suggestion.  Thanks very much for the program!

**Comment by hpiedcoq** [comment]
Baronmax,
This is my main and daily use of Tabula. If you want to talk about it, and share experience, You can contact me by mail : herve [dot] piedcoq [AT] gmail [dot] com.
IMHO, using Excel to perform what you intend to do is too complicated. Other solutions exists.
H.

**Comment by jeremybmerrill** [comment]
@baronmax: Happy to hear your suggestion! We'd LOVE to be able to autodetect all tables. However, it's just kinda difficult or even impossible. We have an autodetect feature that works pretty well if the tables have ruling lines. It doesn't work at all if text is arranged into a table shape without any actual lines in the PDF. There's not much hope on that front, unless you have a terrific idea on how to programmatically determine table structure from words alone in a "mixed" (i.e. tables and free text) context.  (in which case, we're all ears.)

Have you tried the autodetect feature?

**Comment by baronmax** [comment]
Hi Jeremy Thanks for the reply and suggestion! Yes, I did try the auto detect feature - interestingly with one single bank statement pdf (as I had  downloaded) the auto detect was greyed out - not sure why.  However on my merged bank statements (where I'd merged all the pdfs into one) I could select auto detect.  What happened then was that an area corresponding to a bar code on the left hand margin was selected as the table, so obviously the extract failed.  In my case all of the tables (and columns) I'm interested in are bound by a single line box - that's what I was thinking tabula could auto-detect programmatically (albeit the bar code is a complication I hadn't thought of!).  In my case this could theoretically be ignored programmatically if tabula ignored anything that  a) didn't have any text in it and b) is outside a margin (defined by the user).  In other words if you could set the 'area of interest' in tabula then the auto detect might work, particularly if you could tell it that you were looking for a certain number of columns in table....  Anyway that's my suggestion!  Looking a bit at the documentation it appears the command line route might work in this way, albeit I haven't tried this.

**Comment by baronmax** [comment]
oops sorry didn't mean to close this

**Comment by jeremybmerrill** [comment]
Thank you for your suggestion, @baronmax. Our [Ruby library](http://github.com/tabulapdf/tabula-extractor) would allow you to write code to set an area of interest and look for tables within there. It's not likely that we'd implement that in the web UI, since it sounds fairly complicated to design (and similar to the Lattice extraction method).

Your point about excluding autodetected tables without any text is a good one though and I'll look into implementing that...
