### ISSUE TITLE
Tabula files location

### ISSUE THREAD

**Issue by lamaladroite** [tabulapdf/tabula#391]
Hello, 
I have followed all the steps to convert my PDFs to CSV files but when I click export, nothing happens. My files are nowhere to be found. What am I doing wrong?

Thanks in advance!

**Comment by jazzido** [comment]
Hi @lamaladroite,

This is a known issue that will be fixed in the next version of Tabula. In the meantime, you can workaround the problem by using Firefox instead of Chrome or Safari.

Thanks!
