### ISSUE TITLE
I'm new and have no idea why it failed ... But I provide the pdf

### ISSUE THREAD

**Issue by MartinHvidberg** [tabulapdf/tabula#395]
Tabula API version: 1.0.0
Filename: 05 Baffin 1822 (Scoresby).pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/f4588a5c4e54b7c2a89dd7c2368cccf07106f0f0/data

(NoMethodError) undefined method `-' for nil:NilClass

http://hvidberg.net/Martin/temp/05%20Baffin%201822%20%28Scoresby%29.pdf

**Comment by jeremybmerrill** [comment]
This is a known issue with Tabula 1.0.0. The next version of Tabula (v1.0.1) will fix this issue and will be released very very soon.

Right now, you can try an [older version of Tabula](https://github.com/tabulapdf/tabula/releases/tag/v0.9.7) -- or just wait until v1.0.1 is ready.
