### ISSUE TITLE
All works fine except exporting the data

### ISSUE THREAD

**Issue by Kristofp** [tabulapdf/tabula#397]
Nothing happens when I click export (mac version)

**Comment by Chester-Gillon** [comment]
With tabula-win-1.0.0 under Windows 8 I had the same problem in that nothing happens when I click export with the Export Format set to CSV.

With tabula-1.0.0 under Linux (CentOS 6) the export button works, in that it opens a dialog to ask how to open a file named tabula-<*PDF_basename*>.csv

**Comment by Kristofp** [comment]
I see it wants to submit the form to this url: http://127.0.0.1:34555/pdf/045eb7e5a33da45169da34856809d60ff8f99172/data?format=csv

Loading this url directly doesn't do anything either. 

I doesn't work under safari, chrome and opera ( all latest versions)
However it does work under Firefox.

**Comment by Chester-Gillon** [comment]
OK, it could be browser related. Under Windows 7 which failed tabula was run in Opera. Under CentOS which worked tabula was run in Firefox.

**Comment by jeremybmerrill** [comment]
Yes, it is browser related. Unfortunately, Tabula 1.0.0's download function
is only working in Firefox right now.

Tabula 1.0.1 will fix this issue and we hope to have it released very very
soon.

Very sorry for the inconvenience!

**Comment by Kristofp** [comment]
thanks Jeremy, it's a wonderful tool, I'm amazed how good it works actually.  Very user friendly as well. Looking forward to the new version.

**Comment by jeremybmerrill** [comment]
Thanks, glad you find it useful!
