### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by intrtxt** [tabulapdf/tabula#398]
Unpacking zip-file (with WinZip) resulted in error message: corrupt file? And since Chrome doesn't work with Java anymore, what browser do you recommend?

**Comment by jeremybmerrill** [comment]
The Windows zip is valid (I just checked), so there was probably just a download error. Can you try downloading it again?

Tabula should work fine with Chrome*. The Java app runs on your desktop and creates a local web server that Chrome accesses, so the fact that Chrome no longer runs Java plugins isn't a problem.

* The caveat is that there's a known bug where you can't download data -- you can copy it to the clipboard though -- in Chrome/Safari. If you want to use Chrome, wait for Tabula 1.0.1 which should be released very very soon; or you can use Firefox.
