### ISSUE TITLE
"Copy to clipboard as TSV" should be available

### ISSUE THREAD

**Issue by bradland** [tabulapdf/tabula#40]
Excel has a nice "quick and dirty" clipboard import/export feature using tab-separated-values (TSV). If you copy a range of cells from Excel, they're placed on the clipboard using TSV format. Likewise, if you already have some TSV data in your clipboard, you can paste it in to Excel and it will paste it across columns as expected. This behavior (unfortunately) does not work for comma-separated-values, so the existing clipboard feature has limited utility.

Things needed:

* tabula_web.rb `pdf/:file_id/data` matcher should handle `req.params['format']=='tsv'`
* PDF view and js should include a "Copy to clipboard as TSV" widget

I'm submitting a pull request with a `pdf/:file_id/data` matcher that handles `format==tsv`. I started to take a crack at the interface, but it looks like there are other issues where committers are working on significant changes, so I didn't want to conflict there.

**Comment by jeremybmerrill** [comment]
This is done, isn't it? Implemented in newUI, at least.
