### ISSUE TITLE
Error (500) - (ArgumentError) comparison of Float with nil failed

### ISSUE THREAD

**Issue by jvanecek** [tabulapdf/tabula#401]
Got the error below while parsing this [document](http://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164C-2011-PDF-E.pdf).

Tabula API version: 1.0.0
Filename: T-SP-E.164C-2011-PDF-S.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/4f0feb5af5d09c645b1a053fc4e09f5a693ae6dc/data

(ArgumentError) comparison of Float with nil failed

**Comment by jeremybmerrill** [comment]
It's a known issue and we'll have a fix for this really really soon.

**Comment by jvanecek** [comment]
Cool, anyway my case I just solved it. It was trying to parse the "ITU" logo and there it yields. I selected the proper tables and worked like a charm!
Thanks!
