### ISSUE TITLE
Is there any suggestion to split pdf

### ISSUE THREAD

**Issue by yoonasun** [tabulapdf/tabula#404]
I want to "know Is there any suggestion to split page self instead of drawing rectangle manually". Any effective way to judge some tables area automaticlly

**Comment by yoonasun** [comment]
I want to "know Is there any suggestion to split page self instead of drawing rectangle manually". Any effective way to judge some tables area automaticlly

**Comment by jeremybmerrill** [comment]
Tabula has an button to automatically detect the location of your tables. It's on the top left of the selection page. It only works if your table has ruling lines on all sides. Try it out and let me know how it goes.
