### ISSUE TITLE
Export to where?

### ISSUE THREAD

**Issue by rareal** [tabulapdf/tabula#405]
Hi,
The export bottom is not working for me (Chrome, win8). The copy to clipboard doesn't work very well, when I paste the data in excel the result is not the same of tabula's preview. If I click the export, doesn't matter the format, it loads and nothing else happens. Is it exporting to some place that I don't know?
thanks

**Comment by jeremybmerrill** [comment]
Are you using Tabula v1.0.0 or v1.0.1? You should try the newest one, v1.0.1.

The new version, v1.0.1, (released last week) fixes the problem you're having where the download button is broken in Chrome. 

(Or, you can try selecting the TSV option in the dropdown, then click Copy to Clipboard, which may work better for copy-pasting into Excel.)
