### ISSUE TITLE
Tabula

### ISSUE THREAD

**Issue by aniwork87** [tabulapdf/tabula#406]
I have the latest PDF reader version. Yet when i upload a PDF file, tabula asks me to get the latest version. Please help

**Comment by jazzido** [comment]
Hi @aniwork87,

That is strange. Latest version is 1.0.1, but the update is not mandatory, although we recommend it.

**Comment by jeremybmerrill** [comment]
(I just confirmed that in v1.0.1 I'm not seeing the spurious update notification.)

**Comment by aniwork87** [comment]
Hi,

So i am not able to viw the file in the browser and thus i am not able to
extract tables as well

On Fri, Sep 25, 2015 at 9:11 PM, Jeremy B. Merrill <notifications@github.com

**Comment by aniwork87** [comment]
Check out the screen shot

**Comment by jazzido** [comment]
@aniwork87, github drops attachments when you reply to an issue by email. please reattach the screenshot through the web site.
