### ISSUE TITLE
Not detecting tables in this PDF 

### ISSUE THREAD

**Issue by avdata99** [tabulapdf/tabula#407]
https://github.com/avdata99/padrones-electorales/blob/master/padronesAProcesar/Concepcion-Entre-Rios-Paso-2015/01-Padron-Concepcion-Entre-Rios.pdf?raw=true

Also can't read data if I manually select one table.

Ubuntu + java-7-openjdk-amd64

**Comment by jazzido** [comment]
That's a monstrosity, @avdata99 :)

Although there is definitely a tabular structure in the information contained in that document, there are a lot of elements that will make Tabula's algorithm fail miserably; especially the overlayed "watermark" huge characters.

Did you try processing the output of Poppler's `pdftotext -layout`?

**Comment by avdata99** [comment]
Termine usando *pdfedit* que me dio algo mas o menos masticable.
Gracias.
