### ISSUE TITLE
Tabula not opening

### ISSUE THREAD

**Issue by NishaT** [tabulapdf/tabula#415]
Tabula isn't opening it is saying can't connect. 

Err_Connection_Refused

I'm running windows 7. I just downloaded it last month, and i tried opening it in chrome and firefox.

**Comment by NishaT** [comment]
Have tried firefox, uninstalled and reinstalled, updated java no luck. still won't connect.  it has been working great up until today.

**Comment by NishaT** [comment]
Ah! Windows was for some reason stopping java with the firewall. Issue resolved!

**Comment by jeremybmerrill** [comment]
@NishaT Glad you solved the issue! And thanks for documenting it here, hopefully if anyone else runs into it, they'll find this thread and find the solution.
