### ISSUE TITLE
pdf has a "fainter" line in the table, which is not picked up in lattice mocde

### ISSUE THREAD

**Issue by EvanSmithMSMD** [tabulapdf/tabula#427]
[000153061.pdf](https://github.com/tabulapdf/tabula/files/36088/000153061.pdf)

Looking at this table I tried using columns, but was unable to figure out what the -c setting would be as I think I must use the "lattice" mode.

But a bigger issue is in lattice mode the last column is never "seen" as I think the vertical column is to faint.

Ideas?

Thanks!
Evan

**Comment by EvanSmithMSMD** [comment]
Also what is the command line argument to say use "lattice" when using tabula from the command line?

**Comment by jeremybmerrill** [comment]
Hi @EvanSmithMSMD,

The command-line argument for using lattice mode is `--spreadsheet`, "spreadsheet mode" being the old name for lattice mode. (I should get around to updating that...)

I'm not seeing the problem you're getting with the fainter line -- that is to say, though I don't have your expert eye, Tabula's reconstruction of the table looks accurate... Lattice mode should pick up all lines, regardless of color. Can you tell me which page you're looking at and send the output you're getting, so I can compare? Happy to continue to help debug this problem.

**Comment by EvanSmithMSMD** [comment]
Hello,

All seems to work now that I understand --spreadsheet mode.

I did modify my copy of your ruby code to replace \r with a " ", as I 
found the "" replace to make a mess.

Otherwise, great stuff.

Evan

Jeremy B. Merrill wrote:
>
> Hi @EvanSmithMSMD <https://github.com/EvanSmithMSMD>,
>
> The command-line argument for using lattice mode is |--spreadsheet|, 
> "spreadsheet mode" being the old name for lattice mode. (I should get 
> around to updating that...)
>
> I'm not seeing the problem you're getting with the fainter line -- 
> that is to say, though I don't have your expert eye, Tabula's 
> reconstruction of the table looks accurate... Lattice mode should pick 
> up all lines, regardless of color. Can you tell me which page you're 
> looking at and send the output you're getting, so I can compare? Happy 
> to continue to help debug this problem.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/tabulapdf/tabula/issues/427#issuecomment-159016501>.
>

-- 


Evan C. Smith, MS, MD
Evan.Smith.MS.MD@gmail.com
Cell: 781-879-8736

**Comment by jeremybmerrill** [comment]
Great, glad you were able to get the results you needed! There's a command-line option that should solve the other problem too, `--use-line-returns` will put in \n (which you can then replace with " " if that's all you want). 

The question of what to do with text on multiple lines is unfortunately a really complicated one, since sometimes line-breaks are just long text that didn't fit on one line and sometimes they're meaningful -- but the PDF format doesn't give us much in the way of hints.

Closing this, since it sounds like you've got the problem resolved.

**Comment by EvanSmithMSMD** [comment]
Cool.  Thanks for the help!!
