### ISSUE TITLE
Edit table on Preview section

### ISSUE THREAD

**Issue by sashsvamir** [tabulapdf/tabula#429]
You have planned in future make simple edit table on Preview page (merge/separate cells, move data from one cell to another and etc) before export?

**Comment by jeremybmerrill** [comment]
Hi @sashsvamir, we've considered it, but I think [we decided not to](https://github.com/tabulapdf/tabula/issues/172). We think Tabula is best suited to do only one thing, that is, extracting data from PDFs. If you want to edit the output spreadsheets, you should use a dedicated spreadsheet editing tool like LibreOffice Calc, Google Sheets or Microsoft Excel. Those tools do a far better job at editing spreadsheets than Tabula would.
