### ISSUE TITLE
Any way to use command line to input the manually selected table area? 

### ISSUE THREAD

**Issue by w013ccw** [tabulapdf/tabula#434]
Hi,

The tables in my pdf sometimes don't have the most-left and most-right lines. Using tabula-extractor, it only extracts the content in middle area. 

Since tabula browser interface has ability to let user select area, I am wondering if I can use this feature from command line. Say, input 4 coordinates of the table frame, and get the cvs extraction. Thanks.

**Comment by jeremybmerrill** [comment]
Hi, you sure can! 

You'll want something like: 

`tabula path_to_your_pdf.pdf --area 250,0,325,1700  --pages 1 -o output.csv`

You can see more details on how to use tabula-extractor in that project's README: https://github.com/tabulapdf/tabula-extractor/

In the Tabula GUI, you can choose "Script" as a download option and it will include the coordinates of your selected table frame in a script like the example I gave above. That's probably your best option (that's what I use).

Let us know if you need help...

@jazzido: This sounds like another example of when using the frame as boundaries for lattice/spreadsheet mode would be useful.

**Comment by w013ccw** [comment]
Hi @jeremybmerrill ,

I still cannot make it work. Using tabula with lattice method doesn't extract most left/right columns. 

My solution right now is using pdfbox to draw two lines as boundaries.

**Comment by jeremybmerrill** [comment]
If you'd like me to take a look, can you send me a link to the PDF? (or attach it via the Github issues interface -- attaching it to an email reply won't work)

**Comment by w013ccw** [comment]
Hi, here it is, the pdf is written in Chinese. But I believe you can see the csv isn't in correct format. 

I used this command,  thanks.

tabula test-p20.pdf--format CSV -r -o test.csv

[Uploading test-p20.pdf…]()

**Comment by w013ccw** [comment]
Hi, here it is, the pdf is written in Chinese. But I believe you can see the csv isn't in correct format. 

I used this command,  thanks.

tabula test-p20.pdf--format CSV -r -o test.csv

[test-p20.pdf](https://github.com/tabulapdf/tabula/files/60320/test-p20.pdf)

[test.txt](https://github.com/tabulapdf/tabula/files/60321/test.txt)
