### ISSUE TITLE
HIV error text 

### ISSUE THREAD

**Issue by evaconstantaras** [tabulapdf/tabula#436]
Tabula API version: 1.0.0
Filename: HIV data.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/bf7aef86f0d339a076511ca5a2c3141e97abaa31/data

(ArgumentError) comparison of Float with nil failed
[HIV data.pdf](https://github.com/tabulapdf/tabula/files/47060/HIV.data.pdf)

**Comment by jeremybmerrill** [comment]
Hi @evaconstantaras: Please download and use [Tabula 1.0.1](https://github.com/tabulapdf/tabula/releases/tag/v1.0.1). (We've fixed that bug in the new version.)
