### ISSUE TITLE
Add-On Feature

### ISSUE THREAD

**Issue by ryanjmarcus** [tabulapdf/tabula#440]
First of all, would like to say: brilliant work. Elegant and smooth.

Okay, so with my line of work, I download gas bills (.pdf) of my clients for the previous 12 months. Each bill looks exactly the same, except the amount of therms changes each month. So I have to individually open each pdf look at the amount of therms used each month. Then I have to add all the therms for the previous 12 months up. So, I was wondering...

1.) First, would a folder upload option be possible?
2.) When I custom select the table area (for it to grab the therms)---could you make it where that area would be used for all the other pdfs uploaded as well. Maybe, you could select the table and then click apply to all? 
3.) Lastly, once 2 is possible, would there be a way to view (in the preview screen) the sum of all the values up? Like a quick excel f(x) formula but in the preview screen?

Thanks
Please get back to me.
Keep up the hard work.
-Ryan

**Comment by jazzido** [comment]
Thanks for your comments, @ryanjmarcus.

> 1.) First, would a folder upload option be possible?

Multiple upload already works. In the file-upload dialog, just CTRL-click to select multiple PDFs. That should do the trick./

> 2.) When I custom select the table area (for it to grab the therms)---could you make it where that area would be used for all the other pdfs uploaded as well. Maybe, you could select the table and then click apply to all?

That feature has been in our backlog for some time now. While it's not possible to do it from Tabula's UI, you can get that functionality through our command line application.

> 3.) Lastly, once 2 is possible, would there be a way to view (in the preview screen) the sum of all the values up? Like a quick excel f(x) formula but in the preview screen?

We try to keep our UI as simple as possible. Our focus is on building a great table scraper, and not a semi-good spreadsheet. The feature you suggest would fall our of our scope.

Thanks again!
