### ISSUE TITLE
Accent Detection

### ISSUE THREAD

**Issue by mucavv** [tabulapdf/tabula#443]
Is it possible to detect the accents in works like "português" or "administração"?

**Comment by jazzido** [comment]
Hi @mucavv,

Sometimes PDF documents encode accents in non-standard ways. Can you attach to this issue the PDF that you're trying to process?

**Comment by mucavv** [comment]
Hi @jazzido,

Thanks for the quick reply. 
The problem was really with the PDF I was using. Others PDFs are converting correctly.

Thanks
