### ISSUE TITLE
Failed PDF conversion

### ISSUE THREAD

**Issue by guy4261** [tabulapdf/tabula#447]
Hello,
Tried to convert this PDF:
[2014-12-08-2015-01-07.pdf](https://github.com/tabulapdf/tabula/files/62173/2014-12-08-2015-01-07.pdf)

And got out this table (this is CSV, changed suffix to .txt so that github would let me upload it):
[tabula-2014-12-08-2015-01-07.csv.txt](https://github.com/tabulapdf/tabula/files/62172/tabula-2014-12-08-2015-01-07.csv.txt)

I got this PDF from my cellphone operator - this is a list of calls I made. The PDF is in Hebrew (which is a right-to-left language) and I have no idea how it was created and why some columns are chopped correctly and some are not.

**Comment by jazzido** [comment]
Hi @guy4261,

Tabula frequently has issues with the table headers. More specifically, if a header spans more than 1 column of a table, and it's included in the selection, results might not be optimal. I tried making a selection that does not contain the table header and it seems to work:

![screen shot 2015-12-15 at 12 19 10 pm](https://cloud.githubusercontent.com/assets/27584/11818063/3d4623d0-a326-11e5-8306-8eef979e6092.png)

![screen shot 2015-12-15 at 12 21 17 pm](https://cloud.githubusercontent.com/assets/27584/11818085/5dfa4ea8-a326-11e5-8923-ade21108052a.png)


Thanks!

**Comment by guy4261** [comment]
You're awesome!!! Thanks!!!
I opened  this issue because the UI said I should contact the developers if I fail. Maybe you should add this header warning to the UI so that less people would bother you :)
Thanks again!!!
