### ISSUE TITLE
Auto-detect missing last line of table when exporting

### ISSUE THREAD

**Issue by tforward** [tabulapdf/tabula#448]
Example attached

> Import Table
> Extract Data
> In Preview Mode, Note: The last entry in each table.
> When Autodetect tables it grabs everything except the last entry of each row.

> If I manually move the selection area down slightly on each it will pick up everything I need.

> Don't know if you can adjust the tolerance of the Auto-Select to grab a bit more at the bottom without compromising things elsewhere.

[report dump_tables.pdf](https://github.com/tabulapdf/tabula/files/78420/report.dump_tables.pdf)

**Comment by jeremybmerrill** [comment]
Hi @tforward, thanks for the bug report. It's a known bug, but we haven't figured out the right way to solve it yet. Feel free to check out discussion in https://github.com/tabulapdf/tabula-extractor/issues/99
