### ISSUE TITLE
borderless tables ?

### ISSUE THREAD

**Issue by b44p** [tabulapdf/tabula#449]
Any suggestions on how to wield these kind of tables ?

https://nycfuture.org/pdf/State-of-the-Chains-2015-5.pdf

**Comment by jeremybmerrill** [comment]
Does "Stream mode" not handle them correctly? It looks like it ought to.

**Comment by b44p** [comment]
Stream worked like a charm ! Thanks!

**Comment by jeremybmerrill** [comment]
Hooray! Glad to hear it.

Jeremy B. Merrill
