### ISSUE TITLE
Installation on Mac OS, Tabula.app only opens Apache Tomcat/ homepage

### ISSUE THREAD

**Issue by kavitarege** [tabulapdf/tabula#453]
I have downloaded and unzip tabula.zip on my Mac os, When I click on Tabula.app, it only opens Apache Tomcat/ home page
![screen shot 2016-01-27 at 17 07 15](https://cloud.githubusercontent.com/assets/4427792/12619330/ca1c3d90-c517-11e5-8a63-a13522ad912b.png)

How to go about it,

**Comment by jazzido** [comment]
Hi @kavitarege,

Seems that you have Apache/Tomcat running on port 8080. Unfortunately, it's not possible to change the port number from Tabula.app. If you can't stop the process bound to port 8080, download the JAR distribution of Tabula and start it from the command line as:

```
java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Dwarbler.port=9999 -jar tabula.jar
```
