### ISSUE TITLE
Internal Server Error - Gem Rack problem

### ISSUE THREAD

**Issue by pedro-stanaka** [tabulapdf/tabula#457]
Whenever I start the server with

```java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -jar tabula.jar```

It returns the following error to me:

![captura de tela de 2016-02-05 10 00 45](https://cloud.githubusercontent.com/assets/2609731/12845763/5589847c-cbef-11e5-81f3-0b6fc5b67cff.png)

I'm looking in to the error myself, but I just wanted to report the bug...

**Comment by jazzido** [comment]
Closed by #458, thanks!
