### ISSUE TITLE
The data of the last column was missing with Lattice algorithm

### ISSUE THREAD

**Issue by LittleLakeFish** [tabulapdf/tabula#467]
Firstly, I want to say Tabula is the greatest tool I used for PDF table extraction, thanks for your great job!
I met a small problem, when I use the stream algorithm to do the extraction, one row in the original pdf file will be extracted two rows (because there is negative sign in the table data). Then I used the Lattice algorithm, it did very well (the data and it's negative sign can be put in one table cell), but the data of last column was missing(Please see the attachment for detailed information).
How can I get all the data with Lattice algorithm?
![lattice](https://cloud.githubusercontent.com/assets/17400379/13211527/f13977f6-d973-11e5-8054-2ac9af92edb5.png)
Tabula version is Tabula 1.0.1
Platform windows 7
Thanks a lot for your kindly help!

**Comment by jeremybmerrill** [comment]
Hi LittleLakeFish, 

Can you send us the original PDF? It'll help us debug. 

One thing to check is to expand your selection to the right by a few pixels, to make sure it really includes the entirety of the right boundary line.

**Comment by LittleLakeFish** [comment]
Hi jeremybmerrill,

I have sent the PDF to your mailbox, because the data is sensitive.
Thanks a lot for your help!

**Comment by jeremybmerrill** [comment]
I can confirm the problem. I don't see a solution with the latest version of Tabula, but the current master branch works properly. @jazzido @mtigas Do we think we're ready to release --  maybe as a beta -- a packaged version with tabula-java?

**Comment by jazzido** [comment]
Definitely. Let's not t forget about bundling latest JRuby, tho.

**Comment by jeremybmerrill** [comment]
Oh weird, there's no stable warbler for JRuby 9.0.*. (It's at 2.0.0.rc2, so likely soon, but who knows what troubles that could introduce.)

**Comment by jazzido** [comment]
Let's just stay with the latest JRuby release in the 1.7 branch, then.

**Comment by jeremybmerrill** [comment]
I built the jar with jruby-jars 9.0.5.0 and Warbler 2.0.0.rc2 and it seems to work fine. 

Jar: https://www.dropbox.com/s/88h90rhm0wg5iul/tabula.jar?dl=0

And, @LittleLakeFish, here's a Windows build you can try, off of master. I haven't tested it AT ALL, but it theoretically ought to work. Please let me know if it works for you. https://www.dropbox.com/s/jde2mh8n98ax99c/tabula-win-rev514181232a84c99742ddf40d56c87aeedf0bc7a8.zip?dl=0

**Comment by jeremybmerrill** [comment]
here's a branch with JRuby 9000 and warbler 2.0.0.rc2 https://github.com/tabulapdf/tabula/tree/feature/jruby9000, which is what I built the above from

**Comment by LittleLakeFish** [comment]
@jeremybmerrill The new package works very well, very sorry I can't post the nice result here.
Thanks a lot for your great job! @jeremybmerrill @jazzido @mtigas
