### ISSUE TITLE
Selection size/position is wrong with rotated pages

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#468]
![screen shot 2016-02-25 at 10 55 52 am](https://cloud.githubusercontent.com/assets/27584/13325069/5c5201de-dbae-11e5-992d-824b34c9cba9.png)

Test PDF: [tabla_subsidios.pdf.zip](https://github.com/tabulapdf/tabula/files/146845/tabla_subsidios.pdf.zip)

Also, when manually selecting an area, the extractor returns incorrect data.

@jeremybmerrill, can you take a look at this when you get the chance? The pre-redesign UI had logic to handle this case.

**Comment by jeremybmerrill** [comment]
I'll take a look soon. Is that file the same tabla_subsidos.pdf as https://github.com/tabulapdf/tabula-extractor/blob/master/test/data/tabla_subsidios.pdf?

**Comment by jazzido** [comment]
Yes.

**Comment by jazzido** [comment]
The problem can also be reproduced with this document: https://github.com/tabulapdf/tabula-extractor/blob/master/test/data/strongschools.pdf

**Comment by jeremybmerrill** [comment]
I can only reproduce with strongschools, not tabla_subsidios. 

1. Load up the PDF
2. Make a selections
3. See that stuff is excluded that should be included, and vice versa.

With strong schools, autodetect also gives me totally incorrect selections (outside the page area, etc.)

**Comment by jeremybmerrill** [comment]
Looks like maybe a selection is being scaled wrong?

**Comment by jeremybmerrill** [comment]
See the ternaries on these two lines: 
https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/pdf_view.js#L1155
https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/pdf_view.js#L67
If we add ` && false` so only the last fork is every executed, it appears to work properly. This suggests that something else is doing the rotating (so that where in older versions of Tabula, rotated pages had to be rotated by the client-side UI, but that maybe now the images generated are pre-rotated). Is it possible that tabula-java or newer PDFBox or something has made this change?

**Comment by jeremybmerrill** [comment]
https://github.com/tabulapdf/tabula/tree/bugfix/468 contains a proposed fix -- I'm surprised that this works, and want to track down the reason why it does work before merging...

**Comment by jeremybmerrill** [comment]
> This suggests that something else is doing the rotating (so that where in older versions of Tabula, rotated pages had to be rotated by the client-side UI, but that maybe now the images generated are pre-rotated). Is it possible that tabula-java or newer PDFBox or something has made this change?

@jazzido Any ideas? I wanna merge this if we can track down why it happened.

**Comment by jazzido** [comment]
Closed via #504

**Comment by psychemedia** [comment]
I'm getting all sorts of weird auto-detection failures with the `tabula-mac-1.1.0c.zip` download on a Mac.

For example, nested tables :

<img width="706" alt="select_tables___tabula_and_downloads2" src="https://cloud.githubusercontent.com/assets/82988/21619206/98cf741e-d1e6-11e6-8608-258da6042cd3.png">

Overflowed highlighted areas in [this data file](https://www.iwight.com/azservices/documents/2812-AssetListSept16.pdf):

<img width="1228" alt="select_tables___tabula" src="https://cloud.githubusercontent.com/assets/82988/21619207/98d406be-d1e6-11e6-817e-055777bf101b.png">
