### ISSUE TITLE
Use the stream method in tabula-java

### ISSUE THREAD

**Issue by javshak** [tabulapdf/tabula#473]
I might be asking another newbie question but whats the way to use the stream algorithm in tabula-java? As I understand the Lattice method is the default one. Thanks again! Oh and yes forgot to mention your little tool is kick-ass and you have no idea how much it has helped our team.

**Comment by jeremybmerrill** [comment]
@javshak: Nah, not a n00b question. We need to fix the documentation. Glad Tabula's useful to you :)
We've referred to the extraction methods in a couple of different ways over the years.

Lattice = Spreadsheet
Stream = No-Spreadsheet = Original

So, in tabula-java, you'll want to use the `--no-spreadsheet` switch.
