### ISSUE TITLE
Import hangs at "Waiting to be processed" under IE 11

### ISSUE THREAD

**Issue by jlitwiller** [tabulapdf/tabula#474]
When pulling up Tabula under IE 11, any PDF I try to import stalls saying "Waiting to be processed".  The console shows the message "DEBUG: resetting rack response due exception"

Import works correctly under Chrome or Firefox.  I have tested this on multiple PCs.

Other details:  every machine tested was running Windows 7 Pro, have encountered the problem under Java versions 8.60 and 8.71

**Comment by jeremybmerrill** [comment]
Ah, yes. We need to re-build and re-release to fix this problem, it's the same as https://github.com/tabulapdf/tabula/issues/408. 

Until we make a "full" release, here's a prerelease version that will work: https://www.dropbox.com/s/npvrzlx4lz0tn42/tabula-win.zip?dl=0
