### ISSUE TITLE
Looks like it does not support Chinese

### ISSUE THREAD

**Issue by liuhmthu** [tabulapdf/tabula#475]
It looks fine in preview, but everything crashed when exporting as csv, all Chinese turned into "???". Any measures to quickly fix it?

**Comment by jazzido** [comment]
thanks for reporting, @liuhmthu.

Can you provide us with the PDF you were using?

**Comment by liuhmthu** [comment]
[15H1.pdf](https://github.com/tabulapdf/tabula/files/168351/15H1.pdf)

**Comment by liuhmthu** [comment]
Thx!

**Comment by liuhmthu** [comment]
I guess it's a pretty common Java language issue. "charset=GBK" will output Chinese

**Comment by jazzido** [comment]
Fixed in 1.1.0
