### ISSUE TITLE
Mac OS 10.9.5 / Safari 9.0.3

### ISSUE THREAD

**Issue by mwhybark** [tabulapdf/tabula#476]
Tabula 1.0.1

Previously ran Tabula 1.0 with no issue. Tabula opens and launches browser window, showing previous file set.

Clicking 'Browse' instantiated file-open dialog. However, only the first folder in a selected directory structure is displayed and no files are shown as eligible for opening.

Using Default Folder, it is possible to change the open-file dialog focus to a new folder containing only PDFs; no files are shown as eligible for opening.

Please advise. Thank you!

**Comment by jeremybmerrill** [comment]
Hi @mwhybark: 

Can you send a screenshot of what you're seeing? 

Two possibilities:

1. This sounds like a browser problem -- the filepicker is implemented by the browser and just instantiated by the file HTML <input> tag, so Safari is what's in charge here. Tabula did nothing but start
2. Are you sure the PDFs are proper PDFs, not, say, HTML saved with a PDF extension? The browser should not allow you to upload anything whose mime type isn't `application/pdf`.

**Comment by mwhybark** [comment]
I will if it happens again - I was noticing some other oddities in the
finder with regard to file system display and concluded I needed to reboot
(and possibly back up!) asap. So table this for now but if it comes back I
will pursue documentation.

On Thu, Mar 17, 2016 at 1:28 PM, Jeremy B. Merrill <notifications@github.com
> wrote:

> Hi @mwhybark <https://github.com/mwhybark>:
>
> Can you send a screenshot of what you're seeing?
>
> Two possibilities:
>
>    1. This sounds like a browser problem -- the filepicker is implemented
>    by the browser and just instantiated by the file HTML tag, so Safari is
>    what's in charge here. Tabula did nothing but start
>    2. Are you sure the PDFs are proper PDFs, not, say, HTML saved with a
>    PDF extension? The browser should not allow you to upload anything whose
>    mime type isn't application/pdf.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tabulapdf/tabula/issues/476#issuecomment-198068564>
>



-- 
Mike Whybark - mwhybark@gmail.com

**Comment by jeremybmerrill** [comment]
@mwhybark: Okay. That would have been my other suggestion -- to reboot -- so I'm going to close the issue as likely a browser/OS problem that's not Tabula-specific. If it recurs, please do re-open the ticket and we'll work on finding a solution.

Good luck with the back ups; I hope it's not a data loss problem!

**Comment by jeremybmerrill** [comment]
@mwhybark: Okay. That would have been my other suggestion -- to reboot -- so I'm going to close the issue as likely a browser/OS problem that's not Tabula-specific. If it recurs, please do re-open the ticket and we'll work on finding a solution.

Good luck with the back ups; I hope it's not a data loss problem!
