### ISSUE TITLE
a second JSON export option should exist with data in 2d-array format

### ISSUE THREAD

**Issue by wbuchanan** [tabulapdf/tabula#477]
New issue requested after response to [Issue 325](https://github.com/tabulapdf/tabula/issues/325#issuecomment-195397974).    What I assumed was that the export/output functionality would return a JSON Object Array/two dimensional array with the contents of the table in it.

**Comment by jeremybmerrill** [comment]
Cool. Do you need any metadata at all?

**Comment by wbuchanan** [comment]
I didn't have any use for it myself, but I could see how exporting a selection area could be useful if someone needed to parse the same document in the future.

**Comment by jeremybmerrill** [comment]
Got it. It sounds like the internal API's response (the pdf/<id>/data response) probably does the trick. A fix for this would probably just look like holding onto that response and returning it again as a download.

**Comment by jeremybmerrill** [comment]
it's this request: https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/pdf_view.js#L289-L333

**Comment by jeremybmerrill** [comment]
I shoulda done this earlier, this took like five minutes. :shruggie:
