### ISSUE TITLE
Advice on OCR tools to use (No problem with tabula)

### ISSUE THREAD

**Issue by javshak** [tabulapdf/tabula#480]
Let me say at the onset that this is not an issue in tabula. However I need to come up with a solution to process scanned PDFs and yes we tried Tesseract however for scans without tables it works pretty well but when it comes to scans with complex tables, it's way off the mark. We've spent enough time on it however & it did not help. 
Also my organization isn't ready to spend a whole lot of money on this however please advise whether there are free/opensource OCR tools (yes,Abbey Finereader Engine is too expensive) that do a good job or as good a job :) (with tables in scanned documents) as tabula does. Thanks again.

**Comment by jeremybmerrill** [comment]
tesseract is, I think, the open-source state of the art, so I'm disappointed to hear it didn't work for you. I've heard good things about OcraPy, so that may be worth looking into.
