### ISSUE TITLE
Tabula on academic transcript

### ISSUE THREAD

**Issue by ctstackh** [tabulapdf/tabula#482]
I tried auto and manual selection of fields on an academic transcript and was returned this output from two different windows machines running windows 10:

6XEMHFW &RXUVH /HYHO 7LWOH ,*UDGH ,&UHGLW +RXUV,"",4XDOLW\3RLQWV ,"",5
*%6 ,*5 ,%DVLF %LRFKHP 0HWDEROLVP ,$
*%6 ,*5 ,"%DVLF *HQHWLFV 0ROH %,R ",$
*%6 ,*5 ,",QWUR WR 1HXURELR ",$
*%6 ,*5 ,1HXURVFLHQFH +LVWRULFDO /LW -& ,$
*%6 ,*5 ,/DE 5RWDWLRQ ,$
"",$WWHPSW +RXUV 3DVVHG +RXUV,"",(DUQHG +RXUV,"",*3$+RXUV,4XDOLW\3RLQWV ,"",*3$
&XUUHQW 7HUP,"","","","","","","",""
&XPXODWLYH,"","","","","","","",""
7HUP 6SULQJ 7HUP,"","","","","","","","",""
0DMRU 1HXURVFLHQFH,"","","","","","","","",""
$FDGHPLF 6WDQGLQJ *RRG 6WDQGLQJ,"","","","","","","","",""
6XEMHFW &RXUVH /HYHO 7LWOH ,"","","",*UDGH &UHGLW +RXUV,"","",4XDOLW\3RLQWV ,"",5
*%6 *5 'HYHORSPHQWDO 1HXURVFL ,"","","",$,"","","","",""
*%6 *5 *UDG 1HXURVFLHQFH ,"","","",%,"","","","",""
*%6 *5 'LV RI 1HUY 6\V ,"","","",:,"","","","",""
*%6 *5 *UDG 1HXUR 'LVFXVVLRQ ,"","","",$,"","","","",""
*%6 *5 /DE 5RWDWLRQ ,"","","",$ ,"","","","",$
"",$WWHPSW +RXUV 3DVVHG +RXUV*3$ +RXUV 4XDOLW\,(DUQHG +RXUV,"",3RLQWV ,"","",*3$,"",""
&XUUHQW 7HUP,"","","","","","","","",""
&XPXODWLYH,"","","","","","","","",""
7HUP 6XPPHU 7HUP,"","","","","","",""
0DMRU 1HXURVFLHQFH,"","","","","","",""
$FDGHPLF 6WDQGLQJ *RRG 6WDQGLQJ,"","","","","","",""
6XEMHFW &RXUVH /HYHO 7LWOH ,"",*UDGH ,&UHGLW +RXUV,"",4XDOLW\3RLQWV ,"",5
*%6 *5 3ULQFLSOHV RI &HOO 1HXURVFL ,"",$,"","","","",""
*%6 *5 1HXUR 6WXGHQW 6XPPHU 6HPLQDUV ,"",:,"","","","",""
*%6 ,*5 ,/DE 5RWDWLRQ ,"","",:,"",""
*%6 ,*5 ,/DE 5RWDWLRQ ,"","",:,"",""
*%6 ,*5 ,1RQ GLVVHUWDWLRQ 5HVHDUFK ,"","",:,"",""
"","",$WWHPSW +RXUV 3DVVHG +RXUV*3$ +RXUV 4XDOLW\,(DUQHG +RXUV,"",3RLQWV ,"",*3$
&XUUHQW 7HUP,"","","","","","",""
&XPXODWLYH,"","","","","","",""
7HUP )DOO 7HUP,"","","","","","","","","",""
0DMRU 1HXURVFLHQFH,"","","","","","","","","",""
$FDGHPLF 6WDQGLQJ *RRG 6WDQGLQJ,"","","","","","","","","",""
6XEMHFW &RXUVH /HYHO 7LWOH ,"","","","",*UDGH ,&UHGLW +RXUV,"",4XDOLW\3RLQWV ,"",5
*%6 *5 /DE 5RWDWLRQ ,"","","","",$ ,"","","","",","
*%6 *5 1RQ GLVVHUWDWLRQ 5HVHDUFK ,"","","","",3,"","","","",""
"",$WWHPSW +RXUV 3DVVHG +RXUV,"",(DUQHG +RXUV,"",*3$+RXUV,4XDOLW\3RLQWV ,"",*3$,"",""
&XUUHQW 7HUP,"","","","","","","","","",""
&XPXODWLYH,"","","","","","","","","",""
"75$16&5,37 727$/6 *5$'8$7( 7RS","","","","",""
(YHQWV $GPLW *UDG,"","","","",""
6FKRRO,"","","","",""
/HYHO &RPPHQWV 1RUWK &DUROLQD 6WDWH 8QLYHUVLW\ %6,"","","","",""
$WWHPSW +RXUV 3DVVHG +RXUV ,"",+RXUV*3$ +RXUV 4XDOLW\(DUQHG ,3RLQWV ,"",*3$
"7RWDO ,QVWLWXWLRQ","","","","",""
7RWDO 7UDQVIHU,"","","","",""
2YHUDOO,"","","","",""
6XEMHFW,&RXUVH,/HYHO,7LWOH,&UHGLW +RXUV,""

I'm not sure if the issue is resolution of the pdf (it was a print screen).

I'm testing out tabula to see if it will work to extract information from police incident reports which are electronic forms in a lattice format. There are tables within tables, check boxes, and narrative text within approximately 200 fields. I have thousands of reports in this same format. Would tabula be able to save a template of the form and then align/apply it serially to multiple files of the same format? Can you suggest how to serially extract data from thousands of pdf's into csv tables?

My goal, once in csv, is to convert the files into RDF/XML using the Apache Any23 core distribution for linux. I'll then write RDFS and OWL documents linking all of the data and build a semantic database. Ultimately, I aim to construct a RESTful web interface that allows public access to these incident reports.

First though, I've got to get the data out of the fill forms. Any advice would be greatly appreciated!

Best,
Christian

**Comment by jeremybmerrill** [comment]
For the transcript, please try the Beta version we released last week. The extraction engine has been rewritten and will probably fix this problem. 

For the police reports, our templating workflow leaves a lot to be desired. Improving it is definitely on the wishlist, but it hasn't been done yet. What you CAN do is make a selection on one archetypal PDF and export it as a tabula-extractor script. You can then use the command-line app, tabula-java, to extract each of your 1000s of PDFs to CSV using that tabula-java script. 

Because the layout of these police reports is probably complicated, you may need to do some trial and error on the table layouts -- and I don't think we handle checkboxes at all.

Happy to help if you have more questions.

**Comment by ctstackh** [comment]
Jeremy,


I was actually just downloading the tabula-java jar. Thank you for your reply! I have a higher resolution pdf now and the extractor is working great! I just need to do some tweaking with the fields before exporting the script.


Perhaps, for the check boxes, if they are marked with an "X" then the extract can pull that out? I can find a way to work with that. Right now I'm just practicing on a blank report, but I hope to get my hands on some completed reports soon! I'll let you all know how it turns out.


Best,

Christian T. Stackhouse | Graduate Student
GBS Neuroscience Theme
Department of Neurosurgery
Department of Radiation Oncology
UAB | The University of Alabama at Birmingham
Hazelrig-Salter Radiation Oncology Center | 1700 6th Ave S | Birmingham, AL 35233
M: 919.724.6890 | ctstackh@uab.edu | cstackhouse@uabmc.edu | ctstackh@gmail.com

uab.edu<http://uab.edu/>
Knowledge that will change your world



________________________________

**Comment by jeremybmerrill** [comment]
Hi Christian,

I'm honestly not sure about the checkboxes; Tabula focuses on reconstructing tabular data from PDFs, so we haven't put in much effort towards extracting non-tabular data. I suspect they won't work, but I suppose you can give it a shot and see. (And let us know if they do.)

**Comment by jeremybmerrill** [comment]
@ctstackh Let us know what you find with the checkboxes. Feel free to reopen if there are more issues.
