### ISSUE TITLE
Change output of "script" download to use tabula-java

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#484]

**Comment by jeremybmerrill** [comment]
I can probably pick this up tonight. Thoughts on just having the path to
the jar be `tabula-java.jar` and rely on users to manually rename it?

Jeremy B. Merrill

**Comment by jazzido** [comment]
Sure. If they're using that option, it's reasonable to expect that they can change a path.

**Comment by mtigas** [comment]
OK. Yeah, I think it’s probably best to release the first beta as-is; I'll just write a note into the release notes about this.

For users advanced enough to use that script, it shouldn’t be a big issue anyway as long as we flag it for them.

**Comment by jeremybmerrill** [comment]
👍

Jeremy B. Merrill
