### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by werdlv** [tabulapdf/tabula#489]
Is there a way to export tabular data automatically via command line instead of manual upload => detect => export?
Something like `tabula input.pdf -o data.csv`

**Comment by jeremybmerrill** [comment]
Yes, with [tabula-java](https://github.com/tabulapdf/tabula-java/), which is the command-line version of Tabula's extraction engine. There are docs in tabula-java's README, but feel free to ask if you have more questions.

**Comment by werdlv** [comment]
@jeremybmerrill thanks! ;)
