### ISSUE TITLE
running tabula behind an SSL port  

### ISSUE THREAD

**Issue by pdemilly** [tabulapdf/tabula#491]
I am trying to protect my tabula using at least SSL. However I am encountering some issues. Since I am running nginx I was able to rewrite most of the links but at some point it does an outside call to

Mixed Content: The page at 'https://xxxxxx/#//pdf-extractor' was loaded over HTTPS, but requested an insecure script http://tabula.jeremybmerrill.com/tabula/notifications.jsonp?callback=notifications&_=1460412668038 This request has been blocked; the content must be served over HTTPS

What the reason for this and how can I prevent it?

**Comment by jeremybmerrill** [comment]
That JSONP endpoint is a list of Tabula versions and an opportunity for the Tabula developers to put a small message on the Tabula start page (if we wanted to run a user survey or something like that). We also count hits to that endpoint as a rough measure of usage.

I'll try to make it accessible over HTTPS, but that won't happen immediately.

You can turn it off for each browser using Tabula by running `localStorage.setItem("tabula-notifications", false)` in the JavaScript console -- and for new browsers, turning off the notifications in the popup modal.

Alternatively you could remove the [Tabula.getNotificatoins function](https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/tabula.js#L91) or replace it with a no-op.

I'm curious why you're putting Tabula behind SSL. Are you planning on exposing it to the open web?

**Comment by pdemilly** [comment]
I am integrating tabula inside my app in an iframe right now. Since the app is running over ssl, the browser rejects any attempt to access outside resources over http. The app is for non-profits in affordable housing market and tabula is used to extract data from those reports. You need valid credentials to use that app.

**Comment by pdemilly** [comment]
I was able to make it work using a reverse ssl proxy. Thx
