### ISSUE TITLE
incorrect extraction of column with Autodetection of table

### ISSUE THREAD

**Issue by jahagirdar** [tabulapdf/tabula#498]
Using autodetect table on the tables at http://bbmp.gov.in/trade-license e.g. http://bbmp.gov.in/documents/10180/1153943/Trade_Category_NEW_Fees+%2823-02-2016%29.pdf/4cca8b5c-52fa-4d15-aee6-f14209b3c60b
results in extraction of all columns but the last.

Manual selection of tables works fine.

**Comment by jeremybmerrill** [comment]
It worked for me... But it sounds like this is the same problem as tabulapdf/tabula-extractor#99 and #493, etc.
