### ISSUE TITLE
Tabula-Java pdf extractin documentation

### ISSUE THREAD

**Issue by ravibiradar** [tabulapdf/tabula#499]
Hi,
where can i find the documentation for pdf extraction using java. in the path Tabula-java/src/main/java/technology/tabula/  I got only code for java. through that code i can get the content from pdf directly on the console, I am not able to get it int String variable or even i don't know how to store that data into text file.
please help me

**Comment by melisabok** [comment]
Hi!

Using the option '-o' you can specify a file name where to store the data and using '-f' you can specify the format: JSON or CSV. Here an example:

```java -jar ./tabula-java.jar -p2 -fJSON -oout.json April-2016-National-List-v5.pdf```

more info about the parameters: 

```java -jar ./tabula-java.jar --help```

**Comment by ravibiradar** [comment]
Thank you so much melisa
