### ISSUE TITLE
Tabula has some strange spaces that get added in middle of words..

### ISSUE THREAD

**Issue by prabhathn** [tabulapdf/tabula#502]
I have a PDF file that is really clean and straightforward looking.. Tabula does well here on both Stream and Lattice, however, it keeps inserting spaces between sentences.. Wondering if there are settings that I can tweak to get a better out put

Link to the PDF I'm trying to scrape.
[https://www.publix.com/-/media/documents/wellness/the-right-foods-for-you/four-grams-of-sugar.ashx?la=en](url)

**Comment by jazzido** [comment]
Hi @prabhathn,

PDF is essentially a vector graphics format, and it does not encode the notion of a 'word'. For that reason, the word segmentation that Tabula does is based in heuristics that measure distance between characters. 

At the moment, however, the distance thresholds that we use for segmenting words can't be tweaked.
