### ISSUE TITLE
Unable to Generate New Jar File

### ISSUE THREAD

**Issue by maphysics** [tabulapdf/tabula#510]
I'm unable generate a new jar file.  It could be my newly set up ruby environment as I'm coming back to Ruby from Java after a number of years or it could be an issue with warbler and rake linked below.  

I'm regenerating the jar file to test changes.  I need to make a change to the config.ru so that lines 18-20 look like this

  port = java.lang.Integer.getInteger('warbler.port', 8080)
  host = java.lang.String.toString('warbler.host', 'http://127.0.0.1')
  url = "#{host}:#{port}"

The host address can then be passed in from the command line. I want my tabular to be accessible from the web while running on my centos server.   I've made the change locally to my checkout.  Attempts to generate the new jar result in errors from rake seemingly relating to 

https://github.com/jruby/warbler/issues/366

So my question is in the gemfile the warbler version is set to 1.4.9 and the rake version is unset.  Which versions is recommended to solve the issue referenced above?

Thanks!

**Comment by jeremybmerrill** [comment]
Oof. Warbler can be a real pain sometimes... @mtigas is our build maven (ha! sorry) and he may have an idea...

**Comment by massimosala** [comment]
@maphysics I extract tabula.jar with unzip, make my changes, and then update with

`zip.exe -u -r tabula.jar tabula\META-INF\MANIFEST.MF tabula\*`

fo linux, change from zip.exe to zip

**Comment by mtigas** [comment]
I bet this had to do with the Java or JRuby version @maphysics was running; the previous warbler & rubyzip were not compatible with the JRuby 9 series. Got a similar error when I'd upgraded JRuby but did not update the gems.

Should be fixed in 7875582becb2799b65586d5680782cafd399bb33
