### ISSUE TITLE
Tabula Export Problem

### ISSUE THREAD

**Issue by diaholliday** [tabulapdf/tabula#512]
I have 50 PDFs in the same format but I can't seem to get one of them formatted correctly. The Tabula auto-highlight function works well for the actual data field, it even seems to upload fine—but the CSV that I download always comes out with jumbled letters in certain fields (the jumbled letters don't seem to correspond to anything in particular). 

I'm hoping there's a fix and that it can be duplicated for each of the 50+ PDFs I hope to convert.

**Comment by jeremybmerrill** [comment]
Can you share with us one of these PDFs?

**Comment by jeremybmerrill** [comment]
Which PDF(s) in particular have this error? Is it all of the PDFs there?

And can you give me an example of a CSV with "jumbled letters"?

And, when the letters are jumbled in the CSV, are they also jumbled in the data preview in the Tabula app?

I tried the Addams table and everything seemed to work fine.

**Comment by jeremybmerrill** [comment]
@diaholliday: feel free to reopen the issue to answer the questions above, if you'd still like help.
