### ISSUE TITLE
Workaround for tabula 1.1.0-beta.1 calling tabula-java 0.9.0: where is the script to modify?

### ISSUE THREAD

**Issue by samoura-remy** [tabulapdf/tabula#516]
I would like to follow the workaround explained in the page [https://github.com/tabulapdf/tabula/releases/tag/v1.1.0-beta.1 (see extract below at end)](https://github.com/tabulapdf/tabula/releases/tag/v1.1.0-beta.1).
I saw the instructions of tabula-0.9.0-jar-with-dependencies.jar, can compile from source with Eclipse on Windows an run it with any of the options. I would like to use the web interface and "_replace the tabula command with java -jar tabula-0.9.0-jar-with-dependencies.jar in the generated script._" but where is that "generated script" (containing the old command) or where is the code that generates the script containing the old command?

I tried to find that in the sources without success. Is it a ruby file, a java file, a parameter file? If necessary I can modify some code, but I did not see where to make the modification.

Can you help me? Or can you point me to the answer if already explained somewhere else.

Thanks a lot.

"_Bug: Although the backend for the Tabula app has been rewritten using tabula-java instead of tabula-extractor, the "script" export option still generates commands to call the older tabula-extractor. To fix this, you may follow the download and example instructions for tabula-java, and replace the tabula command with java -jar tabula-0.9.0-jar-with-dependencies.jar in the generated script. (#484)_"

**Comment by jeremybmerrill** [comment]
If you start the GUI, upload a PDF, then make a selection, you'll be taken to a page that has a preview of your data and a series of download options: CSV, JSON, TSV, as well as "Script"

The "Script" option generates a shell script that calls the Tabula binary and allows a repeatable, browser-less extraction. It's this generated shell script to which that workaround line refers: we recommend users download the script and make the change in the downloaded script.

That script is generated https://github.com/tabulapdf/tabula/blob/master/webapp/tabula_web.rb#L290-L304; the next release of Tabula -- or if you were to compile from the branch -- will incorporate a reference to the Tabula jar.
