### ISSUE TITLE
Auto detect tables command line

### ISSUE THREAD

**Issue by chrispmlee** [tabulapdf/tabula#517]
Hi,

I was wondering if there was a way to use the command line tool to auto-detect tables in a certain area. Currently the area extraction commandline option extract all text in a certain region rather than just a specific table. 

Best,
Chris

**Comment by jeremybmerrill** [comment]
Hi @chrispmlee: Yes, sort of. The `-g` option will autodetect tables (via the same mechanism as the GUI) on the given page or pages. 

There's no built-in way to restrict the autodetected tables to a particular area on a page though.

**Comment by jeremybmerrill** [comment]
And the documentation for the command-line tool is here: https://github.com/tabulapdf/tabula-java/

**Comment by chrispmlee** [comment]
Thank you for your response!

**Comment by tanyaroosta** [comment]
Hi,
I am running into a similar issue and looking at the documentation isn't helping. When I try the -g option it does not seem to work.  I have a number of pdf files and am trying to automate the table extraction using the command line.  I don't know ahead of time if/which page has a table, so I am assuming I should use the -g option based on the above discussion.  
Any help is greatly appreciated.

**Comment by laigor** [comment]
It looks like tabula-1.0.2-jar-with-dependencies ignores the -d and -r keys. Automatic detection of tables is a very necessary function for tabula-java and I want to sponsor its refinement. How can I do it?
