### ISSUE TITLE
Table columns

### ISSUE THREAD

**Issue by amanmaru** [tabulapdf/tabula#518]
Table columns from the pdf are not copying correctly. How can I copy data from the pdf to excel in the exact format? I believe the issue is coming from the some of the headers spanning multiple columns.

**Comment by jeremybmerrill** [comment]
You're exactly right about the problem. The best way to fix it will be to exclude the headers from your selection.

**Comment by amanmaru** [comment]
I found another issue after removing the columns. When copying the data and selecting repeat, so that all tables are selected. I found that after every page, the data does not copy correctly. Some values are missing or aren’t in the right columns. Any suggestions?
Aman Maru
Data Curator
The E.W. Scripps Company
312 Walnut Street, Suite 2800 | Cincinnati, OH 45202
Desk:513.898.4045 | Cell:513.328.3395
Aman.Maru@Scripps.com<mailto:Joseph.Schultz@Scripps.com>

“Give light and the people will find their own way.”

**Comment by amanmaru** [comment]
I found another issue after removing the columns. When copying the data and selecting repeat, so that all tables are selected. I found that after every page, the data does not copy correctly. Some values are missing or aren’t in the right columns. Any suggestions?
