### ISSUE TITLE
A difficult PDF example

### ISSUE THREAD

**Issue by posixpoet** [tabulapdf/tabula#523]
Dear Tabula masters
I am very fond of Tabule - thank you so much!
This PDF however seems to be very difficult for Tabula:
https://crdev.blob.core.windows.net/files/13678.pdf

Mind checking it out? 

TIA
Georges

**Comment by jeremybmerrill** [comment]
Hi Georges,

Yes, I see. I don't have a suggestion for you, unfortunately, the PDF is incredibly pathological; it almost seems constructed to confuse Tabula. The problems are: the lack of ruling lines between cells and the text from one cell overflowing "behind" the next cell.

If you use "Stream" extraction mode (the button is on the left of the Data Export page) and exclude the headers from your selection, then you'll get okay results. Some of the cells containing times are combined, but you could use Microsoft Excel (or LibreOffice Calc)'s Text-to-Column feature to separate them.
