### ISSUE TITLE
Mapping multiple lines into one cell

### ISSUE THREAD

**Issue by smwitkowski** [tabulapdf/tabula#526]
I have a table in a PDF that has multiple lines of text written in one row. Tabula is putting each line in a new row. 
[Delegate_Anderton.pdf](https://github.com/tabulapdf/tabula/files/367350/Delegate_Anderton.pdf)

**Comment by jeremybmerrill** [comment]
Use the Lattice extraction method. (Button is located to the left.) This method will work only if there are lines separating each cell in your document.
