### ISSUE TITLE
Extracting lists from PDF

### ISSUE THREAD

**Issue by luykx7** [tabulapdf/tabula#527]
Was trying to extract lists from this PDF to Excel. Where the output is that all text within each member of the list, is put into one cell. 
The standard output from tabula is that each line in the document is put into a new cell/row, regardless of whether it's actually a new bullet or not.
And list-signs like bullets need to be dropped.

[28Soncos_norm-rapp2016_vdef.pdf](https://github.com/tabulapdf/tabula/files/373941/28Soncos_norm-rapp2016_vdef.pdf)

**Comment by jazzido** [comment]
Hi @luykx7,

Thanks for your suggestion. Tabula can't accommodate every possible text extraction case. At the moment, we focus on detecting, segmenting and extracting table-like structures.
