### ISSUE TITLE
Does tabula reveal underlying data or just what is presented in the PDF? 

### ISSUE THREAD

**Issue by BMcclain** [tabulapdf/tabula#532]
I was hoping to see the underlying data that generated the graphic. What I saw in the attached PDF was the outline of the graphic with totals revealed. Nothing I couldn't observe from looking at the graphic.
[{b7161c8c-788e-4a01-85be-c303e7f74d72}_E4P0716_PatientCentricProfitability_WP_V9.pdf](https://github.com/tabulapdf/tabula/files/402344/b7161c8c-788e-4a01-85be-c303e7f74d72._E4P0716_PatientCentricProfitability_WP_V9.pdf)

The graphic #1 

Thanks. I am new to the whole process...

Bonny

**Comment by jeremybmerrill** [comment]
Hi @BMcclain,

You're correct that Tabula only deals with data that's immediately visible in the PDF; Tabula cannot digitally process or interpret a chart/graphic and restore the underlying data. I assume you're talking about one of the bar charts in the PDF you attached.

What Tabula can do is take a data table (words and numbers on the page, arranged to look like a table -- PDFs don't understand spreadsheets) and transform it into a real spreadsheet that programs like Excel can handle.

I'd certainly be interested in something that could process charts in the way it seems you're looking for, but I'm not sure something like that exists, unfortunately. If you find a solution, please do let me know.

**Comment by BMcclain** [comment]
Is that what import.io <http://import.io/> does with urls? They are just fabulously expensive. Thanks for clarifying and your quick reply.

Bonny


"Statistics are like swimwear - what they reveal is suggestive but what they conceal is vital." 
-Ashish Mahajan, Lancet 2007

bonny p mcclain
medical writer | speaker | insight analyst

http://www.amazon.com/Bonny-McClain/e/B00J0M10OY
http://www.dataanddonuts.org
http://www.alzheimersdiseasethebrand.com

**Comment by jazzido** [comment]
> I'd certainly be interested in something that could process charts in the way it seems you're looking for, but I'm not sure something like that exists, unfortunately. If you find a solution, please do let me know.

@jeremybmerrill, IIRC, the [Content Mine](http://contentmine.org) was working on that problem.

**Comment by jeremybmerrill** [comment]
@BMcclain: I'm not super familiar with import.io, but I think they likewise work with numbers/words that are on the page -- transforming the HTML webpage into a real spreadsheet. Besides the (very ambitious) Content Mine project that @jazzido, I don't know of anyone trying to systematically transform charts/graphics _back into_ data.
