### ISSUE TITLE
Windows, requirements : user into Administrators or directory writeable ?

### ISSUE THREAD

**Issue by massimosala** [tabulapdf/tabula#533]
Trying on two pc : Windows 7 SP 1 and Windows XP SP3.
Java 1.7_u80

Tabula starts. I open the webpage and I get
INTERNAL SERVER ERROR 500 : "Could not load FFI provider."

The Windows logged user account  isn't into Administrators group.
If I run Tabula under Administrator, no error.

Our corporate policies disagree with this.
How can I check if it is a problem of directories and permissions ?
Is it possible to get a verbose log, tracing file system issues ?

Best regards, Sala

**Comment by massimosala** [comment]
From tabula messages, I see there variables : DATA_DIR, DOCUMENTS_BASEPATH, ENABLE_DEBUG_METHODS. How can I set them before to launch tabula ?
Best regards, Sala

**Comment by jeremybmerrill** [comment]
If you're launching Tabula from a batch script (as you mention in the other issue), you should be able to set those environmental variables. I'm not sure exactly how you do it (I'm not much of a Windows user), but it might be like this.

```
DATA DIR c://Documents And Settings/MyUsername/My Documents;
```

Let me know how it goes. You should be able to find instructions online for setting environment variables in Windows.

**Comment by massimosala** [comment]
Hi Jeremy
I done a search on this web site, and I found the hint 

`java -Dtabula.data_dir=...  tabula.jar
`

grazie, Massimo
