### ISSUE TITLE
Is it possible to disable tabula launching the browser ?

### ISSUE THREAD

**Issue by massimosala** [tabulapdf/tabula#534]
environment : Windows

We have Internet Explorer as default, but we want to start tabula with firefox.

So our batch starts tabula and launches firefox.

Is it possible to disable tabula launching the browser ?
best regards, Sama

**Comment by jeremybmerrill** [comment]
Currently, there's not. We should add that (but it won't be immediate).

**Comment by jeremybmerrill** [comment]
Maybe your batch script can temporarily change the default browser to Firefox, then change it back to IE once Tabula is launched?

**Comment by massimosala** [comment]
We are a non profit organization, with low budget and very old clients.
Some of them have mono-core cpu, 10 years old, and tabula takes too much to start.

So I am thinking to deploy tabula on a server, not on the clients.

What do you think ? Is it a correct path ?

best regards, Sala

**Comment by jeremybmerrill** [comment]
That would work. I've done it at my office as well.

Jeremy B. Merrill

**Comment by massimosala** [comment]
Hi Jeremy

Could you please give me some hints about running tabula as a Windows service ?

thks, Sala

**Comment by jeremybmerrill** [comment]
Hi Sala,

I don't know anything about Windows services. I've set up Tabula to run as a Docker service, but that's in Linux: https://github.com/newsdev/tabula/blob/master/Dockerfile

**Comment by massimosala** [comment]
Jeremy, thanks for your suggestion. I open another thread specific to "run as a service".

**Comment by massimosala** [comment]
I found the solution reading the source code, into the file tabula/WEB-INF/config.ru

To decide about launching the browser, the code checks if there is a desktop.
Running java 1.7 headless, no desktop, no browser

java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Djava.awt.headless=true -jar tabula.jar

**Comment by jeremybmerrill** [comment]
Oh, I didn't even know you could do that. Nice find!

**Comment by massimosala** [comment]
Hi Jeremy

I want to contribute, not only ask ;-)!


Issue #541 Running as a service under linux and windows
<https://github.com/tabulapdf/tabula/issues/541>

I have  a simple idea about how to handle many different users' workspaces
"My files".

I write programs, but not in ruby, so alone I cannot update Tabula' source
code.

Can you please put me in contact with the developers ?
I think with 10 minutes and a couple of Emails, we can update the code, and
try my improvement.

thks, Massimo
