### ISSUE TITLE
Nested columns merged into one

### ISSUE THREAD

**Issue by yonnig** [tabulapdf/tabula#540]
The "Create" and "Update" sub-columns of the first table (7.4.7.1-2) of the file attached are wrongly 
merged within a single column.
[TS-0004.pdf](https://github.com/tabulapdf/tabula/files/424913/TS-0004.pdf)

**Comment by jeremybmerrill** [comment]
Exclude the headers. (The "Request Optionality" header spans the two columns, so Tabula interprets this as a single column.)

**Comment by yonnig** [comment]
So I guess it's a limitation of Tabula. The attached document is an excerpt of a bigger document (> 200 pages). I was hoping to have an automated process.
By the way, pdftables (https://pdftables.com/) did the trick well on this exerpt; this is not a free nor open-source software however (just tried it on-line).
Thanks a lot for all the job done on Tabula.

**Comment by jeremybmerrill** [comment]
The "Lattice" extraction mode (which is automateable) OUGHT to have worked on this table, but, oddly, it didn't. 

The "Stream" mode (which Tabula used by default here) uses only text on the page to determine the table structure -- so that's why the column header spanning the two columns caused a problem.

Lattice mode uses the ruling lines to recreate the table structure -- but these must be a little weird or something.

**Comment by yonnig** [comment]
Yes I indeed tried with the "Lattice" mode as well, and the result was worse.
I didn't catch the meaning of "ruling lines" initially, so thanks for the explanation.
Would by any chance someone have a look at that "weird" stuff ?

**Comment by jeremybmerrill** [comment]
Will we take a look? Yes, eventually... :) I've got a huge backlog and no working dev environment right now, so, you know, eventually.

My guess is that there may be something legitimately strange about the ruling lines. Maybe the vertical one goes past the horizontal one by a pixel or two? The lattice mode *ought* to work on this kind of table and the feature is pretty mature, so if it's not working, there's something pretty weird going on.

**Comment by jazzido** [comment]
Just ran the PDF through `tabula-java`'s debug tool:

![ts-0004-1](https://cloud.githubusercontent.com/assets/27584/17788910/cc8b0b24-655d-11e6-82b1-d63c9f841de1.jpg)

My bet is that those "invisible" lines around the table headers are confusing the Lattice extractor.
