### ISSUE TITLE
Tabula API

### ISSUE THREAD

**Issue by asbjornenge** [tabulapdf/tabula#542]
Hi there!

We have been trying to use `tabula` as an "API" form another web service. It works quite well and we can upload and extract data. But it seems to solely rely on the use of `coords` pr. page. Is there a way to use the `/data` endpoint with other type of parameters like `--no-spreadsheet --columns 32,168,220.3,250,355,474,668,735 --pages all` etc. similar to what you would pass to the command line? Or is there some other endpoint we might use?

I also found [tabula-api](https://github.com/tabulapdf/tabula-api) - what is the status of that project? Seems abandoned. Do you know of another tabula api out there we could take a look at?

Thanks,
Asbjørn

**Comment by jeremybmerrill** [comment]
Hi @asbjornenge:

You cannot specify columns via the internal API used by the Tabula web app.

You can, however, specify the extraction method. The `coords` can contain an `extraction_method` key. The values can be `"original"`, `"spreadsheet"` (or `"guess"`, but that's the same as not including the key).

tabula-api isn't abandoned, per se, but we haven't worked on it in a while. We'd love to pick it back up, but... we're all super busy.

**Comment by asbjornenge** [comment]
@jeremybmerrill Ok, thanks a bunch :grin: I'll give the other `extraction_method` values a try. Hope you find some time to work on `tabula-api`, seems like something many would want and need. I can sympathize with the being busy part :stuck_out_tongue_closed_eyes: :+1:

**Comment by jeremybmerrill** [comment]
Happy to help if you run into trouble.
