### ISSUE TITLE
I use different charactors which er letters of Norwegian language

### ISSUE THREAD

**Issue by mesealemu** [tabulapdf/tabula#543]
I used a pdf document having different charactors which er letters of Norwegian language. I cant able to find the expected result from extracting my pdf file. There comes all capital letters with strange and un understandable words in tables as a result.

**Comment by jeremybmerrill** [comment]
Can you please send us the PDF?

**Comment by jeremybmerrill** [comment]
@mesealemu We're happy to help, but we need the PDF. Please reopen the issue if you're able to send us the PDF.
