### ISSUE TITLE
after some collumns Stream mode starts to combine collumns

### ISSUE THREAD

**Issue by yannick9906** [tabulapdf/tabula#544]
Stream Mode:
![image](https://cloud.githubusercontent.com/assets/8795691/18315383/171150d6-7517-11e6-93d5-29cd7d702cac.png)
Lattice Mode:
![image](https://cloud.githubusercontent.com/assets/8795691/18315473/6bf306f8-7517-11e6-8e43-b073b48de651.png)

Original
![image](https://cloud.githubusercontent.com/assets/8795691/18315392/27fc40e0-7517-11e6-8477-5827c53134a3.png)

Streammode does everything else correctly.

[PDF-File](http://www.mvg-mainz.de/fileadmin/user_upload/Downloads/Linienfahrplan_aktuell/TFP_68_1.PDF)

**Comment by jeremybmerrill** [comment]
Those columns are probably too close together. There's not a really easy way to fix this in Tabula, but Excel's Text to Columns feature might help, by splitting on spaces.
