### ISSUE TITLE
TABULA CSV EXTRACTION

### ISSUE THREAD

**Issue by sidmohan** [tabulapdf/tabula#545]
[http://www.kemet.com/Lists/ProductCatalog/Attachments/254/KEM_T2005_T491.pdf](url)

i am facing some issues in tabula ,when extracting table from url above-

1. i am doing in stream mode only but if i don't select the Column header its an issue for me as i need to run a script that will extract the column data based on the Column header name. Is there any way out on this?

2. Also i am getting blank columns also in between in the final .CSV, although the original table doesn't have those - how to get rid of those

**Comment by jeremybmerrill** [comment]
Hi @sidmohan

Thanks for opening this issue on Github. 

There's not really a way to fix either of those issues. In Stream mode, in PDFs that, like yours, have headers that span across data rows, you have to exclude the headers. One possible solution is to make two selections: one for the data and one for the headers, and join them in your script.

For the second issue, if you're using Stream mode, there shouldn't be any empty columns. If you're using lattice mode, there isn't a way to avoid the empty columns (there are probably two lines in the PDF that touch each other). You can remove them in your final script as well.

**Comment by sidmohan** [comment]
thanks, request you to please provide solution for getting the multiplication symbol correctly from the PDF. In the preview mode the symbol appears correctly in size column of PDF but when exported it gets distorted to a hypen and strange character 

IN PREVIEW MODE -
![image](https://cloud.githubusercontent.com/assets/22184015/18608061/20922e22-7cfc-11e6-9ea8-fcb7f11541b6.png)

AFTER DOWNLOADING-

![image](https://cloud.githubusercontent.com/assets/22184015/18608066/3b8b43c6-7cfc-11e6-8886-de9e10fafbff.png)

**Comment by jeremybmerrill** [comment]
That's a problem in Excel, not with Tabula. Instructions like these will help you open the CSV in Excel with the right encoding: http://superuser.com/questions/280603/how-to-set-character-encoding-when-opening-excel

**Comment by sidmohan** [comment]
Hi thanks for the reply, may i know what is the backend coding platform for tabula? i need to perform some kind of automation so that it can automatically fetch a PDF from a website and convert it into an excel. Your inputs will be highly valuable

**Comment by jazzido** [comment]
Tabula, as you can see from its source code, it's written in JRuby. The extraction algorithms are implemented in Java: [`tabula-java`](http://github.com/tabulapdf/tabula-java)

**Comment by sidmohan** [comment]
hi all, can anyone let me know how to encode the Auto detect feature of tabula into python script. i basically want to run python script to pull out all the tables from a given PDF? i am not familiar with JRUBY and hints will be great help

**Comment by sidmohan** [comment]
Hi , can you suggest some hints on automating extraction of multiple tables from a PDF (like http://datasheets.avx.com/TAJ.pdf )
