### ISSUE TITLE
Internal Server Error (500) Comparison method violates its general contract

### ISSUE THREAD

**Issue by craigdsouza** [tabulapdf/tabula#546]
Hey, can anyone help with this error?
The link to the pdf is here 
http://cbrienvis.nic.in/Thermal%20Power%20Station%20in%20India%202016.pdf

and the error I got is below.
Tabula API version: 1.1.0.160330
Filename: Thermal Power Station in India 2016.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/32cde132930f09e09e552c8074d8b7654ef8f09f/data

Comparison method violates its general contract!

My system is a Windows 7, 64 bit, Browser Google Chrome. Let me know if any other details are required.

**Comment by jeremybmerrill** [comment]
This will be fixed by https://github.com/tabulapdf/tabula-java/issues/81, which will be included in the next release of tabula, which will be very very very soon, hopefully.
