### ISSUE TITLE
Tabula extracted the header as part of the table, and missed the second line.

### ISSUE THREAD

**Issue by bumblebritches57** [tabulapdf/tabula#550]
I disabled the first table, I'm talking about the second one on the first page.

It completely ignored the N table, in Lattice mode. and the formatting in stream mode is basically unusable

Here's my file, it's from the H.264 whitepaper. [Table.pdf](https://github.com/tabulapdf/tabula/files/491161/Table.pdf)

**Comment by jazzido** [comment]
Hi @bumblebritches57,

The tables with spanning cells/headers are sort of an edge case for Tabula: it works best with *flat* tables. Nevertheless, I think the output for the table you mention is usable after a bit of cleaning.

Selection:

![screen shot 2016-09-24 at 2 00 47 pm](https://cloud.githubusercontent.com/assets/27584/18810247/54a117c4-825f-11e6-8c9b-170ce4be8ab7.png)

Result:

![screen shot 2016-09-24 at 1 51 04 pm](https://cloud.githubusercontent.com/assets/27584/18810249/603844cc-825f-11e6-9e2b-415f812870c8.png)

**Comment by bumblebritches57** [comment]
Yeah, I'm trying to clean the html right now actually, The biggest inconvenience currently is having to navigate through a gajillion <span> tags instead of a few <table> ones.
