### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by rjp0i** [tabulapdf/tabula#554]
Error message below, with PDF file attached

Tabula API version: 1.1.0.16092117
Filename: Textbooks.pdf
Internal Server Error (500)

```
    Request Method:
    POST


    Request URL:
    http://127.0.0.1:8080/pdf/ac409c5c09cc25afbfbbd6b087240bc379789d4a/data
```

[Textbooks.pdf](https://github.com/tabulapdf/tabula/files/499374/Textbooks.pdf)

**Comment by jeremybmerrill** [comment]
I gather from #555 that you were able to get the PDF imported into Tabula properly. If you had to do anything to the PDF to make it work, please reopen this issue.
