### ISSUE TITLE
Newlines break CSV export

### ISSUE THREAD

**Issue by sstangl** [tabulapdf/tabula#557]
Using the "Lattice" mode, grid cells appear correctly in the preview table. However, if some of those cells contain newlines, for example "Deadlift\n1", the CSV export will produce:

> ,Deadlift
> 1,

which is not a useful CSV file and requires manual correction.

Example file: http://www.upapower.com/development/wp-content/uploads/2016/02/resultsfor01232016AZpp.pdf

**Comment by jeremybmerrill** [comment]
When I tried to replicate this, the resulting CSV was properly formatted. Individual cells do contain newlines, but the cells are properly quoted and Excel was able to display the document correctly.

@sstangl: If the cells were NOT quoted in your output, could you send me the CSV output?
