### ISSUE TITLE
Tabula 1.1.0 Release (1.1.0.16092117) crashes 

### ISSUE THREAD

**Issue by Kristofp** [tabulapdf/tabula#563]
Tabula 1.1.0 Release (1.1.0.16092117) crashes when extracting data on iOS 10.12, MacBook Pro (Retina, Mid 2012)

**Comment by jeremybmerrill** [comment]
When did the crash occur? Were you able to see the Import PDF page? Were you able to select a table on the PDF?

Did you get an error message?

**Comment by Kristofp** [comment]
sorry I can’t remember the problem it’s too long ago.  As far as I could remember I couldn’t even import it.  I had to download the old version to continue.  I no longer have the file at hand so I can’t reproduce it to see the error message.



On 19 Nov 2016, at 22:18, Jeremy B. Merrill <notifications@github.com> wrote:

When did the crash occur? Were you able to see the Import PDF page? Were you able to select a table on the PDF?

Did you get an error message?
