### ISSUE TITLE
Wrong eol encoding on UNIX ('\r')

### ISSUE THREAD

**Issue by malaterre** [tabulapdf/tabula#570]
For some reason tabula is using '\r' to encode an end of line. So one could get something like this in the json encoded output:

`"text" : "The value is same as Diffusion b-value\rof MR Diffusion Macro",
`
However `'\r'` has a funky behavior on UNIX since it will return at the begining of the line. Therefore the equivalent CSV output will be:

`of MR Diffusion Macro,xx30) FD The value is same as Diffusion b-value
`

I would suggest you make sure to use `'\r\n'` to encode an end of line, otherwise the CSV output is pretty much useless on UNIX.

**Comment by jeremybmerrill** [comment]
Can you give us more details of the system you're using and the PDF you were trying to extract? Tabula uses the [Apache Commons CSVWriter's Excel CSV format](http://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html#EXCEL) so I'm surprised you're getting an invalid CSV. It's possible there's a bug with that Apache library's format or a weird interaction between your locale and the CSV format.

**Comment by malaterre** [comment]
@jeremybmerrill I am not saying that the library is good or bad, I am just saying that the CSV format is hard to deal with (I am sure there are plenty of example on the web). You cannot pass `'\t'` in a CSV file where tab is used as separator. Same reason you cannot pass `'"'` when quote are used to with multiline fields...

**Comment by malaterre** [comment]
Maybe I can redo my bug report with the original example and let you do the conclusion instead.

So steps are:

```
$ wget http://www.hitachimed.com/idc/groups/hitachimedical/documents/supportingdocumentpdf/poc_013216.pdf
$ java -jar tabula-0.9.1-jar-with-dependencies.jar -o foo.csv -p 59 hitachi/poc_013216.pdf
$ grep xx31 foo.csv 
Functional Groups Module"frame,"(0029,xx31)",SQ,"The value is same as Shared Functional

```

Thanks for this great tools, JSON output works just fine for me.

**Comment by jeremybmerrill** [comment]
Ah, I see. I think I'm familiar with what this issue might be... Can you reopen this bug in https://github.com/tabulapdf/tabula-java/ ? That's the issue tracker for the command-line tool. 

We'll take a look at the bug when we get a chance; thanks for the report.
