### ISSUE TITLE
Tabula automation

### ISSUE THREAD

**Issue by sidmohan** [tabulapdf/tabula#574]
may i know what is the backend coding platform for tabula? i need to perform some kind of automation so that it can automatically fetch a PDF from a website and convert it into an excel. Your inputs will be highly valuable

**Comment by jazzido** [comment]
Replied in #545

**Comment by sidmohan** [comment]
thanks a lot for the quick reply, can you please provide some insights into how can i perform the automation such that tabula can automatically fetch a PDF from a website and convert it into an excel. I am not aware of Ruby , have worked on Python - so is there any work around?

**Comment by sidmohan** [comment]
can someone please provide some insights into how can i perform the automation such that tabula can automatically fetch a PDF from a website and convert it into an excel. I am not aware of Ruby , have worked on Python - so is there any work around?

**Comment by jeremybmerrill** [comment]
You can fetch the PDF with any language that you want. You can automate Tabula with [tabula-java](https://github.com/tabulapdf/tabula-java/), which provides a command-line interface to Tabula. You should be able to call the command-line interface from Python -- or any language that you want. tabula-java's documentation should give you sufficient guidance to extract the table.
