### ISSUE TITLE
Wrapped Text in PDF 

### ISSUE THREAD

**Issue by anitabev** [tabulapdf/tabula#580]
Wrapped Text in PDF shows up in the row below when it's extracted. Is there a work around?

**Comment by jeremybmerrill** [comment]
You can try the Lattice mode -- that will work if your table has lines separating each cell. Otherwise, there is no workaround: Tabula extracts the data as it is contained in the PDF, and we haven't found a way to reliably determine what is wrapped text and what is a new row.
