### ISSUE TITLE
Question on api

### ISSUE THREAD

**Issue by DmitryKey** [tabulapdf/tabula#584]
Hi guys,

This is a question, not a real "issue".

Does tabula expose api? In particular, I'm interested in api support for mouse selected table extraction. Hope my question is clear, let me know if not. Thanks

**Comment by jeremybmerrill** [comment]
HI @DmitryKey: You're asking in the right place.

Tabula does not currently have an HTTP API. It's on the roadmap, but isn't expected soon.

However, Tabula does have [a command-line interface to its extraction engine](https://github.com/tabulapdf/tabula-java). You could provide the coordinates to this... (I don't quite understand what you mean by "api support for mouse selected table extraction" -- I think this is what Tabula does.)

**Comment by DmitryKey** [comment]
Hi @jeremybmerrill : thanks for your quick reply. Sorry for fuzzy wording: you nailed my question exactly. So in order to integrate tabula cli into my own UI it would be sufficient to compute and pass down the coordinates behind the mouse selection? Assuming a PDF is loaded into some sort of viewer component inside the UI.

Do you think, transition from tabula's java cli to a web service is a relatively low effort?

Thanks for your help!

**Comment by jeremybmerrill** [comment]
I'm not sure exactly what you want to do that's different than Tabula itself. And I wouldn't say the Tabula UI was "low effort." But, yes, a minimal clone of the Tabula UI could function by passing the coordinates from the UI into the Java extraction engine (either via the CLI or by integrating directly with the library).

**Comment by DmitryKey** [comment]
@jeremybmerrill Tabula UI is great as a standalone product. That won't work for my case, since our web ui already has the pdf viewer built in. In particular I would like to expose things like extraction methods etc. But looks like, from what you explain, it is relatively straightforward to get the coordinates of a selection and send them over to the extraction engine.
If it is not much to ask, could you please give pointers in the tabula ui code where the coordinate computation is implemented? I'm talking about the feature of the manual table selection.

**Comment by jeremybmerrill** [comment]
Ah, I understand. 

I wouldn't say it's straightforward -- there are a fair number of gotchas -- but it's definitely doable. 

https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/rectangularSelector.js implements drawing selections on the images of the PDF. https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/resizableSelection.js makes it resizable by the user. And https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/pdf_view.js#L52-L95 transforms those into coordinates relative to the actual size of the PDF. And https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/pdf_view.js#L272-L321 sends those coordinates the [very thin API](https://github.com/tabulapdf/tabula/blob/master/webapp/tabula_web.rb) that sits in front of the Java library.

Keep us posted on your project. I and the other developers will be curious to hear how you're integrating Tabula into your system. And let me know if you need more pointers.

Out of curiosity, what PDF viewer are you using?

**Comment by DmitryKey** [comment]
@jeremybmerrill thanks for sharing the js code, that's helpful. For the viewer, it is a customly developed component, that transforms PDF into an HTML representation. I bet that hides own gotchas for the table selection / coordinate calculation, as what user has selected in the HTML representation would need to be mapped to the source PDF.

Thanks for your help!

**Comment by jeremybmerrill** [comment]
Sure thing. Let us know if you have other questions. I think it's basically just a question of figuring out how to make selections and then scale those properly to the units used by tabula-java. (A lot of the complexity in the above code is from preventing selections from overlapping; if you have a simpler use case, you can skip a lot of that.)

**Comment by arpit-gbpec** [comment]
Hello @DmitryKey ,I was just curious to know that did you incorporate this functionality in your system as I myself was looking for something like that.

**Comment by DmitryKey** [comment]
Hi @arpit-gbpec,

No, went with another vendor, mostly due to time pressure and customization points. But I have to say, I love tabula. On of the cases needed to quickly extract tables using tabula UI and it worked swiftly.

Would be looking forward to integrate for future projects.

**Comment by jakehockey10** [comment]
What are the units of the coordinates?  I'm not sure which viewer to use, but I'd like to build something similar to Tabula and was considering using pdf.js as a viewer.  But I wasn't sure what the selection capabilities would look like in this setup.  Is Tabula's pdf view showing just an image?  Are the coordinates dependent on the size of the image of the pdf on screen?
