### ISSUE TITLE
automatically previews and exports only in lattice mode..

### ISSUE THREAD

**Issue by baspeij** [tabulapdf/tabula#587]
on some documents the tables extracted are previewed in lattice mode automatically and changing the mode to stream, the default I presume, changes the preview but not the exported csv?

**Comment by jeremybmerrill** [comment]
@baspeij: I fixed this issue just yesterday, and we haven't had a release since then. There is not currently a workaround, though if you're using Windows or the JAR version (not the Mac version, unfortunately), I could build you a custom version that includes the fix, to test it out.

**Comment by baspeij** [comment]
Wow, quick response.. I just downloaded Tabula-pdf today to see if it
works. The first document went ok in stream mode. A few corrections I
had to make considering multi-lined cells, but I was impressed. The
second document however showed already the issue mentioned. I noticed
that if the file contains a table with a higher number of rows the issue
occurs. Smaller tables don't show the issue somehow

Will the issue be fixed in a future release?
Using the mac version..


Jeremy B. Merrill wrote:

**Comment by jeremybmerrill** [comment]
The issue will be fixed in the next version, but I'm not sure when that'll get released. 

@mtigas: Any chance you could build an "alpha" off of the master branch, to include this fix?

**Comment by tayloramurphy** [comment]
@jeremybmerrill I'm seeing the same issue on a PDF with between 50 and 60 rows per page. Any update on when a fix might be available? Thanks!

**Comment by jeremybmerrill** [comment]
I can make you a pre-release if you're on Windows, Linux or can run the Jar on Mac.

(When will the fix be released? Whenever I can convince the person with the signing keys to build one.)

**Comment by tayloramurphy** [comment]
@jeremybmerrill I'm on Mac, so the Jar would be great. 

Please let me know if there's anything I can do to help move the process along! Thank you for your help on this.

**Comment by jeremybmerrill** [comment]
@tayloramurphy give this a shot: https://www.dropbox.com/s/0gkxj5n64s0hy17/tabula.jar?dl=0

**Comment by tayloramurphy** [comment]
@jeremybmerrill Works great! Hope you can get those keys for an official version. Thank you!!!

**Comment by jeremybmerrill** [comment]
Glad to hear it!

Jeremy B. Merrill
