### ISSUE TITLE
Allow naming of downloaded file

### ISSUE THREAD

**Issue by mihi-tr** [tabulapdf/tabula#59]
When extracting multiple tables out of a PDF it would be handy to be able to name downloaded files in the dialog - right now they are all called "data"

**Comment by jeremybmerrill** [comment]
Done in newUI! (Right now, the file comes out as `tabula-<input filename>.csv`, but it's trivial to turn the hidden input into a text box, if we htink that's necessary see https://github.com/tabulapdf/tabula/issues/257)
