### ISSUE TITLE
First column(Right aligned) merged with second column(Left aligned)

### ISSUE THREAD

**Issue by jkarthic** [tabulapdf/tabula#590]
Have attached a PDF file with a simple table with 4 columns. Out of 4 columns it detects only 3 columns. The first column and second columns are merged into a single column. It is worth mentioning that the first column is right aligned and second column is left aligned.
[out.pdf](https://github.com/tabulapdf/tabula/files/614056/out.pdf)

**Comment by jeremybmerrill** [comment]
The two columns are close enough that it's confusing the "stream" algorithm. Try switching to "lattice", that should give you the result you expect.
