### ISSUE TITLE
Not opening in the Windows 10 - Bug

### ISSUE THREAD

**Issue by shahbazkhan94** [tabulapdf/tabula#591]
Its not opening the **http://127.0.0.1:8080/** not either on Explorer, Google Chrome 54.0.2840.99.
I have Windows 10 Enterprise Build 1607 installed, with Java 6.0270.7 version. 

Please help.

I exactly did as you described in the instruction. Extracted the file and opened the tabula.exe. Tried both with and without admin access.

See the following error messages I got.
![capture](https://cloud.githubusercontent.com/assets/11898353/20663115/29828036-b578-11e6-91a1-7a9b56f86a8a.PNG)

**Comment by jeremybmerrill** [comment]
Hi @shahbazkhan94: Tabula requires Java 7 or greater. If it doesn't work after you've installed Java 7, please let us know.

**Comment by shahbazkhan94** [comment]
Hi @jeremybmerrill : I updated Java to latest version (V8 Update 11) and the server started but it asking for weird login authentication? See the screenshot 

![image](https://cloud.githubusercontent.com/assets/11898353/20858112/971f894c-b95e-11e6-9665-e1b4a54d4c52.png)

**Comment by shahbazkhan94** [comment]
Its done @jeremybmerrill . I have stopped manually other services on the same port and it started.

**Comment by jeremybmerrill** [comment]
Glad it worked
