### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kris-CK** [tabulapdf/tabula#592]
I have always been able to use this tabula. Today, with the new mac download the program does not seem to be working for me.

Received this error:

Tabula API version: 1.1.0.16092117
Filename: Venture Global Budget Pkg 11-28-16.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/3f247ddcc54ab52e1a400fee38d053cec311e676/data

shapes can't be empty

**Comment by jeremybmerrill** [comment]
Hi @Kris-CK: Thank you for the bug report. Can you tell me what Java version you're using?

Also, can you share with us the PDF that's causing this problem?

And what do you mean by "shapes can't be empty"? Is that a message you saw in the Tabula UI, or is that your description of the problem?

**Comment by Kris-CK** [comment]
That's correct. That was the error message. 

However, the program started working again after a few more attempts. Not sure what the issue was. 

Thank you.

**Comment by jeremybmerrill** [comment]
Glad it started working again.
