### ISSUE TITLE
Only able to extract the last page even after clearing the selection and selecting other pages before clicking Auto detect.

### ISSUE THREAD

**Issue by BudTheWiser** [tabulapdf/tabula#597]
[Dec Fulton Tax Sale.pdf](https://github.com/tabulapdf/tabula/files/661729/Dec.Fulton.Tax.Sale.pdf)

**Comment by jeremybmerrill** [comment]
Please just make your selections manually, rather than using autodetect.

**Comment by BudTheWiser** [comment]
Sorry, didn't think to drag the crosshatch.

Duh....

Thanks!

Jeremy B. Merrill wrote:

  Please just make your selections manually, rather than using
autodetect.
  —
You are receiving this because you authored the thread.
Reply to this email directly, view
it on GitHub, or mute
the thread.
  
  
  
  
  
  
  
  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tabulapdf/tabula","title":"tabulapdf/tabula","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/tabulapdf/tabula">"https://github.com/tabulapdf/tabula"</a>}},"updates":{"snippets":[{"icon":"PERSON
","message":"@jeremybmerrill in #597: Please just make your selections manually, rather than using autodetect."}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/tabulapdf/tabula/issues/597#issuecomment-268037170">"https://github.com/tabulapdf/tabula/issues/597#issuecomment-268037170"</a>}}}
