### ISSUE TITLE
Tabula API version: 1.1.0.16092117 - Internal Server Error (500)

### ISSUE THREAD

**Issue by joevector** [tabulapdf/tabula#599]
In the attached pdf you'll find two types of table, a wider one and a taller one. Selecting either or both tables of the same type produce the expected results but the following error appears when selecting both types of table at the same time.

[Amazonas.pdf](https://github.com/tabulapdf/tabula/files/667517/Amazonas.pdf)

```
Tabula API version: 1.1.0.16092117


Filename: Amazonas.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/76a93f5d522062829219ecd8615b8092d1622c88/data
```

**Comment by jeremybmerrill** [comment]
@joevector: please try the newest version of Tabula. I think this error has been fixed (or at least, I can't replicate it now)
