### ISSUE TITLE
Can Tabula allow full pdf to be selected (Automatically through auto detection feature) for Table detection and extraction.

### ISSUE THREAD

**Issue by algoscale1** [tabulapdf/tabula#601]
Hi Team,

I want to avoid manual intervention (of selecting the Area for table detection). Can we select  full pdf for Table detection and extraction?

if yes, please let me know the part of Source-code i need to customize.

Regards,

**Comment by jazzido** [comment]
Hi @algoscale1,

The table detection and extraction algorithms are implemented in [`tabula-java`](https://github.com/tabulapdf/tabula-java), please check the README and tests for more information.

**Comment by algoscale1** [comment]
Thanks a lot. Will explore this one :)
