### ISSUE TITLE
Watermark creating problem in parsing table

### ISSUE THREAD

**Issue by suresh-soundararajan** [tabulapdf/tabula#609]
I think the product is doing very good job in parsing the table. Find a minor issue like while parsing the content it also getting the watermark background text with the part of the field values.

Any idea how to fix it?

**Comment by jeremybmerrill** [comment]
Hi @suresh-soundararajan: I don't think I know of a workaround, unfortunately. Tabula extracts the text that's present in the table, even if some of that text is "properly" part of the watermark. You could potentially use [tabula-java](http://github.com/tabulapdf/tabula-java) to ignore characters whose size/color signals that they're part of the watermark () -- but it'd probably be easier to manually remove the watermark text in the output.

**Comment by suresh-soundararajan** [comment]
Thanks for your reply..@jeremybmerrill.. But it would be helpful if there is some option to detect the watermark based on the layers and remove if necessary..

**Comment by jeremybmerrill** [comment]
I agree that would be neat. I just don't know how to do it in the general case. (If you script tabula-java, you could pretty simply exclude text that isn't the same color of the real body color, probably black; but that's a fix for your PDF only.)
