### ISSUE TITLE
Tabula Error Report

### ISSUE THREAD

**Issue by squidding007** [tabulapdf/tabula#610]
**Link to Document: http://www.ctps.org/data/pdf/studies/transit/2012_MBTA_Commuter_Rail_Passenger_Counts/MBTA_Commuter_Rail_Passenger_Count_Results.pdf** (Plots starting page 54)

Tabula API version: 1.1.0.16092117
Filename: MBTA_Commuter_Rail_Passenger_Count_Results.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/7ea415b4767d0d84a50b5709c9acc2f57c113eae/data

Many thanks,
Alex

**Comment by jeremybmerrill** [comment]
Hi @squidding007:

Thanks for reporting the problem. I'm seeing that error too, with this traceback: 

````
Java::JavaLang::IndexOutOfBoundsException: Index: 0, Size: 0
	java.util.ArrayList.rangeCheck(java/util/ArrayList.java:653)
	java.util.ArrayList.get(java/util/ArrayList.java:429)
	technology.tabula.extractors.BasicExtractionAlgorithm.columnPositions(technology/tabula/extractors/BasicExtractionAlgorithm.java:113)
	technology.tabula.extractors.BasicExtractionAlgorithm.extract(technology/tabula/extractors/BasicExtractionAlgorithm.java:63)
````
I don't know of a workaround at the moment, and we'll try to get it fixed, but the error is likely from a page that doesn't have a table (or that has a very very weird table). Did you make the selections manually, or using the Repeat Selections button? If the latter, I'd recommend going thru and eliminating any selections that look weird and trying again; I was able to extract data successfully from several of the tables without trouble.
