### ISSUE TITLE
Last screen fails

### ISSUE THREAD

**Issue by alasdairfraser** [tabulapdf/tabula#611]
Tabula API version: 1.1.0.16092117
Filename: Annex from 1314 performance.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/abfb86cf337210cb383a3f6cb3cb0c3ea357a4f2/data

shapes can't be empty
[Annex from 1314 performance.pdf](https://github.com/tabulapdf/tabula/files/700482/Annex.from.1314.performance.pdf)

**Comment by jeremybmerrill** [comment]
Hi @alasdairfraser, this bug is fixed in the master branch of Tabula, but the fix hasn't made it into the release. If you tell me which platform you're using, I can potentially build you a new version of Tabula that should work correctly.

**Comment by alasdairfraser** [comment]
JeremyThat would be a huge help. I'm using macOS 10.12.2 but can use Windows 10 also. BestAlasdair

Get Outlook for iOS

		_____________________________

**Comment by jeremybmerrill** [comment]
@alasdairfraser: try this windows build out and let me know if it works: https://www.dropbox.com/s/ga92sdlpyjsiwqu/tabula-win-rev4860c428a4e50d2cac5ac02e43ee194f54e7dd28.zip?dl=0

(building for Mac is harder because of their package-signing requirements, hence Windows.)

**Comment by alasdairfraser** [comment]
Many thanks!

Get Outlook for iOS

		_____________________________

**Comment by alasdairfraser** [comment]
Hi JeremyThis definitely works for small documents. Will try larger documents later on. Many thanks for developing Tabula, it's extremely useful. 

Typed on mobile

Alasdair Fraser | +44 7538 708 356 | +256 778 049 788 | alasdairfraser1

		_____________________________

**Comment by jeremybmerrill** [comment]
Feel free to reopen if the bug recurs.
