### ISSUE TITLE
Multipage table export uses Stream for first page and Lattice for the rest

### ISSUE THREAD

**Issue by Geotig** [tabulapdf/tabula#613]
In this pdf file: [cf-rauld_rp.pdf](http://www.tesis.uchile.cl/tesis/uchile/2011/cf-rauld_rp/pdfAmont/cf-rauld_rp.pdf) when I select the tables from pages 422 to 444 and go to Preview and Export data only the first page is correctly detected using the Stream technique, and the rest seems to be extracted using the Lattice technique. If I click in Stream to reload the data, all the pages are displayed correctly in the web, but when I export them to CSV, TSV, zip or other format, only the first page is correctly exported.

I'm using the linux tabula.jar in Solus OS with openjdk-8 as the java engine runtime.

Tomás

**Comment by jeremybmerrill** [comment]
Hi Tomás / @Geotig : This is a known issue that's fixed in master, but not in the current packaged version. Can you give this JAR a try and see if it fixes the issue for you? https://www.dropbox.com/s/0gkxj5n64s0hy17/tabula.jar?dl=0

**Comment by Geotig** [comment]
Hi Jeremy,

Thanks for this version, it allows me to export the data I need. I assume that you are aware of this, but it only exports correctly if I manually select the Stream method of extraction before exporting.

I'm available if more testing is needed.

**Comment by jeremybmerrill** [comment]
@Geotig: Great, glad to hear it. 

> it only exports correctly if I manually select the Stream method of extraction before exporting.

Right. Tabula makes a "guess" about which of the two extraction methods to use, and then preselects that. This guess is usually right, but often wrong; improving it is not a high priority right now, since it's easy to switch methods and Tabula's goal isn't to be totally automated.
