### ISSUE TITLE
Reporting error

### ISSUE THREAD

**Issue by wcgortel** [tabulapdf/tabula#617]
Tbh not sure what happened but here's the pdf that's causing issues. Obscure indian statistical release, so fair enough it's not the easiest to parse.

Your software makes me very happy btw. Glad to have it around. 

[All India Debt & Investment Survey 2013 (70th Round).pdf](https://github.com/tabulapdf/tabula/files/723627/All.India.Debt.Investment.Survey.2013.70th.Round.pdf)

**Comment by jeremybmerrill** [comment]
This is a weird PDF with a lot of weird bugs that I think breaks JPedal for some reason. (JPedal is a library that Tabula uses to make thumbnails.) Not much we can do about it, unfortunately. Glad Tabula is useful to you!
