### ISSUE TITLE
Cannot convert, PDF reported as non-text, Acrobat claims is text

### ISSUE THREAD

**Issue by lymankj** [tabulapdf/tabula#618]
The PDF is a table on several pages but with a header and footer added. Acrobat reports that the document contains renderable text when trying to run the OCR command.

This information is public on the web, released by a state agency. It is probable that they obfuscate the data in a PDF format to make it more difficult to analyze.

[multi.pdf](https://github.com/tabulapdf/tabula/files/725440/multi.pdf)

**Comment by jeremybmerrill** [comment]
I suspect it's a mundane bug with PDFBox, the library which Tabula uses to access PDF data. We're working on getting a more up-to-date version of PDFBox integrated into Tabula, which would likely fix the problem. Until then, you might try "printing" the PDF to another PDF, to see if it gets reconstituted in a way that Tabula/PDFBox can handle.

(It's possible that the agency obfuscates the data, but I suspect it's more likely that they just use a janky PDF generator, which seems to be confirmed by the metadata, where the PDF is claimed by PHPMyAdmin *AND* LibreOffice.)
