### ISSUE TITLE
Error in extracting Data form a particular type of pdf

### ISSUE THREAD

**Issue by MAELAIDOUNI** [tabulapdf/tabula#619]
Hi,
I have an error when i try to extract data tables from one pdf 

"Tabula API version: 1.1.0.16092117
Filename: vll-sfcr-30-june-2016.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/01b63ad543dd9869eefd41ad864f0b9ff290c28f/data"

**Comment by jeremybmerrill** [comment]
@MAELAIDOUNI Can you try the newest version of Tabula, released two weeks ago? That likely will fix the issue. If not, can you please send us the PDF too? (If the issue isn't fixed, please reopen the issue.)
