### ISSUE TITLE
Specifying area and using nospreadsheet=True doesn't work

### ISSUE THREAD

**Issue by Kanz95** [tabulapdf/tabula#622]
I have a pdf where guessing or autodetect tables isn't able to find the table and the table is a Stream table(columns separated by white spaces). I used tabula-py where the code goes like:

`df=tabula.read_pdf("sample.pdf",nospreadsheet=True,area=(321.3,49.459,836.719,567.109))`

I get an empty dataframe after executing .But mentioning the same area and using it through tabula in windows produces me a output which is what i want.

is there any way?

**Comment by jeremybmerrill** [comment]
Hi @Kanz95, sounds like this is a bug with the ["tabulizer" R bindings](https://github.com/ropensci/tabulizer) for Tabula, not with the Tabula windows GUI. Please open this bug there: https://github.com/ropensci/tabulizer
