### ISSUE TITLE
Extracted cells missing last character in some cases

### ISSUE THREAD

**Issue by jyunis** [tabulapdf/tabula#623]
I'm attempting to extract address info from an admittedly messy PDF file (attached). The process is actually pretty close to accurate, except it often leaves out the last digit of the zip code field (ZIP). For example, the cells with "55306" almost always come out as "5530" in the extracted spreadsheet. I'm using the following command:

`java -jar /opt/web/tabula/tabula-0.9.1-jar-with-dependencies.jar --pages all --spreadsheet -o /tmp/spreadsheet.txt /opt/web/657.pdf`

Example of resultant CSV:

`
"",115 MAPLE ISLAND RD,JIM AND CHERYL PRINCE,BURNSVILLE,5530,0,,1,RES-1,,9528984538,
"",2844 SUMTER AVE S,TIM SKOGEN,BURNSVILLE,5530,0,,1,RES-1,,4254883131,
2,708 CRYSTAL LAKE RD E,ELIZABETH THALHUBER,BURNSVILLE,5530,3000,,1,RES-1,,18003679444,
3,15201 LEAD ST,STEVE TILLGES,BURNSVILLE,5530,3000,,1,RES-1,,7276427401,
3,15517 LOGARTO LN,KIMBERLY KUSSER,BURNSVILLE,5530,3000,,1,RES-1,,00000000000,
3,15709 MAPLE ISLAND CT,DONNA THOMPSON,BURNSVILLE,5530,3000,,1,RES-1,,6514631977,
3,170 MAPLE ISLAND RD,RANDALL HALL,BURNSVILLE,5530,3000,,1,RES-1,,777-555-4434,
3,342 MAPLE ISLAND RD,KARISSA DEE ZIMMER,BURNSVILLE,5530,3000,,1,RES-1,,6127605801,
3,346 MAPLE ISLAND RD,MULTIPLE NAMES,BURNSVILLE,5530,3000,,2,RES-2,,800-526-3404,
3,391 MAPLE ISLAND RD,MULTIPLE NAMES,BURNSVILLE,5530,3000,,2,RES-2,,5027182272,
3,4 MAPLE ISLAND RD,SARAH FLICEK,BURNSVILLE,5530,3000,,1,RES-1,,8282540054,
3,15001 STEVENS AVE,KIM PARNELL,BURNSVILLE,5530,3000,,1,RES-1,,6124249907,
3,509 E 153RD ST,SUSAN HARPER,BURNSVILLE,5530,3000,,1,RES-1,,4158827765,
4,1037 CRYSTAL LAKE RD E,RAIS KANWAR,BURNSVILLE,5530,3037,,1,RES-1,,9525940955,
5,405 W 158TH ST,MONIA,BURNSVILLE,5530,7500,,1,RES-1,,6126368889,
`
[657.pdf](https://github.com/tabulapdf/tabula/files/751723/657.pdf)

**Comment by jyunis** [comment]
I have tried 0.9.2 with the same result.

**Comment by jeremybmerrill** [comment]
@jyunis Can you please open this bug under https://github.com/tabulapdf/tabula-java? That's the repo for the command-line app.

**Comment by jazzido** [comment]
@jeremybmerrill Just moved it (BTW, [ZenHub](http://zenhub.io) is a great tool for managing GH issues)
