### ISSUE TITLE
tabula didn't finish

### ISSUE THREAD

**Issue by jalbertbowden** [tabulapdf/tabula#624]
reporting because you asked for it. sorry if this doesn't follow the format, i went to the guidelines and clicked on reporting and it just takes me [here](https://github.com/tabulapdf/tabula).  

was trying to generate csv from a rather large pdf. probably 125 pages of straight tabular data. got this message:  
Preview of Extracted Tabular Data

Tabula couldn't finish processing your request. We'd appreciate if you could report this error in our issue tracker. If possible, please include a link to the document that caused the error and the text below:

Tabula API version: 1.0.1
Filename: 2016-General-Election-Canvass-Book-WEB.pdf

hope that is good enough? if you need more, let me know.

**Comment by jeremybmerrill** [comment]
Hi @jalbertbowden: Can you try the newest version of Tabula, released two weeks ago? That likely will fix the issue. If not, can you please send us the PDF too? (If the issue isn't fixed, please reopen the issue.)
