### ISSUE TITLE
Column endings overlap, cant be read.

### ISSUE THREAD

**Issue by weirdnose** [tabulapdf/tabula#631]
Hello,

I tried to import this pdf file into tabula 

http://b2run.maxfunsports.com/event/competition?id=13632

(press download on right side to generate the PDF).

Unfortunately the PDF seems to have some overlap between columns, e.g. page 9, where the name of the participant is very very close to the time. This leads to tabula thinking this is actually one column (no space for first row) and the whole page will have a column where name and time are in one column.

Page 17 is even worse, the name of the participant in the second row gets actually mixed up with the time of the runner, leading to something like this 

G0a0ll:e2g8o:33.0

which should be 

 Gallego 00:28:33.0

**Comment by jeremybmerrill** [comment]
Yep, that's gonna be a problem. If the PDF has ruling lines betwene the columns (I didn't download the PDF to check), you can switch to Lattice mode (on the data preview page). Otherwise you're out of luck.
