### ISSUE TITLE
Column span issue

### ISSUE THREAD

**Issue by suresh-soundararajan** [tabulapdf/tabula#632]
I am try some sample with the tabula. And it really working great. But Facing issue with the column span in the table. Is there any work around for this to detect the col span and make the column repeated as the header for the next row content. It would be great if this scenario is capture and address in the future.

Thanks,
SureshKumar S

**Comment by jeremybmerrill** [comment]
No, this is not and will not ever be supported. Tabula does not modify the table by adding additional elements (because this would never be generalizable across the innumerable crappy ways that people lay out their PDFs)
