### ISSUE TITLE
line and columns not seen right grey background

### ISSUE THREAD

**Issue by Vartkat** [tabulapdf/tabula#634]
<img width="971" alt="capture d ecran 2017-02-23 a 14 00 38" src="https://cloud.githubusercontent.com/assets/1696899/23260207/019e0ac0-f9d1-11e6-9e4e-ea1a993824a2.png">
<img width="822" alt="capture d ecran 2017-02-23 a 14 00 14" src="https://cloud.githubusercontent.com/assets/1696899/23260206/019c642c-f9d1-11e6-8e48-6ab9d87a428d.png">

Hello,

I'm trying to get my bank statements tables into CSV but Tabula doesn't succeed. I think that's because of the grey background. Second problem is my table cells contains several lines and Tabula sees one row per line where it should see (looking for the boundaries) that it's one cell containing several lines.
And last, the right two columns are seen as one column.

I'm on Mac OS 10.11.6 aka El Capitan.

Thanks for your help

regards

Vartan

**Comment by jeremybmerrill** [comment]
Try lattice mode. That should fix most of the problems, though the content of the explanation cell ("COTIS FREQUENCE PRO" etc) will still as disorganized as it appears on the bank statemnet. (The background color shouldn't be a problem...)

**Comment by Vartkat** [comment]
Lattice gives "no data" and Stream doesn't understand that 06/12 is a date and 39,76 is an amount so they shouldn't be in the same cell (I know I'm seeing things as a human and not as the process...but I'm human :-) ).
About lines, is there a way to have the lines with same background color in the same cell ?

Thanks 

Vartan

**Comment by jeremybmerrill** [comment]
@Vartkat: Stream mode uses whitespace to distinguish columns. It should separate the date and the amount if there's no text in your selection that spans both columns; you may need to exclude some headers from the selection.

For lattice mode, the table needs to have ruling lines on all sides -- and those ruling lines need to be included in your selection.

**Comment by Vartkat** [comment]
@jeremybmerrill As you can see on the screenshot, there is a space, there's even a vertical line, and as I read other question I didn't include headers in the selection, only rows with data.

**Comment by jeremybmerrill** [comment]
It's possible there's some weird features of your PDF in particular (maybe spaces joining the dates and the amounts, or something like that) that are confusing Tabula. Bank statements seem to commonly be generated in an awful way.

Or maybe text that visually appears somewhere else, but seems to Tabula (because of errors in an underlying library) to span both columns. Rotated text often does this.

**Comment by Vartkat** [comment]
You mean a vertical text somewhere else on the page, outside the selected area ? Means that Tabula is looking outside the area ? 
Do you have an answer for the lines problem ?
Do you need the pdf file to test it ?
