### ISSUE TITLE
El Salvador Ag Stats

### ISSUE THREAD

**Issue by geilerts** [tabulapdf/tabula#635]
Hi. Love the product.  I'm extracting large amounts of historic data from all over the world. In this application of it, I'm using the newest version of Tbula (as of Feb 25), on Win10.  I'm extracting ag stats from a pdf (attached).  Many of the tables work fine in stream mode. Some don't. 

Cuadro 8, on page 10 is one that doesn't. 
I mark for extraction only the first three columns, with NO headers. Columns 2 and 3 are not separated, AND, the first and last row is not recognized. 
I mark only column 2 and 3, NO headers, and the same result. 
Thanks
Gary
[anuario-de-estadisticas-agropecuarias-2014-2015.pdf](https://github.com/tabulapdf/tabula/files/801277/anuario-de-estadisticas-agropecuarias-2014-2015.pdf)

**Comment by jeremybmerrill** [comment]
Hi Gary, please try specifying Stream mode. Tabula is mistakenly "guessing" that it ought to use the other extraction mode ("Lattice") because of the various ruling lines on the page. I think Stream mode works perfectly.
