### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by OrsuSuni** [tabulapdf/tabula#639]
While passing jruby -G -S rakeup iam getting the following error
![capture](https://cloud.githubusercontent.com/assets/26080134/23510913/638d10a4-ff81-11e6-937a-2fb4ef9732f4.PNG)
Please give me a solution.

**Comment by jeremybmerrill** [comment]
Can you try running `gem install bundler` first?

Jeremy B. Merrill

**Comment by OrsuSuni** [comment]
I have done it and bundler installed successfully...

**Comment by jazzido** [comment]
@OrsuSuni,

If you have both Ruby _and_ JRuby on the same machine, it's possible that the commands `gem` and `bundler` default to being executed with Ruby and not JRuby.

Run these commands instead:

  - `jruby -S gem install bundler`
  - `jruby -S bundle install`.

Let us know how that goes.

**Comment by OrsuSuni** [comment]
Thanks for your response...
I have executed the commands you said to use.. 
![capture4](https://cloud.githubusercontent.com/assets/26080134/23600051/a3695908-026a-11e7-929d-73b3307b4e91.PNG)

**Comment by jeremybmerrill** [comment]
Does it work now, if you visit localhost:9292? I'm seeing what look like successful web requests.

**Comment by OrsuSuni** [comment]
No it doesn't opened any browser and i tried running the same command again but it showed the error message  "No such file or directory".. I am very new to this technology and need to converter Pdf table data into text.. Please help me with this..

![capture7](https://cloud.githubusercontent.com/assets/26080134/23646867/dd74a6f6-0338-11e7-86a3-5929c90c7998.PNG)

**Comment by jeremybmerrill** [comment]
It might be easier to try the packaged Windows version if you don't need to modify Tabula: https://github.com/tabulapdf/tabula/releases/tag/v1.1.1

Otherwise, you'll need to install `git`.
