### ISSUE TITLE
Import error on Kubuntu 16.04 JRE 9

### ISSUE THREAD

**Issue by Neudrino** [tabulapdf/tabula#641]
I am experiencing an error when trying to import any PDF file. Repeats every time. Firefox or Chromium Browser makes no difference. Tried 2 different PDF files. Appending 3 log files of the same issue (tried 3x - should be the same?). Hope everything is in there.

[hs_err_pid4798.log.txt](https://github.com/tabulapdf/tabula/files/817336/hs_err_pid4798.log.txt)
[hs_err_pid5169.log.txt](https://github.com/tabulapdf/tabula/files/817337/hs_err_pid5169.log.txt)
[hs_err_pid5305.log.txt](https://github.com/tabulapdf/tabula/files/817338/hs_err_pid5305.log.txt)

Anything more you need?

**Comment by Neudrino** [comment]
Works with JRE8 though! :+1:

**Comment by jazzido** [comment]
Thanks @Neudrino. That looks like an exception from the deepest trenches of JRE9 (in the font libraries, it appears).

Closing from now, since we don't "officially" support JRE9.
