### ISSUE TITLE
how can i know table context content?

### ISSUE THREAD

**Issue by bczhou** [tabulapdf/tabula#649]
can tabula extract context content of the pdf? or I must use pdfbox to extract content of the pdf?

**Comment by jazzido** [comment]
What do you mean by *context content*?

**Comment by bczhou** [comment]
a pdf with table and text,I have to know where the text at the top of the table and at the below of the table.

**Comment by jeremybmerrill** [comment]
@bczhou: Yes, Tabula's Stream mode can usually extract any text on the page. 

However, any errors relating to non-tabular content are not within scope for Tabula.

**Comment by bczhou** [comment]
the pdf file I extracted  is spreadsheet and I want to use lattice mode to extract tables and use stream mode to extract other non-tabular content, and then combine tables and contents together. how can i ensure the order of the tables and contents.
