### ISSUE TITLE
Replace PDF rendering lib: JPedal → PDFBox

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#650]
After tabulapdf/tabula-java#150 is merged and released, we should get rid of JPedal for generating PDF thumbnails. Besides the benefit dropping a dependency, we've been seeing repeated reports of it failing to render some documents (#647, #615, #513, #470, #461)

**Comment by jeremybmerrill** [comment]
this is implemented here: https://github.com/tabulapdf/tabula-web-java

**Comment by jeremybmerrill** [comment]
Done (but barely tested) here: 33c8588

**Comment by jeremybmerrill** [comment]
this is in the [pdfbox2](https://github.com/tabulapdf/tabula/tree/pdfbox2) branch here.
