### ISSUE TITLE
tabulizer is not available (for R version 3.3.2)

### ISSUE THREAD

**Issue by kiranhsgithub** [tabulapdf/tabula#654]
I tried installing this R package and it gave below error. 

Installing package into ‘C:/Users/hskir/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘tabulizer’ is not available (for R version 3.3.2)

May I know which version is supported. Thanks

**Comment by jeremybmerrill** [comment]
Please open this bug with Tabulizer: https://github.com/ropensci/tabulizer

**Comment by kiranhsgithub** [comment]
thanks
