### ISSUE TITLE
Tips for integrating into SpringMVC app?

### ISSUE THREAD

**Issue by iWhacko** [tabulapdf/tabula#655]
Hi, 

I'm building a Spring MVC app with the need to import PDF files. I plan on using Tabula-java in my project. And I'm sure that all works fine.

But I will probably need a preview function in my webapp. 
What should be my best course of action?

Should I rewrite the ruby code to a SpringMVC equivalent? (and reuse the 'static' code from this project)
Or is there some PDF preview library which I can use and also select regions with?
I have been searching for a while and I'm not sure which route to take.

Please advise.
Thanks

**Comment by jazzido** [comment]
Hi @iWhacko,

A few weeks ago I started prototyping a [Java rewrite of Tabula](https://github.com/tabulapdf/tabula-web-java). It's not yet ready for general use, but it might give you some pointers on how to implement a PDF rendering function. Alternatively, you can use JPedal, or even PDFBox for rendering PDF pages to an image.

**Comment by iWhacko** [comment]
Hi Jazzido, 

Awesome! this will surely speed things along. :)
