### ISSUE TITLE
not support Chinese ? 

### ISSUE THREAD

**Issue by trheyi** [tabulapdf/tabula#665]
Tabula  not support Chinese  pdf file ? Chinese words not recognized !    it seems  font file problem, who can help me ?  Thanks a lot !~ 
[report.pdf](https://github.com/tabulapdf/tabula/files/949696/report.pdf)

**Comment by jazzido** [comment]
Hi @trheyi,

Thanks for your report. 

Unfortunately, that document is a bit of a pathological case. Numerals are encoded as text, but Chinese characters are bitmaps (images). Tabula will not be able to process that.

**Comment by trheyi** [comment]
@jazzido  thanks .
