### ISSUE TITLE
Can I view the exact call that the tabula web application is making to the java jar file?

### ISSUE THREAD

**Issue by gandhis1** [tabulapdf/tabula#668]
I'd like to see the exact call, specifically the area parameter. I find it very difficult to figure out the ideal parameterization for area in order to get what I want when I am using the java interface. However, it is extremely easy to do this when you are using the interactive web application. Ergo, I'd like to use the web application to figure out the optimal parameterizatation for PDF table extraction, and then use this same command by calling the java jar file.

I promise to donate $50 to the project if someone can help :-D

**Comment by jazzido** [comment]
Hi @gandhis1,

Tabula allows exporting a *script* that contains the area parameter:

![image](https://cloud.githubusercontent.com/assets/27584/25549504/32cd3764-2c40-11e7-89b4-97cbd1841812.png)


We accept donations over at OpenCollective: https://opencollective.com/tabulapdf?utm_campaign=tabulapdf&utm_medium=github&utm_source=opencollective#support

😀

**Comment by gandhis1** [comment]
Donated - thanks for the reply. If anyone browsing this forum needs it, I created a short Python wrapper for the Java file which returns a Pandas DataFrame:

```
def parse_pdf_tabula(pdf_file_path, page=1, top_left_bottom_right=None):
    """
    Parses a PDF file using Tabula and returns a Pandas DataFrame.
    Takes a PDF file path, a page number, and a tuple of four floats
    signifying the top, left, bottom, and right vertices.
    """
    # Get location of tabula binaries
    tabula_jar = os.path.join(os.path.dirname(__file__),
                              "tabula", "tabula.jar")
    if not os.path.exists(tabula_jar):
        raise RuntimeError("The tabula jar file is missing.")

    # Either guess the table area or it can be explicitly parameterized
    if top_left_bottom_right is None:
        area_parameter = "-g"
    else:
        area_parameter = "-a " + ",".join(top_left_bottom_right)

    # Construct the process call string and initiate the process
    tabula_call = ('java -jar "{0}" -p {1} {2} "{3}"'
                   .format(tabula_jar,
                           page,
                           area_parameter,
                           pdf_file_path))
    process = Popen(tabula_call, stdout=PIPE, stderr=PIPE)

    # Check the return code and get the standard out/error
    std_out, std_err = process.communicate()
    if process.returncode != 0:
        raise RuntimeError(std_err)

    # Create a StringIO object and parse CSV to create DataFrame
    string_io = StringIO(std_out)
    table_df = pd.read_csv(string_io)
    return table_df
```

**Comment by jazzido** [comment]
Thanks!

BTW, you might want to take a look at [tabula-py](https://github.com/chezou/tabula-py), a Python wrapper written by @chezou.
