### ISSUE TITLE
Text validation issue

### ISSUE THREAD

**Issue by nannal** [tabulapdf/tabula#670]
Hi, 

I've a PDF document that contains the texts

> "using <frame\>, <iframe\>, <object\>, <embed\>, or <applet\>"

&

> "<frame\> or <iframe\>"

This opens an iframe in the Preview of Extracted Tabular Data page

I suspect I'd be able to do very bad things with this.

**Comment by jeremybmerrill** [comment]
Oh, that's interesting. Thank you for reporting this.

Just to talk thru my thought process: this is only a problem in the Preview pane and we don't need to escape the output in the CSV/JSON/etc. output. Do you agree?

`CGI.escapeHTML` will probably solve this, I think.

**Comment by jeremybmerrill** [comment]
I think I've fixed this here: https://github.com/tabulapdf/tabula/pull/671

@jazzido @mtigas wanna take a look?

**Comment by jeremybmerrill** [comment]
Fixed; merged from #671

**Comment by jeremybmerrill** [comment]
@nannal thanks for reporting this, great find!

**Comment by nannal** [comment]
No worries, thanks for fixing it.
