### ISSUE TITLE
Table in landscape form in PDF

### ISSUE THREAD

**Issue by shreya2105** [tabulapdf/tabula#677]
Hi Tabula developers,
I'm struggling to extract a table from pdf into excel spreadsheet. It has bungled the extraction process a couple times now. Is tabula not set up for horizontal tables?

The table is at pg 124 in the attached pdf. Please take a look if you can and help me. 
[Gangareport.pdf](https://github.com/tabulapdf/tabula/files/992577/Gangareport.pdf)

**Comment by jazzido** [comment]
Hi @shreya2105,

Tabula can't deal with rotated pages directly. I'd recommend that you rotate that page with a PDF viewer application (Preview.app in macOS can do that), save that page as a separate file and trying processing it again.
