### ISSUE TITLE
not getting the opening screen in Tabula

### ISSUE THREAD

**Issue by Shilohtd** [tabulapdf/tabula#683]
I'm installing tabula for windows and I'm getting the message below when I try to open it. I've tried running it from the EXE and manually and it's just not behaving for me. HELP!

![tabula issue](https://cloud.githubusercontent.com/assets/15840186/26432515/3f1ab8e0-40ca-11e7-9609-c9320e21b980.PNG)

**Comment by jazzido** [comment]
You have some other service running on port 8080. I don't think the port number can be changed when running from the EXE build. Try downloading our jar and running it like this:

```
java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Dwarbler.port=9999 -jar tabula.jar
```
