### ISSUE TITLE
carefully selected all columns, then CRASH

### ISSUE THREAD

**Issue by DVPulver** [tabulapdf/tabula#687]
Trying to convert a veto list from Governor's office. Had it all selected, then it wouldn't wor
[Final-Veto-List-2017-As-published.pdf](https://github.com/tabulapdf/tabula/files/1049338/Final-Veto-List-2017-As-published.pdf)
k.

**Comment by jazzido** [comment]
I could not reproduce your issue. Please provide a more detailed description (screenshots of selections, pages where it happened)
