### ISSUE TITLE
tricky table

### ISSUE THREAD

**Issue by sdangt** [tabulapdf/tabula#690]
I'm really happy to have discovered this tool.  As sometimes happens, I discover the open source project later or by accident.  This is such a useful thing that this tool does, so thank you very much for your work!

Here's a table that I just tried to process.

https://www.rjobrien.com/documents/shared/margins/margins.pdf

It's a poorly designed table from a data use point of view, but I think a useful test specimen for your tool because it's human-readable.  The entire point of your tool is to help people extract data from tables that were designed by people who maybe weren't being very thoughtful about how others might use the data.  In a perfect world, no one would provide data in PDF form.

The table uses multiple header lines.  It also has I guess what Excel would call merged cells for those headers, but below the unmerged cells that are the actual categories.

Anyway, I'm curious what you think of it.

Take care,
Dan

**Comment by gandhis1** [comment]
Tabula isn't magic bullet, unfortunately. If your data is 1 element in 1st cell, with 1 header row, it will work perfectly. If it isn't, then it is very likely you will have to post-production the output.

**Comment by sdangt** [comment]
Thanks.  Are you planning to add any additional flexibility or perhaps options to select to allow this?

As long as it produces consistent output, it ought to be possible to automate the post-processing, so it's still useful for these types of documents.

By the way, I tried to make a small one-time donation but wound up accidentally subscribed to a monthly payment at Open Collective.  I was not pleased with that.  I canceled it but it should be clearer.  Rarely is that type of donation a monthly subscription _by default_.

Anyway, thanks again for a nice program.

**Comment by jazzido** [comment]
Thanks for your donation, @sdangt. Sorry to hear about the accidental monthly subscription. We will mention that to OpenCollective (the service we use to collect donations).

Regarding your use case, try leaving out the headers (cells that span multiple columns) out of the selection. For tables without ruling lines, it's (currently) impossible for Tabula to segment cells.
