### ISSUE TITLE
Auto-detect borders of rows and columns

### ISSUE THREAD

**Issue by rajatchaudhary-innoplexus** [tabulapdf/tabula#691]
Hi @jeremybmerrill , 
If tabula can auto-detect the table in a pdf (I am assuming by looking the border of the table), why it can not detect the lines between rows and columns. If tabula can detect the lines between rows and columns it would be very easy to extract the **multiple lines data from a single row**. As of now, there is a lot of noise while extracting this kind of data.
Please provide your views. If you have fixed it when can I expect the next release?

Thanks

**Comment by jazzido** [comment]
Tabula is a volunteer-run project, so you can't expect any planned release. 

Also, we need a test document and a detailed description of the issue.
