### ISSUE TITLE
Error with tabula

### ISSUE THREAD

**Issue by Nicoolmontilla** [tabulapdf/tabula#693]
link pdf: http://enfermedades-raras.org/images/stories/documentos/Estudio_ENSERio.pdf

Tabula API version: 1.1.0.16092117
Filename: Estudio_ENSERio.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/4ac8c0cb69b8ad0a1fee6b8c9e4fd91b1f73b8e2/data

**Comment by jazzido** [comment]
Thanks, @Nicoolmontilla.

This issue is now solved in the development branch, which will be released in the coming weeks.
