### ISSUE TITLE
tough table to convert - comes out blank

### ISSUE THREAD

**Issue by vniemeyer** [tabulapdf/tabula#695]
[ExtractPage1.pdf](https://github.com/tabulapdf/tabula/files/1089545/ExtractPage1.pdf)

any ideas what to try?

**Comment by jazzido** [comment]
Thanks for the report @vniemeyer.

That PDF is particularly nasty. It seems to have been generated with multiple small images. Tabula will not be able to process it.

**Comment by vniemeyer** [comment]
Thank you, I can believe it.  I appreciate you looking at it.
Best,Vic
