### ISSUE TITLE
Extracting Table from PDF

### ISSUE THREAD

**Issue by shahutpal** [tabulapdf/tabula#697]
Dear Team,

I am getting below error while uploading PDF file.

Sorry, your file upload could not be processed. Please double-check that the file you uploaded is a valid PDF file and try again.

Attaching files for your reference.
[test.pdf](https://github.com/tabulapdf/tabula/files/1105249/test.pdf)

**Comment by jazzido** [comment]
Hi @shahutpal,

Thanks for your report. This issue is now solved in the development branch, which will be released in the coming weeks.
