### ISSUE TITLE
Tabula won't upload my PDF, help!

### ISSUE THREAD

**Issue by william-mathis** [tabulapdf/tabula#698]
I am trying to upload this PDF (https://www.cdc.gov/nchs/data/nvsr/nvsr64/nvsr64_12.pdf), which I downloaded to my hard drive. I keep getting the error message: " Sorry, your file upload could not be processed. Please double-check that the file you uploaded is a valid PDF file and try again." As far as I can tell, it is a valid PDF. It's not an image file. I had previously extracted data from a similar PDF (the same report but from a different year). Can't figure out why this is not working. My Tabula is updated to the newest version and I tried to upload the PDF on two different machines with no luck.

**Comment by jazzido** [comment]
Thanks for your report @william-mathis,

This issue is now solved in the development branch, which will be released in the coming weeks.
