### ISSUE TITLE
Error while extracting

### ISSUE THREAD

**Issue by bn326160** [tabulapdf/tabula#702]
Tabula API version: 1.1.1.17021116
Filename: ParkerStore catalogue 2012_NL.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/89d7a3a9bb33d73ded924a67c562c25ec25a3b88/data

Comparison method violates its general contract!

PDF url: http://www.parker.com/literature/Corporate%20EMEA/ParkerStore%20catalogue%202012/ParkerStore%20catalogue%202012_NL.pdf

**Comment by cjwinchester** [comment]
Got the same error while parsing [this PDF](http://www.elpasoelections.com/2016General/2016gensovc.pdf).

```
Tabula API version: 1.1.1.17021116
Filename: _elpaso2016genraw.pdf
Internal Server Error (500)
      
        Request Method:
        POST
            
        Request URL:
        http://127.0.0.1:8080/pdf/ca6afd7d16910336cb10f5bbd16dc4c816da0c24/data

Comparison method violates its general contract!
```

Imported fine, then I clicked "Autodetect Tables," then I clicked "Preview & Export Extracted Data," and this error was thrown.

Thanks!

**Comment by jazzido** [comment]
Hi @bn326160 and @cjwinchester,

Thanks for reported the issue. We already fixed that bug in `tabula-java` (the library that contains the extraction algorithms). It'll be fixed in the Tabula application in the next release cycle (hopefully within the next couple weeks)

Thanks!
