### ISSUE TITLE
Table from PDF that doesn't convert properly

### ISSUE THREAD

**Issue by wooandwowme** [tabulapdf/tabula#704]
This tool is a great idea. Its really appreciated that its free as well.

I'm attempting to extract the table on page 13 of this PDF. It doesn't seem to be seeing the white space between the columns because three of the columns of data get put into the same Excel Column.

I've attached the PDF and a screenshot of the issues in the resulting CSV file.

[62270_1981.pdf](https://github.com/tabulapdf/tabula/files/1133606/62270_1981.pdf)

![screenshot](https://user-images.githubusercontent.com/6112707/27992246-d0c1edaa-64d2-11e7-9b8e-c49680896edc.png)

**Comment by jazzido** [comment]
Hi @wooandwowme,

Try leaving out from the selection the cells that span multiple columns:

![image](https://user-images.githubusercontent.com/27584/28735151-013a61ea-73b2-11e7-83ca-6fed62be21cc.png)

The results look correct:

![image](https://user-images.githubusercontent.com/27584/28735166-0b70917a-73b2-11e7-8a13-39cd223e47b2.png)
