### ISSUE TITLE
Having hard time automating pdf to excel conversion via UiPath RPA tool

### ISSUE THREAD

**Issue by manojkarde** [tabulapdf/tabula#706]
Browse, Import etc buttons doesn't have unique UI-IDs due to which RPA tool is not recognizing these and more buttons

**Comment by jazzido** [comment]
Thanks, @manojkarde.

I'm not familiar with the tool that you mention, but if it allows selecting buttons through CSS, I'm sure there's a way to do it. 

For automating extraction, we also build [tabula-java](http://github.com/tabulapdf/tabula-java), which might be more appropriate for your task.
