### ISSUE TITLE
Tabula just giving me gray boxes after import, with tiny "x" box in left corner

### ISSUE THREAD

**Issue by DCWrider** [tabulapdf/tabula#710]
Hi community, thank you very much for the help! I am trying to extract these rows of data into an .xls using Tabula. When I import the PDF, which I ran through Adobe Acrobat for OCR, it loads but then only provides me grayed-out pages. I Can't drag the selector tool across to select text and have it result in a CSV file.  
I Have no programming experience at all; I'm a reporter trying to build a database of previous Air Force mishaps and the Air Force would not provide me the copy in original PDF form or Excel; just these pages. Any advice you have on how I can get these pages to scrape is deeply appreciated!
Thank you! Tara 

[Part 1 2010 to 2015.pdf](https://github.com/tabulapdf/tabula/files/1200250/Part.1.2010.to.2015.pdf)

**Comment by DCWrider** [comment]
also, one general question for the community - it seems I have to re-launch Tabula through the extracted .exe file I downloaded from the web every time I want to use it - is this the correct way to do it or is there a step I'm missing to have a Tabula program resident on my start bar or desktop? 
Thank you!
Tara

**Comment by jeremybmerrill** [comment]
Hi @DCWrider!

For the second question, nope, you're doing it right. You could put the extracted Exe on your desktop, if you wanted though.

For the first problem, I'm seeing the problem too. There's something wrong with either the PDF or the tool Tabula uses to open PDFs. Manuel is actually in the middle of replacing that tool; so I tried it with two of those tools (the old one and the new one) -- but neither worked right. That makes me suspect your PDF is screwed up somehow, like Adobe OCR did something funny. Sorry I don't have a better answer for you.

**Comment by jazzido** [comment]
Hi @DCWrider,

Just confirmed that your PDF works in the development version of Tabula. We hope to cut a new release in the coming weeks. Thanks for reporting!

![image](https://user-images.githubusercontent.com/27584/28979087-6d23228e-7916-11e7-9f8a-f626a2712312.png)
![image](https://user-images.githubusercontent.com/27584/28979096-74171b4a-7916-11e7-89dc-5a39b01570ca.png)
