### ISSUE TITLE
Some tables' numbers extracted wrong from pdf

### ISSUE THREAD

**Issue by oryahud** [tabulapdf/tabula#714]
**Step to reproduce:**
1. Import the attached problem.pdf file.
2. Extract the tables from it (By auto-detect or manually).
3. Some numbers are wrong.
e.g: Line 6 : 3,797 -> 3,777, 5,317 -> 5,337 and there are some more...

**Tested Tabula:**
1. tabula v1.1.1
2. tabula-java v1.01
command:
java -jar tabula-1.0.1-jar-with-dependencies.jar problem.pdf -o problem.csv
3. tabula-py v1.0.0
command:
read_pdf('problem.pdf')

**Details:**
File: 
[problem.pdf](https://github.com/tabulapdf/tabula/files/1232755/problem.pdf)

OS: Windows 10
Computer languages: English \ Hebrew

**Comment by jeremybmerrill** [comment]
closing in favor of https://github.com/tabulapdf/tabula-java/issues/180; will comment there soon.
