### ISSUE TITLE
CBA Commonwealth Bank statement can't be scraped

### ISSUE THREAD

**Issue by tfsimondouglas** [tabulapdf/tabula#716]
> What error message did you get?

No error message. Output is missing information

> What PDF were you trying to extract data from? Some PDFs are wacky, so seeing the exact PDF will be useful. 

Trying to extract the data from a Commonwealth bank statement that's protected. I noticed in Acrobat and PDFPen that the text could not be OCR'd at all. Hence the use of your tool. 

> What version of Tabula are you using? 

Latest as of 19-08-2017

> What platform are you on? Windows 7 or 8? Mac? Linux? 

Mac 10.12.6 English only

![screenflow](https://user-images.githubusercontent.com/19296923/29485274-84a95bb4-8512-11e7-8e9c-86151eaa48f4.gif)

**Comment by jeremybmerrill** [comment]
Bank statements are notoriously weird and hard to scrape. I can take a look if you upload (or send to my email) an example, but it may be that the PDF is generated in such a weird way, it can't be scraped.

**Comment by jazzido** [comment]
Ditto. @tfsimondouglas, if you're comfortable with emailing us the original PDF, we would be happy to take a look.
