### ISSUE TITLE
webout not like cvs

### ISSUE THREAD

**Issue by u2funker** [tabulapdf/tabula#721]
![image](https://user-images.githubusercontent.com/10113114/29713014-f4b45740-899c-11e7-9e46-d5bb4d82e408.png)

Hi,
the wesite output is perfect (see above), but the cvs output look not like this see below.
any Ideas?
Kind regards
Michael

![image](https://user-images.githubusercontent.com/10113114/29713081-4f835c7a-899d-11e7-96f2-549770b006ef.png)

**Comment by jeremybmerrill** [comment]
Hi Michael,

I think this is an issue with how Excel opened the output. It looks like the commas are in the right place in the Excel screenshot, except Excel didn't know to put column boundaries there. You might try using Excel's Import function to force it to recognize the CSV correctly.
