### ISSUE TITLE
Additional unnecessary rows in spreadsheet

### ISSUE THREAD

**Issue by manojkarde** [tabulapdf/tabula#729]
I am using command line option to extract table data from PDF to CSV format. 

java -jar tabula-1.0.1-jar-with-dependencies.jar -p all -g -l -o D:\bank.csv d:\bank.pdf

Table starts at about 14th line within PDF. Table data is coming all fine in the CSV file but getting about 13 odd lines in the CSV which are blank at the start of CSV file and then followed by real needed table data.

How do I work around to get rid of these additional 13 blank rows?

Thanks
Manoj
[Bank.pdf](https://github.com/tabulapdf/tabula/files/1321608/Bank.pdf)

[Bank.xlsx](https://github.com/tabulapdf/tabula/files/1321622/Bank.xlsx)

**Comment by jazzido** [comment]
Hi @manojkarde,

It's likely that the table detection algorithm is taking some spurious lines as part of a table. I'd recommend that you post-process the CSV output with a script or a command line tool such as `grep` to filter out empty rows.

Thanks for your report!
