### ISSUE TITLE
How hard is to modify tabula so that it can detect merge cells?

### ISSUE THREAD

**Issue by SparkyCola** [tabulapdf/tabula#731]
Hi, I have a document, a schedule which I'll get every semester so it's worth it for me to put some effort to turn this into an csv or similar. tabula seems to detect the table pretty well, but has some issue with the merged cells, like in #600, to get a better idea of what I want to do is my PDF:
[1.Sem_Mech-3.pdf](https://github.com/tabulapdf/tabula/files/1322420/1.Sem_Mech-3.pdf)

I tried to achieve the same with python and pdfminer.six which generates an xml that can be parsed, not too easily though because I need to analyse everything and the hard part is to find all the boundaries of the text. However pdfminer seems to be capable of detecting the position of stuff which would be cool since it allows me to separate all entries like rooms, prof, ... in one cell but not necessary.

**Comment by jazzido** [comment]
Hi @SparkyCola,

[tabula-java](http://github.com/tabulapdf/tabula-java) is better suited for custom processing. [pdfplumber](https://github.com/jsvine/pdfplumber), a project inspired by Tabula, is also worth a look.

**Comment by lycanthropes** [comment]
Can you do it now ? I also meet the same problem.
