### ISSUE TITLE
Issues in extraciting multiple tables

### ISSUE THREAD

**Issue by anilnaik1988** [tabulapdf/tabula#738]
While i am trying to extract multiple tables from pdf using below command:-
convert_into("mypdf.pdf","outputables.csv",pages="all",multiple_tables="true",output_format="csv".
I am getting multiple tables but no delimiters are there in between the extracted tables. I would rather suggest to have some delimiters between tables in order to identify bw tables. Or is it my mistake in extracting tables.

**Comment by jeremybmerrill** [comment]
It looks like you're probably using the tabula-py software in Python, rather than the Tabula GUI. Please raise support issues for that library in it's repo: https://github.com/chezou/tabula-py/issues
