### ISSUE TITLE
Open Collective is a pain

### ISSUE THREAD

**Issue by sdangt** [tabulapdf/tabula#743]
I tried to make a donation to Tabula awhile back, and wound up getting subscribed by Open Collective to monthly donations.  I complained about it and fixed it, but they continued to send me marketing emails.

This is **totally inappropriate**.  I don't care about Open Collective.  I was trying to make a one-time donation to a totally different project.  I've had more problems with Open Collective than I have with Tabula.  Their latest email update brags about "Open Collective V2", which features like:

- "Custom tiers: set up all kinds of sponsorship levels, backer rewards, special campaigns, or other creative ideas."

- "Improved donation interface: see contribution amounts and frequency more clearly."

Etc.

I'm not even subscribed to updates about Tabula itself.  I've unsubscribed now, again, which hopefully will work, but I shouldn't have had to unsubscribe to Open Collective twice -- once from monthly donations billed automatically, and once from email marketing about a product that I never expressed any interest in.

Dan

**Comment by jazzido** [comment]
Hey @sdangt,

Sorry to hear about your issues with Open Collective. I just forwarded your message to them.

**Comment by piamancini** [comment]
hey @sdangt sorry it was a bad experience. The subscription to Tabula was canceled at the time and, as we responded on our email, your won't receive our newsletter anymore. 
Cheers
