### ISSUE TITLE
This doesn't work for IRS Form 990s...

### ISSUE THREAD

**Issue by snigdhasur** [tabulapdf/tabula#758]
Hi Tabula team!

I just tried using this for a PDF of a 990 and thought the file was processed, I then couldn't extract the data (the preview was blank). Any thoughts on what I might be doing wrong?

Thank you!

[13-5562185_990_201508.pdf](https://github.com/tabulapdf/tabula/files/1447864/13-5562185_990_201508.pdf)

**Comment by jeremybmerrill** [comment]
Hi @snigdhasur, I think that PDF has been scanned, so there's no text data for Tabula to extract.

Conveniently, ProPublica has digitized information for 2015 990 forms, including for that organization: https://projects.propublica.org/nonprofits/organizations/135562185

**Comment by snigdhasur** [comment]
Thank you so much!!

**Comment by thesilentpsycho** [comment]
Hi @jeremybmerrill,
It is unable to extract any data for the below pdf as well:-
http://www.bseindia.com/bseplus/AnnualReport/500570/5005700317.pdf

The pdf clearly has lots of tables. I am able to select data from the tables and paste in excel manually. Please help. Are there any options that I must provide while reading using read_pdf method.

Following is screenshot of the same:
![image](https://user-images.githubusercontent.com/13063226/32690278-5b9c5f6a-c71a-11e7-8950-5f5856d58114.png)
