### ISSUE TITLE
Facing difficulty in extracting unruled tables

### ISSUE THREAD

**Issue by arpit-gbpec** [tabulapdf/tabula#763]
[abc.pdf](https://github.com/tabulapdf/tabula/files/1486825/abc.pdf)

I am working with this Tabula Api.I am writing the code in java to extract the tables from any pdf using this API.I tried my code on several files. But I am only able to extract tables from a file,that has ruled tables.I tried using both SpreadsheetExtractionAlgorithm and BasicExtractionAlgorithm,but none of them produced the desired results.I am sharing a sample pdf file in which I am unable to detect the tables,and the source code I have written in Java to extract the tables(the file is in txt format as it cannot be submitted here in Java).
[TableConverter.txt](https://github.com/tabulapdf/tabula/files/1486847/TableConverter.txt)
@

**Comment by jeremybmerrill** [comment]
Hi @arpit-gbpec: Tabula cannot automatically detect the locations of tables without ruling lines. You'll have to provide their locations as coordinates.

**Comment by jazzido** [comment]
@arpit-gbpec, take a look at [`NurminenDetectionAlgorithm`](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/detectors/NurminenDetectionAlgorithm.java). It implements the same interface as `SpreadsheetDetectionAlgoritm`, so it should be an easy change.

It is pretty accurate in detecting tables *without* ruling lines.

**Comment by jazzido** [comment]
Here's an example of a table without ruling lines detected by Tabula:

![us-002-1](https://user-images.githubusercontent.com/27584/33096979-84a2688a-cee7-11e7-9e7a-d49d827faa58.jpg)

**Comment by jeremybmerrill** [comment]
@jazzido ... that's news to me. Are there (invisible) lines around that table?

**Comment by jazzido** [comment]
There are top and bottom delimiters

![image](https://user-images.githubusercontent.com/27584/33097883-4b3e38e6-ceea-11e7-8f69-445f9df5595e.png)

**Comment by arpit-gbpec** [comment]
@jazzido  Thanks for the response.But the thing is I have already tried using NurminenDetectionAlgorithm. This algorithm only detects the rectangles and returns the rectangles,but my problem here is that I need to Extract the "tables" from my pdf.

So,I mean to ask you that is there any way to extract tables using these rectangles, or if anyhow Can I create multiple Pages from a single page ,wherever I find a rectangle??
