### ISSUE TITLE
Problem with accent letters and specials

### ISSUE THREAD

**Issue by asturnauta** [tabulapdf/tabula#764]
Hi

I have tried tabula and works great. I could uploar a pdf file and detects the whole table, but at the moment to export and import in excel, i have  a problem with special spanish letters like 'á, 'é', 'í', 'ó', 'ú' and 'ñ'

These special letters appears in excel like 'Ã', 'Ã“', 'Ã‰', and other similar combinations.

Is this a problem of tabula or the csv import in excel?.

thanks.

**Comment by jeremybmerrill** [comment]
Hi @asturnauta: This is mostly likely an Excel problem. I assume you're on Windows? You'll have to tell Excel specifically to open the CSV with UTF-8 encoding. Here's a guide for Excel 2007, you may have to find a different one for your version of Excel: https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0
