### ISSUE TITLE
Agradecimientos

### ISSUE THREAD

**Issue by emurillou** [tabulapdf/tabula#765]
buenas tardes 
muchas gracias por liberar esta herramienta para usarla libremente sin animo de lucro.
la uso constantemente para convertir extractos bancarios en archivos de excel manipulables.
de nuevo muchas gracias por este gran aporte

**Comment by jeremybmerrill** [comment]
Estoy feliz de oir que Tabula le ha ayudado!

**Comment by jazzido** [comment]
Muchas gracias, Esteban! Nos alegra mucho que nuestro trabajo te resulte de utilidad.

**Comment by emurillou** [comment]
muchas gracias por su dedicación 
y capacidad de hacer comunidad con este excelente proyecto
cordial saludo
