### ISSUE TITLE
lazyloading should lazily-unload pages as you scroll down

### ISSUE THREAD

**Issue by ftrotter** [tabulapdf/tabula#774]
I am testing tabula on pdfs that are several hundred pages long. 

When I scroll down, there is an "autofill" effect that adds pages to the web view as a scroll down. Which is amazing for dynamically loading 20 pages. But as you get into the hundreds of pages, the ability to scroll down gets harder and harder. The existing pages push the scroll bar to the bottom of the page, and after a while it is a bother to try and see new pages, because you have only a few centimeters to scroll. 

Its pretty easy to see the effect with very large pdfs. 

Thanks for the awesome project!

-FT

**Comment by jeremybmerrill** [comment]
Hey @ftrotter! While I'd like to adjust the lazyloading of pages to lazily unload pages at the top, I don't see myself having time to write it anytime soon. Probably your best option would be to split the PDF with another tool (Acrobat, pdftk, many tools can do it) and then load the pages you want into Tabula.

**Comment by ftrotter** [comment]
Thanks!!
