### ISSUE TITLE
error Comparison method violates its general contract!

### ISSUE THREAD

**Issue by velotechnique** [tabulapdf/tabula#778]
Messieurs
Il apparaît une erreur lorsque j'utilise tabula sur ce document pdf en mode Lattice
par contre il n'y a pas d'erreur en mode Stream ni en mode Autodetect/Lattice
Regards

url : 
(deleted http://127.0.0.1:8080/pdf/24042dcdc2608ead0238ced5eb2afd9c69cc2d2b deleted)
i reloaded the data and get the same error
http://127.0.0.1:8080/pdf/91f55fad540d4cdc9e28d4321451273f215834b4

message :
Tabula API version: 1.1.1.17021116
Filename: n2m20152016.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/24042dcdc2608ead0238ced5eb2afd9c69cc2d2b/data

Comparison method violates its general contract!

**Comment by velotechnique** [comment]
i reloaded the data and get the same error
http://127.0.0.1:8080/pdf/91f55fad540d4cdc9e28d4321451273f215834b4

**Comment by jeremybmerrill** [comment]
@velotechnique This is a known issue, see https://github.com/tabulapdf/tabula-java/issues/116 and https://github.com/tabulapdf/tabula-java/issues/81 and #546, et al. We'll have this fixed in the next release.
