### ISSUE TITLE
bug. the CSV does not support UTF-8

### ISSUE THREAD

**Issue by bendy101** [tabulapdf/tabula#782]
no good for German special characters...

**Comment by jeremybmerrill** [comment]
Hello @bendy101: This is mostly likely an Excel problem. I assume you're on Windows? You'll have to tell Excel specifically to open the CSV with UTF-8 encoding. Here's a guide for Excel 2007, you may have to find a different one for your version of Excel: https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0
