### ISSUE TITLE
Tabula fails to recognize columns when one outer line is missing

### ISSUE THREAD

**Issue by gcgruen** [tabulapdf/tabula#786]
Not sure whether this is a bug something can be done about: When trying to extract data from a [pdf like this](http://frontex.europa.eu/assets/About_Frontex/Governance_documents/Grants_awarded/Grants_awarded_in_2016.pdf), the columns on the very left and the very right both are lost in extraction. I assume because boundaries to three sides of the cell aren't enough, but it needs the fourth to recognize it as part of the table? Is that something that could be fixed or is there a work-around? FYI: I did the extraction with the "Lattice" method instead of "Stream" (which totally blew up the layout), however the problem occurs irrespective of which of the methods I use.

**Comment by jeremybmerrill** [comment]
Hi @gcgruen Thank you for reporting this. It's a known shortcoming of the current implementation of the Lattice method.
