### ISSUE TITLE
Can't extract tables that have vertical orientation

### ISSUE THREAD

**Issue by agapdx** [tabulapdf/tabula#790]
Some pdf's have tables that are in vertical orientation (rotated). Tabula is not able to extract these tables. Is there a defect for this issue or can this be added as a new feature?

**Comment by jazzido** [comment]
Hi.

This is not a defect, Tabula doesn't yet support extracting tables from rotated pages. Many PDF viewers, such as Preview in macOS, support rotating and re-saving the document. After doing that, re-upload the file to Tabula and it should work.

**Comment by agapdx** [comment]
I want to programatically extract tables form 100's of pdf documents. Manually changing rotation is not a good option. This is a common case and I see many other folks have requested this feature. Can you add this to the backlog?

**Comment by jazzido** [comment]
Yes, it is far from ideal. We can add it to the backlog for sure, but I don't know if it's ever going to be implemented. Tabula is made in our very little spare time.

You're more than welcome to hire a developer and, if desired, contribute the feature as a pull-request.

Thanks.
