### ISSUE TITLE
PDF has tables rotated counterclockwise

### ISSUE THREAD

**Issue by theoakahn** [tabulapdf/tabula#791]
Hello - this seems like a pretty simple problem, but I could not figure out how to resolve it. The PDF I am working with has tables that are rotated counter-clockwise, and I could not see an option to rotate the page within tabula. I tried rotating the PDF and then saving and uploading, but that did not work. Thank you in advance.

Theo

**Comment by jeremybmerrill** [comment]
Rotating PDF pages is a capability that is common to many PDF viewing and editing programs like Adobe Reader, Mac Preview, Evince and `pdftk`; we recommend that you rotate your PDF in one of those programs first, save it, then upload it to Tabula for extraction.

Tabula is made in our spare time, so the Tabula development team focuses on features that are unique to Tabula's use case -- extracting tabular data from PDFs. . We would likely accept a pull request that added this feature to Tabula, but we're not likely to build it ourselves.
