### ISSUE TITLE
Bad percent extraction

### ISSUE THREAD

**Issue by sadfuzzy** [tabulapdf/tabula#794]
What I have
![2018-02-18_10-29-04](https://user-images.githubusercontent.com/158883/36349391-dfd4032c-1496-11e8-997d-94072953b43c.png)
The selection
![2018-02-18_10-29-47](https://user-images.githubusercontent.com/158883/36349390-dfb926d8-1496-11e8-8fe6-dc49cddbc51f.png)
The result
![2018-02-18_10-30-01](https://user-images.githubusercontent.com/158883/36349389-df9c59ea-1496-11e8-8b7a-953d68aedb81.png)

For some reason, percent numbers are glued to left column. Is there a way to separate them?

**Comment by jazzido** [comment]
Hi @sadfuzzy,

That's a known property of the _Stream_ extraction mode. Try excluding from the selection the header row at the top of the table.

Thanks!
