### ISSUE TITLE
Convert Marathi language PFD to excel which can have images too

### ISSUE THREAD

**Issue by dineshjain14** [tabulapdf/tabula#796]
Hi team,

I am looking help to convert Marathi language PFD to excel which can have images too.

Thanks,
Dinesh Jain

**Comment by jeremybmerrill** [comment]
Tabula should be able to handle Marathi text -- if the text is embedded in the PDF. If the text is in an image, you'll have to figure out how to use OCR ("Optical Character Recognition") to reconstruct the text. I do not know if there are OCR programs for Marathi.
