### ISSUE TITLE
combine values with line breaks before exporting

### ISSUE THREAD

**Issue by ontrak** [tabulapdf/tabula#804]
many pdf tables have attribute with multi line values (line wrap) to fit into a specific format. at least allow manual fix of these in preview before exporting

**Comment by jeremybmerrill** [comment]
Hi @ontrak: If your table has ruling lines around cells, the Lattice extraction mode will do as you describe. If your table does not have ruling lines, we don't know how to create the feature you describe: the algorithms by which various PDF export programs wrap text (like addresses) into multiple lines are completely unpredictable and vary widely, so we know of no way that would work across all/most PDFs.
