### ISSUE TITLE
Single-object extraction: possible with Tabula-UI, fails with Tabula-CLI

### ISSUE THREAD

**Issue by Eisit** [tabulapdf/tabula#808]
I am trying to batch extract several fields from  laboratory reports PDFs (to csv). Some fields are tables - no problem, Tabula works fine - but some are one single "cell", e.g. the date written in a corner of the report page, or the name of the lab assistant.

Everything works perfectly with Tabula UI on a single PDF: I select manually the areas I want to extract, and get in return both tables and the date/name/whatever. From there, I export the _script_, and I use the coordinates of the areas to script the batch extraction with the appropriate command line argument. The batch work extracts the tables but not the "single-cell". No error message, just nothing.

I tried again, one area at a time: only those single-cells fail to be extracted. I only get an empty csv.

[Sorry in advance if the issue is already known. I couldn't find good search terms to find if somebody has already opened a similar issue.]

**Comment by jeremybmerrill** [comment]
Hi @Eisit, can you please reopen this bug at https://github.com/tabulapdf/tabula-java/issues? That's the proper forum for CLI issues. Can you also please include the PDF and at least one of the malfunctioning "script" outputs so we can see if we can duplicate your bug?

**Comment by Eisit** [comment]
I will do that, thanks. Sorry for choosing the wrong forum.
