### ISSUE TITLE
Unable to extract after applying templates

### ISSUE THREAD

**Issue by Mkline4** [tabulapdf/tabula#810]
I love the idea of templates.  It worked for the first 3 files and then stopped.  I can apply the template, but when I got to "Preview & Export Data" nothing happens.  If I auto-detect or select new area it will let me Extract the data.  Any thoughts as to what my issue may be?

**Comment by jeremybmerrill** [comment]
Hi @Mkline4 and @ajm348: I think you all have found a bug. This makes sense. I'll try to take a stab at reproducing and, hopefully, fixing this bug shortly.

@Mkline4: Is your situation the same, where the template has more "pages" than the PDF does?

**Comment by Mkline4** [comment]
Yes it is.  Thank you for your help.

**Comment by jeremybmerrill** [comment]
I've fixed this here: https://github.com/tabulapdf/tabula/commit/8dcf7d496ce3959a4e44cb059d20d34d89285cf8

The fix will be released in the next release. Until then, either build from source or, as a workaround, only attempt to load templates that have the same (or fewer) number of pages as the target PDFs.

**Comment by ajm348** [comment]
Thanks a ton Jeremy! I really appreciate it.
