### ISSUE TITLE
pdf with sideways tables has text cut-off

### ISSUE THREAD

**Issue by melissakey** [tabulapdf/tabula#811]
I'm interested in table 2 of the attached document.  It's sideways, and covers multiple pages - so it's not an easy table to capture.  Copy/paste into Excel creates too many entries (it sees all breaks as spaces)- so this is one that needs to be entered cell-by-cell, or using a tool like tabula.  I did not get errors, but I did not get the desired output either.
Page 1: Columns 1 and 2 worked beautifully, but column 3 was truncated.
Page 2: Column 1 was truncated from the left, and column 3 was truncated from the right.  (Column 2 did work though)

The paper is available at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3066620/pdf/z7g4921.pdf, if the file did not upload correctly. 
Thanks!

[Chowdhury et al. - 2010 - Proteome analysis of human aqueous humor.pdf](https://github.com/tabulapdf/tabula/files/1776615/Chowdhury.et.al.-.2010.-.Proteome.analysis.of.human.aqueous.humor.pdf)

**Comment by jazzido** [comment]
Hi @melissakey,

Rotating PDF pages is a capability that is common to many PDF viewing and editing programs like Adobe Reader, Mac Preview, Evince and pdftk; we recommend that you rotate your PDF in one of those programs first, save it, then upload it to Tabula for extraction.

Thanks!
