### ISSUE TITLE
Fails to Split Two Columns

### ISSUE THREAD

**Issue by darianhickman** [tabulapdf/tabula#815]
PDF of Zynga Financial Results
Input: https://drive.google.com/file/d/1qny64fjcCfCrnskXCc8sKtK6wszdVtMx/view?usp=sharing
Exports but doesn't correctly separate columns 2016, and 2015:
Output: https://drive.google.com/file/d/1SeGbnjDyxSj0l89lzzy3EhH4t4qgiRap/view?usp=sharing

**Comment by darianhickman** [comment]
This is an excellent tool, btw.  I commend the localhost web interface and I wish more on-premise software projects make this choice.

**Comment by jazzido** [comment]
Hi @darianhickman.

Thanks for reporting this issue. This is a known behavior of the _Stream_ extraction method. Try leaving the headers that span multiple columns out of the selection:

![image](https://user-images.githubusercontent.com/27584/37293643-ad845ac6-25f2-11e8-955c-0ef67e925823.png)

You'll need to add manually the year headers, but that shouldn't be much of a hassle.
