### ISSUE TITLE
plain text tables not converting

### ISSUE THREAD

**Issue by aliabbasjp** [tabulapdf/tabula#817]
I wanted to convert the following very tough text PDF tables to CSV but tabula is unable to separate the cells in proper columns neither in stream nor cell mode:

Round 1 http://www.dmer.org/new/PGM-SelList-R1%20-%2005.05.2017.pdf
On closer inspection it looks like a MS word file!
Round 2
Day 1 http://www.dmer.org/new/SelList%20-%2022052017.pdf
Day 2 http://www.dmer.org/new/SelList%20-%2023052017.pdf
Day 3 http://www.dmer.org/new/SelList%20-%2024052017.pdf (MGIMS Joins Here, Aberrent college  Plz color separately).
Day 4 http://www.dmer.org/new/SelList%20-%2025052017.pdf
Day 5 http://www.dmer.org/new/SelList%20-%2026052017.pdf
Day 6 http://www.dmer.org/new/SelList%20-%2027052017.pdf

Round 2.01
Day 1 http://www.dmer.org/new/SelList%20-%2027052017.pdf

If possible, color code/separate column to indicate Round of final selection

All links taken from http://www.dmer.org/new/pgmcet2016.htm

**Comment by jazzido** [comment]
Hi @aliabbasjp,

Thanks for your report. It seems that the latest version of Tabula is able to extract _some_ of the structure of those tables: 

![image](https://user-images.githubusercontent.com/27584/37293360-ccd5da7c-25f1-11e8-90e9-0a716bf5cdb5.png)

Unfortunately, there are no visual separators between columns, so it won't be possible to recognize all of them correctly.
