### ISSUE TITLE
Tabula adding a space between first and second characters in a field.

### ISSUE THREAD

**Issue by fishpatrol** [tabulapdf/tabula#818]
When extracting tables from a contract PDF, Tabula is adding a space between first and second characters in a field. So a cell that reads "16687" in the table is extracted as "1 6687." 

The table has 8 columns, and this doesn't occur in every column. Affected columns include a column of company names, company addresses, and zip codes, so it affects columns with only numbers, only letters, and a mix of both. 

Also, in a column where a space is being added, it isn't added in every row. For example, facility names that begin with M are not followed by a space, but names that begin with A, H, and T consistently are. When I open the PDF in Acrobat Pro and copy and paste an affected cell into Excel, it pastes in without an added space.

I have tried expanding the selection size, with the same result. I deleted other pages of the PDF so that only the pages includes tables remained with the same result. Unfortunately I am not able to share the PDF.

I'm running Tabula 1.2.0 on a Windows 7 computer, English language. 

In Excel I can correct this programmatically, but I'd rather avoid the added step of running the entire table through a formula like this (which would mistakenly edit an address line with a single-digit street number): ``=IF(MID(A2,2,1)=" ",CONCATENATE(LEFT(A2,1),MID(A2,3,100)),A2)``

**Comment by jazzido** [comment]
Thanks @fishpatrol.

This one is pretty hard. PDF files contains only characters and their position on the page. On top of that, most PDFs don't include any _space_ character. So it's up to us to merge them back into words and lines, and to add spaces. We do that heuristically, by calculating the separation between characters.

Some fonts have really weird kerning values, and that throws off our heuristics.

In any case, I'm glad that you can post-process the result.
