### ISSUE TITLE
extracting AF tables from stm32 datasheets

### ISSUE THREAD

**Issue by tridge** [tabulapdf/tabula#820]
The ArduPilot project is using tabula to extract microprocessor tables from stm32 datasheets so we can more easily port to new boards.
We hit problems with some of the PDFs. I attach an example of the STM32F413xG datasheet, which gets the PA0 row alignment wrong for the first row of the first table. We are using the lattice method, then extracting to csv. We then process the csv with python scripts to generate the processor databases we use in the board ports.
We're using the 1.2.0 version of tabula.
Many thanks for a very useful tool!
[AF-F413xG.pdf](https://github.com/tabulapdf/tabula/files/1808726/AF-F413xG.pdf)
![pa0-alignment](https://user-images.githubusercontent.com/831867/37371168-a216be56-2762-11e8-84f3-d3d9e1d07d40.png)

**Comment by magicrub** [comment]
The problem is the upper left corner of the table is not like the others. It's double wide which causes the first two rows to be shifted.
![image](https://user-images.githubusercontent.com/4782875/37373059-350fabb4-26d2-11e8-9e86-a7aa2d50839f.png)

**Comment by jazzido** [comment]
thanks for reporting, @tridge.

Exactly what @magicrub says. Try leaving out "non-regular" sections of a table out. This selection: 
![image](https://user-images.githubusercontent.com/27584/37404334-5408c228-2770-11e8-8d29-4bf3297a1fef.png)

…seems to work well. You'll have to add the first column (_PA0_…) manually, but it's doable.
