### ISSUE TITLE
Could not extract tables

### ISSUE THREAD

**Issue by romainecarter** [tabulapdf/tabula#822]
Uploaded pdf document and tried to do an autodetect which did not work, I also tried manual selecting the tables and switching between the read modes; none of which produced a result

[JMMB-Group-Limited-Unaudited-Financial-Statement-for-the-period-ended-31-December-2017-1.pdf](https://github.com/tabulapdf/tabula/files/1840108/JMMB-Group-Limited-Unaudited-Financial-Statement-for-the-period-ended-31-December-2017-1.pdf)

**Comment by jazzido** [comment]
Hi @romainecarter,

Thanks for reporting this issue. Unfortunately, the tables on that document are _images_. Tabula only works with character-data.
