### ISSUE TITLE
Issues with converting vertical text

### ISSUE THREAD

**Issue by anijatsu** [tabulapdf/tabula#827]
Windows 8.1, Tabula 1.2.0
[PDF in question](http://kfc.pl/assets/uploads/KFC_Wartosci_Odzywcze_Alergeny.pdf)
![Screenshot of the upper portion of the result](https://user-images.githubusercontent.com/1882015/38139711-eedb9aa6-3430-11e8-91e8-acb5dc462e26.png)

**Comment by jeremybmerrill** [comment]
Vertical text is not considered in scope for Tabula at the moment.
