### ISSUE TITLE
Lattice option not working

### ISSUE THREAD

**Issue by phillipederer** [tabulapdf/tabula#829]
First time user

RE attached file.  The Stream mode works very well for the first column, the second up to the first space and then predictably sets each word into its own column. But when I click "Lattice" I get "no data".  
[ddual 1249 manual (pdf.io).pdf](https://github.com/tabulapdf/tabula/files/1865569/ddual.1249.manual.pdf.io.pdf)

I do not know what you call highlighting each column separately is called but that works no better and again I cannot use the Lattice mode.  Thanks in advance.

**Comment by jeremybmerrill** [comment]
Lattice mode only works on tables with ruling lines on all sides; your PDF doesn't appear to have these, so it's expected that Lattice won't work.
