### ISSUE TITLE
merging rows

### ISSUE THREAD

**Issue by blacksmithapplications** [tabulapdf/tabula#830]
Hi,

We use Docparser's table grid for parsing an invoice.  Docparser uses tabula.pdf for its table grid.

We are seeing many examples where two rows are getting merged inadvertently.   The conditions are pretty similar in all cases.  If the last row was partially filled out, started from the middle of the page to the end of the page, it is getting merged with the row above.

It does not happen when I parse the file with spaces as separators.  Only when table grid is used, the merging happens.

It does not matter where I place the column boundaries.

See attached examples of PDF and their subsequent row formation in Docparser using tabula.pdf.  I have attached three PDFs as well.

[GFS- VR0207801- $1,712.44.pdf](https://github.com/tabulapdf/tabula/files/1872420/GFS-.VR0207801-.1.712.44.pdf)

[Unilever GFS Montreal_5188213_9011 08_ART.pdf](https://github.com/tabulapdf/tabula/files/1872421/Unilever.GFS.Montreal_5188213_9011.08_ART.pdf)

[Cash_Wa_Invoice100280_np.pdf](https://github.com/tabulapdf/tabula/files/1872422/Cash_Wa_Invoice100280_np.pdf)

Let me know what else can I provide.
![page_2_gfs-_vr0207801-_ 1 712 44](https://user-images.githubusercontent.com/38046569/38261801-5080fbce-3739-11e8-98ab-cca92099bd88.png)
![page_4_gfs-_vr0207801-_ 1 712 44_001](https://user-images.githubusercontent.com/38046569/38261802-509170d0-3739-11e8-9b66-3099c2bb4e16.png)
![page_7_unilever_gfs_montreal_5188213_9011_08_art](https://user-images.githubusercontent.com/38046569/38261803-50a184ca-3739-11e8-8aeb-11dc1737daf9.png)
![page_4_unilever_gfs_montreal_5188213_9011_08_art](https://user-images.githubusercontent.com/38046569/38261804-50affef6-3739-11e8-85c6-10d59779ae26.png)
![docparser_merging_two_rows_pfg_ot8](https://user-images.githubusercontent.com/38046569/38261484-523f3440-3738-11e8-808f-687fc3271269.png)

**Comment by blacksmithapplications** [comment]
Any updates?

**Comment by jeremybmerrill** [comment]
We don't maintain Docparser. Please either submit your issue to Docparser and see if they think it's a Tabula bug or not, or test your document in Tabula and see if the issue appears there.
