### ISSUE TITLE
Merging of two rows

### ISSUE THREAD

**Issue by blacksmithapplications** [tabulapdf/tabula#832]
Hi,

Tabula merges two rows.

See attached PDF and merged row formation in Tabula

Cash_Wa_Invoice100280_np.pdf
![tabula_merges_two_rows](https://user-images.githubusercontent.com/38046569/38380033-8d672cfa-38d0-11e8-8cad-c476ecdc3725.png)
[Cash_Wa_Invoice100280_np.pdf](https://github.com/tabulapdf/tabula/files/1880953/Cash_Wa_Invoice100280_np.pdf)

I can attach more examples.

**Comment by blacksmithapplications** [comment]
Any updates?

**Comment by jeremybmerrill** [comment]
First off, this is a volunteer run project. I answer support tickets in my spare time, as a favor to the community, so please be patient. 

Tabula relies on you to draw the correct boundaries around the table; it's not magic. The boundaries you've drawn include stuff outside the table -- like the "Powered by Trackm" thing and the "This invoice is due..." bit. Exclude those from the selection and you'll get better results. You're essentially asking Tabula to fit a tabular structure to non-tabular data (i.e. the random stuff on the margins of the page), so you shouldn't be surprised when Tabula's answer to your unanswerable question is not right.

**Comment by blacksmithapplications** [comment]
Thank you, Jeremy for the insights.
