### ISSUE TITLE
Lack of row boundaries: cell spanning multiple rows split into multiple rows

### ISSUE THREAD

**Issue by gopalpeddinti** [tabulapdf/tabula#837]
I am extracting table 1 from https://onlinelibrary.wiley.com/doi/full/10.1111/1751-7915.12421.

The table contains multiple rows, but without row boundaries. The "stream" mode is correctly extracting the columns, but not the rows. The resulting table contains as many rows as there are text lines, meaning that cells that span across two lines of text get split into multiple rows in the tabular output. Thanks for the great tool by the way.

**Comment by jeremybmerrill** [comment]
Hi @gopalpeddinti: Unfortunately, this is somewhere between a known issue and intended behavior. For tables like yours without row boundaries, we don't know of a way to extract multiline cell content in the general case.
