### ISSUE TITLE
Trouble with Alternating Colored Rows

### ISSUE THREAD

**Issue by adrennhoff** [tabulapdf/tabula#839]
Hi, I'm trying to use Tabula to extract the data from several reports made by FilmLA. You can find a link to one of the reports here: https://www.filmla.com/wp-content/uploads/2017/10/2015_film_study_v4_WEB.pdf

The tables of interest are in the Appendix (pages 23-25). You'll notice that the table alternates white row - dark row. I imagine this contrast is intended to make it easier for people to read across a row. In any case, Tabula works great on pulling the information for the white rows but NOT the dark rows.

**Comment by adrennhoff** [comment]
Here's the Appendix I'm interested in...

[short_2015.pdf](https://github.com/tabulapdf/tabula/files/1938514/short_2015.pdf)

**Comment by jazzido** [comment]
Thanks @adrennhoff 

The _Stream_ extraction mode seems to work well your table. Please make sure that you select it (it's located at the left hand side of the screen)

![image](https://user-images.githubusercontent.com/27584/39141858-5493de40-46ff-11e8-823d-c335abf418c4.png)

**Comment by jazzido** [comment]
Unfortunately those are limitations of the table extraction algorithm, and the particular features of this document.
