### ISSUE TITLE
Use LetsEncrypt for domain requests or do not use a domain.

### ISSUE THREAD

**Issue by FlorianSteenbuck** [tabulapdf/tabula#840]
Nobody likes wrong certs please use a valid one. You can use lima-city.de (free or 2€/month Premium if you want to upload releases) or some own server, with a LetsEncrypt cert. Thats also how the club mate shop solve its problems with their cert.

Firefox Output:
tabula.technology uses an invalid security certificate.
The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

ISP:
Vodafone (Hotspot)

**Comment by jeremybmerrill** [comment]
Hi @FlorianSteenbuck 

Thank you for pointing this out... You're right that we don't have a certificate on here. We probably should. (Though I suppose I should note that the downloads are via Github.com, which does have HTTPS and a valid cert.) @mtigas @jazzido which of you guys has the DNS for tabula.technology?

**Comment by jeremybmerrill** [comment]
Aha, it appears that [Github has just made this way easier](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)... Thanks Github!

It looks like [we need to change the A record](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) that points to Github from the name server... https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by jeremybmerrill** [comment]
Done! Thanks @FlorianSteenbuck 

<img width="447" alt="screenshot 2018-05-03 17 27 08" src="https://user-images.githubusercontent.com/548250/39603697-5bb6a2b6-4ef7-11e8-9997-f249f636c2d0.png">
