### ISSUE TITLE
Issue regarding vertical tables

### ISSUE THREAD

**Issue by mvtej** [tabulapdf/tabula#858]
Getting some random data as output when the table is flipped 90 degrees CW or ACW in the given PDF.

**Comment by jeremybmerrill** [comment]
Rotating PDF pages is a capability that is common to many PDF viewing and editing programs like Adobe Reader, Mac Preview, Evince and `pdftk`; we recommend that you rotate your PDF in one of those programs first, then upload it to Tabula for extraction.

Tabula is made in our spare time, so the Tabula development team focuses on features that are unique to Tabula's use case -- extracting tabular data from PDFs. . We would likely accept a pull request that added this feature to Tabula, but we're not likely to build it ourselves.
