### ISSUE TITLE
trying to fill out fields of spread sheet with extracted data from pdf

### ISSUE THREAD

**Issue by az360ct** [tabulapdf/tabula#862]
[Tow Ticket (4).pdf](https://github.com/tabulapdf/tabula/files/2034109/Tow.Ticket.4.pdf)
thats the pdf

[paperless statement.xlsx](https://github.com/tabulapdf/tabula/files/2034117/paperless.statement.xlsx)
 here is the spread sheet

**Comment by jeremybmerrill** [comment]
Hi @az360ct, I don't understand what you're asking. Can you please describe your question in greater depth?

**Comment by az360ct** [comment]
i dont know how to use the program to move information from there
respective fields on the pdf invoice to the proper fields on the
spreadsheet template

On Mon, May 28, 2018 at 9:59 PM, Jeremy B. Merrill <notifications@github.com

**Comment by jeremybmerrill** [comment]
Hi @az360ct: Tabula only extracts the data into a spreadsheet for you. It is not in scope for the project to place it into another spreadsheet's template (though you could likely accomplish this wish some Excel scripting that pastes, for instance, cell A1 of the Tabula output into the relevant cell of the template).

**Comment by az360ct** [comment]
thats what i was thinking, will tabula batch all the pdf i have in a folder
according to template i have saved into one spread sheet or multiple


On Tue, May 29, 2018 at 3:20 PM, Jeremy B. Merrill <notifications@github.com

**Comment by az360ct** [comment]
is there a way to clean up the data from tabula output

**Comment by jeremybmerrill** [comment]
https://github.com/tabulapdf/tabula-java can process multiple identically-formatted PDFs into multiple spreadsheets. (tabula-java is the command-line version of the extraction engine that powers Tabula). I think there's been some movement about putting templated processing of multiple PDFs into mainline Tabula, but we're not there _yet_.
