### ISSUE TITLE
Deploy on production server

### ISSUE THREAD

**Issue by TonyGan329** [tabulapdf/tabula#883]
I have no trouble for starting development server on my local machine.
Do you have any idea or a quick way on how to deploy Tabula with Jruby on production server for non-commercial use? Many thanks.

**Comment by jazzido** [comment]
Hi @TonyGan329,

Tabula is a standard JRuby+Rack application, you can easily deploy it to a server. There's information in our README about how to run in on Linux. 

There's also a `Dockerfile`, although I don't know what its current state.
