### ISSUE TITLE
Problem with Tabula

### ISSUE THREAD

**Issue by ND83** [tabulapdf/tabula#927]
Hello
I receive many forms I created under Acrbat Pro ; I want to extract datas to use them in xls files. I found many discussions talking of your product ; I tried it on my Mac and my PC. 
I select all the part of the form containing datas and ask to preview : the preview returns me all the labels but not any data _ Perhaps a bad usage ?
I attach a pdf file.
Thansks for your help 
Noël
[formulaire_test_rempli.pdf](https://github.com/tabulapdf/tabula/files/2420057/formulaire_test_rempli.pdf)

**Comment by jeremybmerrill** [comment]
The data is all in PDF form fields. We don't support PDF form field data.

It appears PDFBox supports this, so if someone wanted to modify tabula-java to extract PDF form field data, that'd be an interesting enhancement.
