### ISSUE TITLE
Multi-lingual

### ISSUE THREAD

**Issue by ryankaltenbach** [tabulapdf/tabula#937]
Does Tabula work with multiple languages? when I export the table as a .csv it doesn't properly translate in excel. The copy to clip board button is also grey out. Thank you,

**Comment by jeremybmerrill** [comment]
Tabula successfully outputs UTF-8 encoded text across many languages and writing systems, whether Chinese/Japanese/Korean, Arabic/Farsi, Hebrew, or Indian languages like Hindi and Marathi.

If Tabula correctly displays the text in the Tabula browser window, but the text looks different when you open it in Microsoft Excel, you have an Excel problem. You'll have to tell Excel specifically to open the CSV with UTF-8 encoding. Here's a guide for Excel 2007 on Windows, you may have to find a different one for your version of Excel: https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0
