### ISSUE TITLE
Page Border breaking Continuous Table

### ISSUE THREAD

**Issue by NathanHodges** [tabulapdf/tabula#943]
I have a pdf with hundreds of pages, but just one table that spans them and I would like to create a csv file from it. I imported the pdf into tabula and selected auto detect tables the result produced errors at page borders where the table continues, but the page breaks. I tried resizing the content of the page and merging pages to reduce number of errors, but I have issues with not being able to change page sizes. 

Ideally I would take x pages of length L and merge them onto a single page of length x*L and have tablula look at the one table. 

[genuine-parts.pdf](https://github.com/tabulapdf/tabula/files/2540138/genuine-parts.pdf)

**Comment by jeremybmerrill** [comment]
Yes, you can do this (and I know it has worked in the past), but you have to do it with other software, not with Tabula.
