### ISSUE TITLE
How to read special characters from a table

### ISSUE THREAD

**Issue by unterzwerg** [tabulapdf/tabula#963]
I want to read tables that have columns with wingdings(?)-font; e.g. circled numbers, bullets, ...

**Comment by jeremybmerrill** [comment]
If they're real Wingdings, then you should just change the font of the resulting PDF to Wingdings. (i.e. in Wingdings, the circled number glyph may represent, e.g., the `a` character. Tabula will then extract `a` and it's up to you to tell your CSV viewer program to represent that with the Wingdings font)
