### ISSUE TITLE
Problem with uploading pdf's via REST.

### ISSUE THREAD

**Issue by lovrokneze** [tabulapdf/tabula#966]
Hi, 
I am trying to upload .pdf files to tabula via REST service.
In my exploration i found out that this is the link on tabula expects a POST call to import .pdf.

**http://127.0.0.1:8080/upload.json** (tabula is run locally)

I recreated the heading's from Request Headers in chrome inspect tool.

Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 26639 (size of my pdf)
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary9mOlgdCkDgGfAnrr
Host: 127.0.0.1:8080
Origin: http://127.0.0.1:8080
Referer: http://127.0.0.1:8080/
X-Requested-With: XMLHttpRequest

**Also as a body I included my pdf file as binary.**

My question is is it possible to do something like this, **beacue i get 404 all the time.**

Thanks!

**Comment by jazzido** [comment]
Hi @lovrokneze,

The `/upload.json` is meant to be used from a browser, so it expects a `multipart/form-data` payload. [This StackOverflow answer](https://stackoverflow.com/questions/12667797/using-curl-to-upload-post-data-with-files) shows how to do it with `curl`.

Thanks!
