### ISSUE TITLE
More than one table in a document

### ISSUE THREAD

**Issue by mmicoski** [tabulapdf/tabula#978]
Hello, I am trying to convert a PDF that contains multiple nested tables, and it is not working.
I managed to convert one table when I select just it, but if I go with de default selections, that covers the entire table area, the result is wrong.

The document I am trying to convert if from Official Government Diary, that is open in Internet, for exemple the one below.

https://www.imprensaoficial.com.br/DO/BuscaDO2001Documento_11_4.aspx?link=%2f2012%2fempresarial%2ffevereiro%2f16%2fpag_0005_8HBIFCNOH5JF4e90U1JNETH84LI.pdf&pagina=5&data=16/02/2012&caderno=Empresarial&paginaordenacao=100005

Is there any way of getting the entire table correct in a more automated way?

Thanks,

Mauricio

**Comment by jeremybmerrill** [comment]
Table autodetection is not perfect. I recommend experimenting with saving templates or with scripting to solve this problem. Using one of the wrappers for Tabula in your programming language of choice, you can autodetect tables and discard the outermost box, which should give you the result you're looking for.
